import {apiClient} from './api-client.js';
import {employeeForm,submitEmployee} from './employee-form.js';
import {taskForm,submitTask} from './task-form.js';
const state={section:'dashboard',employees:[],tasks:[],approvals:[],workflows:[],integrations:[],audit:[],loading:false,error:null};
const $=s=>document.querySelector(s);const workspaceId=window.ENJAZ_WORKSPACE_ID||'';const token=window.ENJAZ_ACCESS_TOKEN||'';
const nav=[['dashboard','لوحة التحكم'],['employees','الموظفون الرقميون'],['tasks','المهام'],['teams','الفرق الذكية'],['workflows','سير العمل'],['approvals','الموافقات'],['integrations','التكاملات'],['audit','سجل التدقيق']];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const status=v=>`<span class="status">${esc(v||'—')}</span>`;
async function load(){if(!workspaceId||!token)return;state.loading=true;state.error=null;render();try{const [e,t,a,w,i,d]=await Promise.all([apiClient.employees(workspaceId,token),apiClient.tasks(workspaceId,token),apiClient.approvals(workspaceId,token),apiClient.workflows(workspaceId,token),apiClient.integrations(workspaceId,token),apiClient.audit(workspaceId,token)]);state.employees=e.data||[];state.tasks=t.data||[];state.approvals=a.data||[];state.workflows=w.data||[];state.integrations=i.data||[];state.audit=d.data||[]}catch(e){state.error=e.message}finally{state.loading=false;render()}}
function render(){const title=nav.find(x=>x[0]===state.section)?.[1]||'لوحة التحكم';const pages={dashboard,dashboardPage:dashboard,employees:employeesPage,tasks:tasksPage,teams:teamsPage,workflows:workflowsPage,approvals:approvalsPage,integrations:integrationsPage,audit:()=>listPage(title)};$('#content').innerHTML=(pages[state.section]||dashboard)();document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{state.section=b.dataset.nav;render()});document.querySelectorAll('[data-action="create-employee"]').forEach(b=>b.onclick=openEmployeeForm);document.querySelectorAll('[data-action="create-task"]').forEach(b=>b.onclick=openTaskForm);document.querySelectorAll('[data-action="employees"]').forEach(b=>b.onclick=()=>{state.section='employees';render()});document.querySelectorAll('[data-action="refresh"]').forEach(b=>b.onclick=load);document.querySelectorAll('[data-run-task]').forEach(b=>b.onclick=()=>runTask(b.dataset.runTask,b.dataset.employeeId));document.querySelectorAll('[data-approval-decision]').forEach(b=>b.onclick=()=>decideApproval(b.dataset.approvalDecision,b.dataset.approvalId));}
function shell(head,body,action=''){return `<div class="pagehead"><div><div class="eyebrow">ENJAZ / AI WORKFORCE</div><h1>${head}</h1></div>${action}</div><div class="panel">${body}</div>`}
function dashboard(){return `<div class="hero"><div><div class="eyebrow">ENJAZ / AI WORKFORCE</div><h1>مركز قيادة القوى العاملة الرقمية</h1><p>${workspaceId&&token?'بيانات حقيقية من مساحة العمل':'وضع المعاينة — اربط مساحة العمل والمصادقة'}.</p></div><button class="primary" data-action="employees">+ موظف جديد</button></div>${state.error?`<div class="error">${esc(state.error)}</div>`:''}<div class="stats"><div><span>الموظفون</span><b>${state.employees.length}</b></div><div><span>المهام</span><b>${state.tasks.length}</b></div><div><span>سير العمل</span><b>${state.workflows.length}</b></div><div><span>الموافقات</span><b>${state.approvals.length}</b></div></div><div class="panel"><div class="pagehead"><div><h2>بدء العمل</h2><p>أنشئ موظفًا رقميًا ثم أنشئ أول مهمة له.</p></div><button class="primary" data-action="create-task" ${state.employees.length?'':'disabled'}>+ إنشاء مهمة</button></div></div>`}
function employeesPage(){const rows=state.employees.map(x=>`<article><strong>${esc(x.name||'موظف AI')}</strong><span>${esc(x.role||'')} ${status(x.status)}</span></article>`).join('');return shell('الموظفون الرقميون',rows||`<div class="empty"><h2>ابدأ ببناء فريقك الرقمي</h2><button class="primary" data-action="create-employee">إنشاء أول موظف</button></div>`,'<button class="primary" data-action="create-employee">+ إنشاء موظف AI</button>')}
function teamsPage(){return shell('الفرق الذكية',state.employees.map(x=>`<article><strong>✦ ${esc(x.name)}</strong><span>${esc(x.role||'')} ${status(x.status)}</span></article>`).join('')||'<div class="empty"><h2>لا يوجد فريق بعد</h2></div>','<button class="ghost" data-action="refresh">تحديث</button>')}
function tasksPage(){const rows=state.tasks.map(x=>`<article><strong>${esc(x.title||'مهمة')}</strong><span>${status(x.status)} · ${esc(state.employees.find(e=>e.id===x.employee_id)?.name||x.employee_id||'غير محدد')} ${x.status==='queued'?`<button class="ghost compact" data-run-task="${esc(x.id)}" data-employee-id="${esc(x.employee_id||'')}">تشغيل</button>`:''}</span></article>`).join('');return shell('المهام',rows||'<div class="empty"><h2>لا توجد مهام بعد</h2></div>','<div><button class="ghost" data-action="refresh">تحديث</button> <button class="primary" data-action="create-task" '+(state.employees.length?'':'disabled')+'>+ إنشاء مهمة</button></div>')}
function approvalsPage(){const rows=state.approvals.map(x=>`<article><strong>${esc(x.reason||x.action||'طلب موافقة')}</strong><span>${status(x.status)} ${x.status==='pending'?`<button class="ghost compact" data-approval-decision="approve" data-approval-id="${esc(x.id)}">موافقة</button><button class="ghost compact" data-approval-decision="reject" data-approval-id="${esc(x.id)}">رفض</button>`:''}</span></article>`).join('');return shell('الموافقات',rows||'<div class="empty"><h2>لا توجد موافقات معلقة</h2></div>','<button class="ghost" data-action="refresh">تحديث</button>')}
function workflowsPage(){return shell('سير العمل',state.workflows.map(x=>`<article><strong>${esc(x.goal||'سير عمل')}</strong><span>${status(x.status)} · ${x.succeeded_steps||0}/${x.step_count||0} خطوات</span></article>`).join('')||'<div class="empty"><h2>لا توجد تنفيذات بعد</h2></div>','<button class="ghost" data-action="refresh">تحديث</button>')}
function integrationsPage(){return shell('التكاملات',state.integrations.map(x=>`<article><strong>${esc(x.name||x.provider)}</strong><span>${esc(x.provider)} · ${x.enabled?'مفعّل':'معطّل'}</span></article>`).join('')||'<div class="empty"><h2>لا توجد تكاملات</h2><p>بيانات الاعتماد السرية لا تُعرض.</p></div>','<button class="ghost" data-action="refresh">تحديث</button>')}
function listPage(title){const rows=state.audit.map(x=>`<article><strong>${esc(x.action||x.event_type||'سجل')}</strong><span>${status(x.created_at)}</span></article>`).join('');return shell(title,rows||'<div class="empty"><h2>لا توجد بيانات بعد</h2></div>')}
async function runTask(id,employeeId){if(!employeeId)return alert('المهمة غير مرتبطة بموظف.');try{await apiClient.runTask(workspaceId,token,id,{employeeId,action:'data.analyze',input:{}});await load()}catch(e){alert(e.message)}}
async function decideApproval(decision,id){try{await apiClient.decideApproval(workspaceId,token,id,decision);await load()}catch(e){alert(e.message)}}
function openEmployeeForm(){const el=document.createElement('div');el.className='modal';el.innerHTML=`<div class="modal-card"><header><h2>إنشاء موظف AI</h2><button class="ghost" id="close" type="button">×</button></header>${employeeForm()}</div>`;document.body.appendChild(el);el.querySelector('#close').onclick=()=>el.remove();el.querySelector('#cancel-employee').onclick=()=>el.remove();el.querySelector('#employee-form').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('[type=submit]');b.disabled=true;try{await submitEmployee(e.currentTarget,{workspaceId,token,apiClient});el.remove();state.section='employees';await load()}catch(err){b.disabled=false;alert(err.message)}}}
function openTaskForm(){const el=document.createElement('div');el.className='modal';el.innerHTML=`<div class="modal-card"><header><h2>إنشاء مهمة</h2><button class="ghost" id="close" type="button">×</button></header>${taskForm(state.employees)}</div>`;document.body.appendChild(el);el.querySelector('#close').onclick=()=>el.remove();el.querySelector('#cancel-task').onclick=()=>el.remove();el.querySelector('#task-form').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('[type=submit]');b.disabled=true;try{await submitTask(e.currentTarget,{workspaceId,token,apiClient});el.remove();state.section='tasks';await load()}catch(err){b.disabled=false;alert(err.message)}}}
render();load();