const state={section:'dashboard',employees:[],tasks:[],approvals:[],audit:[],loading:false,error:null};
const $=s=>document.querySelector(s);
const navItems=[['dashboard','لوحة التحكم'],['employees','الموظفون الرقميون'],['tasks','المهام'],['teams','الفرق الذكية'],['workflows','سير العمل'],['approvals','الموافقات'],['integrations','التكاملات'],['audit','سجل التدقيق']];
const workspaceId=window.ENJAZ_WORKSPACE_ID||'';const token=window.ENJAZ_ACCESS_TOKEN||'';
async function load(){if(!workspaceId||!token)return;state.loading=true;try{[state.employees,state.tasks,state.approvals,state.audit]=await Promise.all([apiClient.employees(workspaceId,token).then(x=>x.data||[]),apiClient.tasks(workspaceId,token).then(x=>x.data||[]),apiClient.approvals(workspaceId,token).then(x=>x.data||[]),apiClient.audit(workspaceId,token).then(x=>x.data||[])])}catch(e){state.error=e.message}finally{state.loading=false;render()}}
function render(){const title=navItems.find(x=>x[0]===state.section)?.[1]||'لوحة التحكم';$('#content').innerHTML=state.section==='dashboard'?dashboard():listPage(title);document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{state.section=b.dataset.nav;render()});}
function dashboard(){const live=workspaceId&&token?'بيانات حقيقية من مساحة العمل':'وضع المعاينة — أضف بيانات المصادقة';return `<div class="hero"><div><div class="eyebrow">ENJAZ / AI WORKFORCE</div><h1>مركز قيادة القوى العاملة الرقمية</h1><p>${live}. أنشئ موظفين أذكياء، امنحهم الأدوات والصلاحيات، ودعهم ينجزون العمل مع بقاء القرار تحت سيطرتك.</p></div><button class="primary" onclick="state.section='tasks';render()">+ مهمة جديدة</button></div>${state.error?`<div class="error">${state.error}</div>`:''}<div class="stats"><div><span>الموظفون</span><b>${state.employees.length}</b><small>موظف رقمي</small></div><div><span>المهام</span><b>${state.tasks.length}</b><small>في مساحة العمل</small></div><div><span>الموافقات</span><b>${state.approvals.length}</b><small>تحتاج قرارًا</small></div><div><span>النشاط</span><b>${state.audit.length}</b><small>سجل تدقيق</small></div></div><div class="panel activity"><header><h2>النشاط والتشغيل</h2><span class="live">● ${state.loading?'SYNC':'READY'}</span></header>${state.audit.slice(0,6).map(x=>`<p>${x.created_at||''} — ${x.action||x.event_type||'حدث تشغيلي'}</p>`).join('')||'<p class="muted">لا توجد أحداث بعد.</p>'}</div>`}
function listPage(title){let items=state.section==='employees'?state.employees:state.section==='tasks'?state.tasks:state.section==='approvals'?state.approvals:state.section==='audit'?state.audit:[];return `<div class="pagehead"><div><div class="eyebrow">ENJAZ CONTROL CENTER</div><h1>${title}</h1><p>بيانات مساحة العمل الحالية.</p></div><button class="primary" onclick="state.section='tasks';render()">+ إنشاء مهمة</button></div><div class="panel"><div class="rows">${items.length?items.map(x=>`<article><strong>${x.name||x.title||x.action||x.event_type||'سجل'}</strong><span>${x.status||x.role||x.created_at||''}</span></article>`).join(''):'<div class="empty"><div class="bigicon">✦</div><h2>لا توجد بيانات بعد</h2><p>ابدأ بإنشاء أول موظف أو مهمة في مساحة العمل.</p></div>'}</div></div>`}
load();render();
