const supabaseUrl=window.ENJAZ_SUPABASE_URL||import.meta.env?.VITE_ENJAZ_SUPABASE_URL||'https://cqmwwrrmmqmgpnhnuxyu.supabase.co';
const supabaseKey=window.ENJAZ_SUPABASE_ANON_KEY||window.ENJAZ_SUPABASE_KEY||import.meta.env?.VITE_ENJAZ_SUPABASE_ANON_KEY||'sb_publishable_U12modLyDRQWV2sNAJHiqg_vJPOSoOz';
const configured=Boolean(supabaseUrl&&supabaseKey);
const key='ENJAZ_ACCESS_TOKEN';
const refreshKey='ENJAZ_REFRESH_TOKEN';
const jsonHeaders={'Content-Type':'application/json','apikey':supabaseKey};
const REQUEST_TIMEOUT=12000;
const cleanEmail=v=>String(v||'').trim().toLowerCase();
const authMessage=data=>{const code=data?.code||data?.error||'';const map={invalid_credentials:'البريد الإلكتروني أو كلمة المرور غير صحيحة.',email_not_confirmed:'لا يمكن تسجيل الدخول بهذا الحساب قبل تفعيل البريد الإلكتروني.',user_already_exists:'هذا البريد الإلكتروني مسجل بالفعل.',email_exists:'هذا البريد الإلكتروني مسجل بالفعل.',too_many_requests:'تم تجاوز عدد المحاولات. انتظر قليلًا ثم حاول مرة أخرى.',weak_password:'كلمة المرور لا تستوفي متطلبات الأمان.'};return map[code]||data?.error_description||data?.msg||data?.message||'تعذر إكمال عملية الدخول.'};
async function request(url,options={}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT);try{return await fetch(url,{...options,signal:controller.signal})}catch(error){if(error?.name==='AbortError')throw new Error('انتهت مهلة الاتصال بالخدمة. حاول مرة أخرى.');throw error}finally{clearTimeout(timer)}}
async function authRequest(path,body){if(!configured)throw new Error('إعدادات المصادقة غير متاحة.');let r;try{r=await request(`${supabaseUrl}/auth/v1/${path}`,{method:'POST',headers:jsonHeaders,body:JSON.stringify(body)});}catch(error){throw new Error(error?.message||'تعذر الاتصال بخدمة المصادقة. تحقق من اتصال الإنترنت ثم حاول مرة أخرى.')}const data=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(authMessage(data));e.code=data?.code||data?.error||'';e.status=r.status;throw e}return data;}
async function bridgeRequest(action,body={}){if(!configured)throw new Error('إعدادات المصادقة غير متاحة.');let r;try{r=await request(`${supabaseUrl}/functions/v1/enjaz-auth-bridge`,{method:'POST',headers:jsonHeaders,body:JSON.stringify({action,...body})});}catch(error){throw new Error(error?.message||'تعذر الاتصال بخدمة إنشاء الحساب. تحقق من اتصال الإنترنت ثم حاول مرة أخرى.')}const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data?.error||'تعذر إنشاء الحساب.');return data;}
function store(data){if(data?.access_token)sessionStorage.setItem(key,data.access_token);if(data?.refresh_token)sessionStorage.setItem(refreshKey,data.refresh_token);window.ENJAZ_ACCESS_TOKEN=data?.access_token||sessionStorage.getItem(key)||'';}
async function refresh(){const rt=sessionStorage.getItem(refreshKey)||'';if(!rt)return false;try{const data=await authRequest('token?grant_type=refresh_token',{refresh_token:rt});store(data);return Boolean(data.access_token)}catch{return false}}
async function gatewayRequest(apiBase,path,options={}){let token=this.token();let r;try{r=await request(`${String(apiBase||'').replace(/\/$/,'')}${path}`,{...options,headers:{'Content-Type':'application/json',...(options.headers||{}),Authorization:`Bearer ${token}`}})}catch(error){throw new Error(error?.message||'تعذر الاتصال بخدمة إنجاز. تحقق من اتصال الإنترنت ثم حاول مرة أخرى.')}if(r.status===401&&await refresh()){token=this.token();r=await request(`${String(apiBase||'').replace(/\/$/,'')}${path}`,{...options,headers:{'Content-Type':'application/json',...(options.headers||{}),Authorization:`Bearer ${token}`}})}return r}
export const authClient={
 configured,
 token:()=>sessionStorage.getItem(key)||'',
 async signIn(email,password){const data=await authRequest('token?grant_type=password',{email:cleanEmail(email),password});store(data);return data;},
 async signUp(email,password,name){const cleanName=String(name||'').trim();await bridgeRequest('signup',{email:cleanEmail(email),password,name:cleanName});const session=await this.signIn(email,password);return {data:session,needsEmailConfirmation:false};},
 async resendConfirmation(email){return authRequest('resend',{type:'signup',email:cleanEmail(email),options:{email_redirect_to:`${location.origin}${location.pathname}`}})},
 signOut(){sessionStorage.removeItem(key);sessionStorage.removeItem(refreshKey);sessionStorage.removeItem('ENJAZ_USER_PROFILE');sessionStorage.removeItem('ENJAZ_WORKSPACES');sessionStorage.removeItem('ENJAZ_ACCESS_TOKEN');localStorage.removeItem('ENJAZ_WORKSPACE_ID');window.ENJAZ_ACCESS_TOKEN='';},
 async bootstrap(apiBase,{name,organizationName,workspaceName}){if(!apiBase)throw new Error('خدمة تهيئة مساحة العمل غير متاحة حاليًا.');const payload={name,organizationName,workspaceName};let r=await gatewayRequest.call(this,apiBase,'/api/v1/onboarding/bootstrap',{method:'POST',body:JSON.stringify(payload)});let data=await r.json().catch(()=>({}));if(r.ok)return data.data;if(r.status===403&&/profile|provisioned|not found/i.test(String(data.error||''))){const bridge=`${supabaseUrl}/functions/v1/enjaz-auth-bridge`;const br=await request(bridge,{method:'POST',headers:{...jsonHeaders,Authorization:`Bearer ${this.token()}`},body:JSON.stringify({action:'bootstrap',...payload})});const bd=await br.json().catch(()=>({}));if(br.ok)return bd.data;if(br.status===409){const existing=await this.me(apiBase);if(existing?.workspaces?.length)return existing;};throw new Error(bd.error||'تعذر تهيئة حساب الشركة');}throw new Error(data.error||'تعذر إنشاء مساحة العمل');},
 async me(apiBase){let token=this.token();if(!token)return null;if(!apiBase)return {user:{id:null},workspaces:[]};let r=await gatewayRequest.call(this,apiBase,'/api/v1/auth/me',{headers:{Authorization:`Bearer ${token}`}});if(r.status===401){this.signOut();return null}const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'تعذر قراءة جلسة المستخدم');return data.data}
};
