const supabaseUrl=window.ENJAZ_SUPABASE_URL||import.meta.env?.VITE_ENJAZ_SUPABASE_URL||'https://cqmwwrrmmqmgpnhnuxyu.supabase.co';
const supabaseKey=window.ENJAZ_SUPABASE_ANON_KEY||window.ENJAZ_SUPABASE_KEY||import.meta.env?.VITE_ENJAZ_SUPABASE_ANON_KEY||'sb_publishable_U12modLyDRQWV2sNAJHiqg_vJPOSoOz';
const configured=Boolean(supabaseUrl&&supabaseKey);
const key='ENJAZ_ACCESS_TOKEN';
const refreshKey='ENJAZ_REFRESH_TOKEN';
const jsonHeaders={'Content-Type':'application/json','apikey':supabaseKey};
const cleanEmail=v=>String(v||'').trim().toLowerCase();
const authMessage=data=>{const code=data?.code||data?.error||'';const map={invalid_credentials:'البريد الإلكتروني أو كلمة المرور غير صحيحة.',email_not_confirmed:'يجب تأكيد البريد الإلكتروني قبل تسجيل الدخول.',user_already_exists:'هذا البريد الإلكتروني مسجل بالفعل.',email_exists:'هذا البريد الإلكتروني مسجل بالفعل.',too_many_requests:'تم تجاوز عدد المحاولات. انتظر قليلًا ثم حاول مرة أخرى.',weak_password:'كلمة المرور لا تستوفي متطلبات الأمان.'};return map[code]||data?.error_description||data?.msg||data?.message||'تعذر إكمال عملية الدخول.'};
async function authRequest(path,body){if(!configured)throw new Error('إعدادات المصادقة غير متاحة.');let r;try{r=await fetch(`${supabaseUrl}/auth/v1/${path}`,{method:'POST',headers:jsonHeaders,body:JSON.stringify(body)});}catch{throw new Error('تعذر الاتصال بخدمة المصادقة. تحقق من اتصال الإنترنت ثم حاول مرة أخرى.')}const data=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(authMessage(data));e.code=data?.code||data?.error||'';e.status=r.status;throw e}return data;}
function store(data){if(data?.access_token)sessionStorage.setItem(key,data.access_token);if(data?.refresh_token)sessionStorage.setItem(refreshKey,data.refresh_token);window.ENJAZ_ACCESS_TOKEN=data?.access_token||sessionStorage.getItem(key)||'';}
async function refresh(){const rt=sessionStorage.getItem(refreshKey)||'';if(!rt)return false;try{const data=await authRequest('token?grant_type=refresh_token',{refresh_token:rt});store(data);return Boolean(data.access_token)}catch{return false}}
export const authClient={
 configured,
 token:()=>sessionStorage.getItem(key)||'',
 async signIn(email,password){const data=await authRequest('token?grant_type=password',{email:cleanEmail(email),password});store(data);return data;},
 async signUp(email,password,name){const data=await authRequest('signup',{email:cleanEmail(email),password,data:{full_name:String(name||'').trim()},options:{email_redirect_to:`${location.origin}${location.pathname}`}});store(data);return {data,needsEmailConfirmation:!data.access_token};},
 signOut(){sessionStorage.removeItem(key);sessionStorage.removeItem(refreshKey);sessionStorage.removeItem('ENJAZ_USER_PROFILE');sessionStorage.removeItem('ENJAZ_WORKSPACES');sessionStorage.removeItem('ENJAZ_ACCESS_TOKEN');localStorage.removeItem('ENJAZ_WORKSPACE_ID');window.ENJAZ_ACCESS_TOKEN='';},
 async bootstrap(apiBase,{name,organizationName,workspaceName}){if(!apiBase)throw new Error('خدمة تهيئة مساحة العمل غير متاحة حاليًا.');const token=this.token();const r=await fetch(`${apiBase}/api/v1/onboarding/bootstrap`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({name,organizationName,workspaceName})});const data=await r.json().catch(()=>({}));if(r.status===401&&await refresh())return this.bootstrap(apiBase,{name,organizationName,workspaceName});if(!r.ok)throw new Error(data.error||'تعذر إنشاء مساحة العمل');return data.data;},
 async me(apiBase){let token=this.token();if(!token)return null;if(!apiBase)return {user:{id:null},workspaces:[]};let r=await fetch(`${apiBase}/api/v1/auth/me`,{headers:{Authorization:`Bearer ${token}`}});if(r.status===401&&await refresh()){token=this.token();r=await fetch(`${apiBase}/api/v1/auth/me`,{headers:{Authorization:`Bearer ${token}`}})}if(r.status===401){this.signOut();return null}const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'تعذر قراءة جلسة المستخدم');return data.data;}
};
