import {authClient} from './auth-client.js';
import {apiClient} from './api-client.js';

const root=document.querySelector('.enjaz-root');
const q=new URLSearchParams(location.search);
const apiBase=window.ENJAZ_API_BASE||'';
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const mount=html=>{let el=document.getElementById('auth-gate');if(!el){el=document.createElement('div');el.id='auth-gate';document.body.appendChild(el)}el.innerHTML=html;return el};
const clearGate=()=>{document.getElementById('auth-gate')?.remove();root?.classList.remove('is-auth-locked')};
const isSignup=()=>q.get('signup')==='1';
let resolveAuthReady;
window.__ENJAZ_AUTH_STATE__='resolving';
window.__ENJAZ_AUTH_READY__=new Promise(resolve=>{resolveAuthReady=resolve});
const setAuthState=state=>{window.__ENJAZ_AUTH_STATE__=state;resolveAuthReady?.(state);resolveAuthReady=null};
const goAuth=signup=>{const url=new URL(location.href);url.search='';url.searchParams.set('auth','1');if(signup)url.searchParams.set('signup','1');history.replaceState({},'',url.toString());renderForm()};

const form=({signup=isSignup(),error='' }={})=>mount(`<div class="auth-shell"><div class="auth-card"><div class="auth-brand"><span class="brand-mark"><i></i><i></i><i></i></span><div><strong>إنجاز</strong><small>ENJAZ · DIGITAL WORKFORCE</small></div></div><div class="auth-copy"><div class="eyebrow">${signup?'START YOUR WORKFORCE':'SECURE WORKSPACE'}</div><h1>${signup?'ابنِ قوة العمل الرقمية لشركتك':'مرحبًا بعودتك'}</h1><p>${signup?'أنشئ حسابك ثم سنقودك خطوة بخطوة لتأسيس مؤسستك وتفعيل قوة العمل المناسبة لقطاعك.':'سجّل الدخول للوصول إلى قوة العمل الرقمية وبيانات شركتك.'}</p></div>${error?`<div class="auth-error" role="alert">${esc(error)}</div>`:''}<form id="auth-form">${signup?'<label>الاسم<input name="name" required autocomplete="name" placeholder="اسمك الكامل"></label>':''}<label>البريد الإلكتروني<input name="email" type="email" required autocomplete="email" placeholder="name@company.com"></label><label>كلمة المرور<input name="password" type="password" required minlength="8" autocomplete="${signup?'new-password':'current-password'}" placeholder="••••••••"></label><button class="primary auth-submit" type="submit">${signup?'إنشاء الحساب':'تسجيل الدخول'}</button></form><div class="auth-switch">${signup?'لديك حساب بالفعل؟':'ليس لديك حساب؟'} <button id="auth-switch" class="link-button" type="button">${signup?'تسجيل الدخول':'إنشاء حساب'}</button></div><div class="auth-secure">● جلسة آمنة · عزل بيانات المؤسسة · صلاحيات حسب الدور</div></div></div>`);

const sectorOptions=[
 ['restaurants','المطاعم','تشغيل الفروع، الطلبات، المخزون، المشتريات، الجودة وخدمة العملاء.','مطاعم'],
 ['hospitals','المستشفيات','إدارة المواعيد، التنسيق التشغيلي، الجودة، المرضى والعمليات.','مستشفيات'],
 ['hotels','الفنادق','الضيافة، الحجوزات، التشغيل، خدمة النزلاء والجودة.','فنادق'],
 ['companies','الشركات','المبيعات، العمليات، الموارد، خدمة العملاء، المالية والتقارير.','شركات'],
 ['government','الجهات الحكومية','الخدمات، المعاملات، الامتثال، المتابعة، الجودة والتقارير.','جهات حكومية'],
 ['ecommerce','التجارة الإلكترونية','المنتجات، الطلبات، المخزون، التسعير، التسويق وخدمة العملاء.','متاجر إلكترونية']
];

const workspaceSetup=async profile=>{
 const safeProfile=profile&&typeof profile==='object'?profile:{};
 const el=mount(`<div class="auth-shell"><div class="auth-card onboarding-card onboarding-enterprise"><div class="auth-brand"><span class="brand-mark"><i></i><i></i><i></i></span><div><strong>إنجاز</strong><small>ENTERPRISE ACTIVATION</small></div></div><div class="auth-copy"><div class="eyebrow">01 / ORGANIZATION</div><h1>أسّس بيئة العمل الصحيحة</h1><p>ابدأ بالمؤسسة والقطاع. بعد ذلك يجهّز إنجاز حزمة القوى العاملة الرقمية المتخصصة بدل أن تبدأ ببناء الموظفين واحدًا واحدًا.</p></div><form id="workspace-form"><div class="onboarding-section-label">هوية المؤسسة</div><div class="onboarding-fields"><label>اسم المؤسسة<input name="organizationName" required maxlength="120" placeholder="مثال: شركة إنجاز للتشغيل"></label><label>اسم مساحة العمل<input name="workspaceName" required maxlength="80" placeholder="مثال: العمليات الرئيسية"></label></div><div class="onboarding-section-label">اختر قطاع المؤسسة</div><div class="sector-choice-grid">${sectorOptions.map(([id,title,desc,short],i)=>`<label class="sector-choice"><input type="radio" name="sector" value="${id}" ${i===0?'checked':''}><span class="sector-choice-mark">${esc(short.charAt(0))}</span><span><strong>${esc(title)}</strong><small>${esc(desc)}</small></span><i>✓</i></label>`).join('')}</div><button class="primary auth-submit" type="submit">إنشاء المؤسسة وتفعيل القطاع ←</button></form><div class="auth-secure">سيتم إنشاء المؤسسة أولًا ثم تفعيل حزمة القطاع بشكل آمن. يمكنك إدارة الفروع والأدوار لاحقًا من مركز القيادة.</div></div></div>`);
 el.querySelector('#workspace-form')?.addEventListener('submit',async e=>{
  e.preventDefault();
  const b=new FormData(e.currentTarget),btn=e.currentTarget.querySelector('button');
  btn.disabled=true;btn.textContent='جارٍ تأسيس بيئة المؤسسة…';
  try{
   const sector=String(b.get('sector')||'restaurants');
   const data=await authClient.bootstrap(apiBase,{name:safeProfile.identity?.name||safeProfile.user?.name||'',organizationName:b.get('organizationName'),workspaceName:b.get('workspaceName'),sector});
   const workspaces=Array.isArray(data?.workspaces)?data.workspaces:[];
   const workspace=workspaces[0]||data?.workspace;
   if(!workspace)throw new Error('لم يتم إنشاء مساحة العمل.');
   localStorage.setItem('ENJAZ_WORKSPACE_ID',workspace.id);
   sessionStorage.setItem('ENJAZ_WORKSPACES',JSON.stringify(workspaces.length?workspaces:[{...workspace,role:data.role||workspace.workspace_role||'owner'}]));
   sessionStorage.setItem('ENJAZ_ONBOARDING_SECTOR',sector);
   window.ENJAZ_WORKSPACE_ID=workspace.id;window.ENJAZ_ACCESS_TOKEN=authClient.token();
   let provisioningError='';
   try{await apiClient.provisionIndustryPack(workspace.id,authClient.token(),sector);}
   catch(error){provisioningError=error?.message||'تعذر تفعيل حزمة القطاع تلقائيًا.';console.warn('[ENJAZ_ONBOARDING_PROVISION]',error)}
   setAuthState('authenticated');clearGate();
   if(provisioningError)sessionStorage.setItem('ENJAZ_ONBOARDING_NOTICE',provisioningError);
   window.location.reload();
  }catch(err){
   btn.disabled=false;btn.textContent='إنشاء المؤسسة وتفعيل القطاع ←';
   const old=el.querySelector('.auth-error');old?.remove();
   el.querySelector('.auth-card')?.insertAdjacentHTML('beforeend',`<div class="auth-error" role="alert">${esc(err?.message||'تعذر إنشاء مساحة العمل.')}</div>`)
  }
 });
};

const renderForm=({error='' }={})=>{const el=form({error});el.querySelector('#auth-switch')?.addEventListener('click',()=>goAuth(!isSignup()));el.querySelector('#auth-form')?.addEventListener('submit',async e=>{e.preventDefault();const b=new FormData(e.currentTarget),btn=e.currentTarget.querySelector('button');btn.disabled=true;btn.textContent=isSignup()?'جارٍ إنشاء الحساب…':'جارٍ تسجيل الدخول…';try{if(isSignup()){const result=await authClient.signUp(b.get('email'),b.get('password'),b.get('name'));if(result?.needsEmailConfirmation){const email=String(b.get('email')||'').trim().toLowerCase();mount(`<div class="auth-shell"><div class="auth-card"><div class="auth-brand"><span class="brand-mark"><i></i><i></i><i></i></span><div><strong>إنجاز</strong><small>ENJAZ · EMAIL VERIFICATION</small></div></div><div class="auth-copy"><div class="eyebrow">VERIFY YOUR EMAIL</div><h1>تحقق من بريدك الإلكتروني</h1><p>أرسلنا رسالة تأكيد إلى <strong>${esc(email)}</strong>. فعّل حسابك ثم سجّل الدخول.</p></div><button class="primary" id="go-login" type="button">الانتقال إلى تسجيل الدخول</button><button class="ghost" id="resend-confirmation" type="button" style="width:100%;margin-top:10px">إعادة إرسال رسالة التأكيد</button><div class="auth-secure">حسابك يبقى محميًا حتى يتم تأكيد البريد الإلكتروني.</div></div></div>`);document.getElementById('go-login')?.addEventListener('click',()=>goAuth(false));document.getElementById('resend-confirmation')?.addEventListener('click',async()=>{const button=document.getElementById('resend-confirmation');button.disabled=true;button.textContent='جارٍ الإرسال…';try{await authClient.resendConfirmation(email);button.textContent='تم إرسال الرسالة من جديد';}catch(error){button.disabled=false;button.textContent='إعادة إرسال رسالة التأكيد';const card=document.querySelector('#auth-gate .auth-card');card?.insertAdjacentHTML('beforeend',`<div class="auth-error" role="alert">${esc(error?.message||'تعذر إرسال الرسالة.')}</div>`);}});return;} }else await authClient.signIn(b.get('email'),b.get('password'));await recover()}catch(err){btn.disabled=false;btn.textContent=isSignup()?'إنشاء الحساب':'تسجيل الدخول';renderForm({error:err?.message||'تعذر إكمال العملية.'})}});return el};

async function recover(){try{const profile=await authClient.me(apiBase);if(!profile){authClient.signOut();setAuthState('public');window.location.href=location.origin+location.pathname;return}const memberships=Array.isArray(profile.workspaces)?profile.workspaces:[];if(!memberships.length){setAuthState('auth');await workspaceSetup(profile);return}const requested=q.get('workspaceId')||localStorage.getItem('ENJAZ_WORKSPACE_ID')||'';const selected=requested&&memberships.some(w=>String(w.id)===String(requested))?memberships.find(w=>String(w.id)===String(requested)):memberships[0];localStorage.setItem('ENJAZ_WORKSPACE_ID',selected.id);sessionStorage.setItem('ENJAZ_WORKSPACES',JSON.stringify(memberships));sessionStorage.setItem('ENJAZ_USER_PROFILE',JSON.stringify(profile));window.ENJAZ_WORKSPACE_ID=selected.id;window.ENJAZ_ACCESS_TOKEN=authClient.token();const enteredFromAuth=q.has('auth')||q.has('signup')||q.has('workspaceId');if(enteredFromAuth){const url=new URL(location.href);url.search='';history.replaceState({},'',url.toString())}setAuthState('authenticated');clearGate();window.dispatchEvent(new CustomEvent('enjaz:authenticated'));if(enteredFromAuth)window.location.reload();
}catch(err){setAuthState('error');const el=mount(`<div class="auth-shell"><div class="auth-card session-recovery"><div class="auth-brand"><span class="brand-mark">إ</span><div><strong>إنجاز</strong><small>ENJAZ · SESSION RECOVERY</small></div></div><div class="auth-copy"><div class="eyebrow">SESSION RECOVERY</div><h1>تعذر تحميل مساحة العمل</h1><p>لم نفقد حسابك. حاول استعادة الجلسة أو ابدأ من جديد.</p></div><div class="auth-error" role="alert">${esc(err?.message||'تعذر قراءة جلسة المستخدم.')}</div><div class="auth-recovery-actions"><button class="primary" id="retry-session" type="button">إعادة المحاولة</button><button class="ghost" id="reset-session" type="button">إعادة ضبط الجلسة</button></div></div></div>`);el.querySelector('#retry-session')?.addEventListener('click',()=>location.reload());el.querySelector('#reset-session')?.addEventListener('click',()=>{authClient.signOut();location.href=location.origin+location.pathname})}}

function renderPublic(){if(!root)return;root.innerHTML=\`
<section class="ez-landing" aria-label="إنجاز — قوة العمل الرقمية">
  <div class="ez-ambient ez-a1"></div><div class="ez-ambient ez-a2"></div>
  <header class="ez-nav">
    <div class="ez-logo"><span class="ez-logo-mark"><b></b><b></b><b></b></span><span><strong>إنجاز</strong><small>ENJAZ · WORKFORCE OS</small></span></div>
    <div class="ez-nav-links"><button type="button" data-scroll="workforce">القوة الرقمية</button><button type="button" data-scroll="sectors">القطاعات</button><button type="button" data-scroll="flow">كيف يعمل</button></div>
    <button type="button" class="ez-nav-login" data-public-login>تسجيل الدخول</button>
  </header>

  <main>
    <section class="ez-hero">
      <div class="ez-hero-copy">
        <div class="ez-eyebrow"><span class="ez-live"></span> DIGITAL WORKFORCE · LIVE</div>
        <h1>لا تبنِ فريقًا جديدًا.<br><span>فعّل قوة عمل.</span></h1>
        <p>موظفون رقميون متخصصون يعملون داخل مؤسستك — يخططون، ينفذون، يتابعون، ويتحققون من النتائج تحت حوكمة إنجاز.</p>
        <div class="ez-hero-actions"><button class="ez-cta" type="button" data-public-signup>ابدأ قوة عملك <b>←</b></button><button class="ez-play" type="button" data-scroll="workforce"><span>▶</span> شاهد كيف تعمل</button></div>
        <div class="ez-trust"><span>مصمم للمؤسسات</span><i></i><span>صلاحيات وحوكمة</span><i></i><span>تشغيل قابل للقياس</span></div>
      </div>
      <div class="ez-stage" id="ez-stage" aria-label="مشهد تفاعلي للقوة الرقمية">
        <div class="ez-grid"></div><div class="ez-orbit ez-o1"></div><div class="ez-orbit ez-o2"></div>
        <div class="ez-core"><span class="ez-core-ring"></span><strong>ENJAZ</strong><small>AI WORKFORCE</small><em>● LIVE</em></div>
        <button type="button" class="ez-node ez-node-1" data-scene="procurement"><span class="ez-node-icon">↗</span><b>المشتريات</b><small>يقارن الموردين</small><i>●</i></button>
        <button type="button" class="ez-node ez-node-2" data-scene="sales"><span class="ez-node-icon">↗</span><b>المبيعات</b><small>يدير العملاء</small><i>●</i></button>
        <button type="button" class="ez-node ez-node-3" data-scene="commerce"><span class="ez-node-icon">◇</span><b>التجارة الإلكترونية</b><small>يتابع الطلبات</small><i>●</i></button>
        <button type="button" class="ez-node ez-node-4" data-scene="operations"><span class="ez-node-icon">◌</span><b>العمليات</b><small>ينسق المهام</small><i>●</i></button>
        <div class="ez-scene-pop" id="ez-scene-pop" aria-live="polite"><small>LIVE MISSION</small><strong>تحليل المخزون</strong><span>تم اكتشاف انخفاض في 3 منتجات</span><em>EXECUTING · 82%</em></div>
      </div>
    </section>

    <section class="ez-logo-wall" aria-label="منظومة التكاملات">
      <div class="ez-wall-title">يعمل بجانب منظومتك التقنية</div>
      <div class="ez-marquee"><div class="ez-marquee-track">
        <div class="ez-company"><span class="ez-cmark openai">◉</span><b>OpenAI</b></div>
        <div class="ez-company"><span class="ez-cmark lovable">✦</span><b>Lovable</b></div>
        <div class="ez-company"><span class="ez-cmark shopify">S</span><b>Shopify</b></div>
        <div class="ez-company"><span class="ez-cmark stripe">≋</span><b>Stripe</b></div>
        <div class="ez-company"><span class="ez-cmark slack">#</span><b>Slack</b></div>
        <div class="ez-company"><span class="ez-cmark github">◖</span><b>GitHub</b></div>
        <div class="ez-company"><span class="ez-cmark salesforce">☁</span><b>Salesforce</b></div>
        <div class="ez-company"><span class="ez-cmark supabase">▲</span><b>Supabase</b></div>
        <div class="ez-company"><span class="ez-cmark openai">◉</span><b>OpenAI</b></div>
        <div class="ez-company"><span class="ez-cmark lovable">✦</span><b>Lovable</b></div>
        <div class="ez-company"><span class="ez-cmark shopify">S</span><b>Shopify</b></div>
        <div class="ez-company"><span class="ez-cmark stripe">≋</span><b>Stripe</b></div>
        <div class="ez-company"><span class="ez-cmark slack">#</span><b>Slack</b></div>
        <div class="ez-company"><span class="ez-cmark github">◖</span><b>GitHub</b></div>
      </div></div>
    </section>

    <section class="ez-workforce" id="workforce">
      <div class="ez-section-head"><div><span>THE DIGITAL WORKFORCE</span><h2>موظفون رقميون، وليسوا مجرد أدوات.</h2></div><p>كل موظف لديه دور، هدف، أدوات، صلاحيات وسجل تنفيذ — ويستطيع تسليم العمل لموظف آخر عندما تتطلب المهمة ذلك.</p></div>
      <div class="ez-card-stack">
        <article class="ez-work-card active" data-card="0"><div class="ez-card-top"><span class="ez-status">● يعمل الآن</span><small>EMPLOYEE 01</small></div><div class="ez-person"><span class="ez-avatar">م</span><div><strong>مدير المشتريات</strong><small>Procurement Manager</small></div></div><div class="ez-progress"><span></span></div><div class="ez-card-meta"><span>المهمة الحالية<strong>مقارنة 12 موردًا</strong></span><span>التوفير المتوقع<strong>18.4%</strong></span></div></article>
        <article class="ez-work-card" data-card="1"><div class="ez-card-top"><span class="ez-status">● جاهز للمهمة</span><small>EMPLOYEE 02</small></div><div class="ez-person"><span class="ez-avatar cyan">س</span><div><strong>موظف المبيعات</strong><small>AI Sales Executive</small></div></div><div class="ez-progress"><span style="width:68%"></span></div><div class="ez-card-meta"><span>العملاء اليوم<strong>48</strong></span><span>المواعيد<strong>11</strong></span></div></article>
        <article class="ez-work-card" data-card="2"><div class="ez-card-top"><span class="ez-status">● يراقب الآن</span><small>EMPLOYEE 03</small></div><div class="ez-person"><span class="ez-avatar green">ت</span><div><strong>مدير التجارة الإلكترونية</strong><small>E-commerce Manager</small></div></div><div class="ez-progress"><span style="width:91%"></span></div><div class="ez-card-meta"><span>الطلبات<strong>126</strong></span><span>تنبيهات المخزون<strong>3</strong></span></div></article>
      </div>
      <div class="ez-card-controls"><button type="button" data-card-prev>‹</button><div><span class="is-on"></span><span></span><span></span></div><button type="button" data-card-next>›</button></div>
    </section>

    <section class="ez-sectors" id="sectors">
      <div class="ez-section-head centered"><div><span>READY FOR YOUR SECTOR</span><h2>اختر القطاع. وإنجاز يجهّز القوة.</h2></div></div>
      <div class="ez-sector-grid">
        <button type="button" data-public-signup><span>01</span><b>المطاعم</b><small>الفروع · المخزون · المشتريات</small><i>↗</i></button>
        <button type="button" data-public-signup><span>02</span><b>المستشفيات</b><small>التنسيق · الجودة · العمليات</small><i>↗</i></button>
        <button type="button" data-public-signup><span>03</span><b>الفنادق</b><small>الضيافة · الحجوزات · التشغيل</small><i>↗</i></button>
        <button type="button" data-public-signup><span>04</span><b>الشركات</b><small>المبيعات · الموارد · التقارير</small><i>↗</i></button>
        <button type="button" data-public-signup><span>05</span><b>الجهات الحكومية</b><small>الخدمات · المعاملات · المتابعة</small><i>↗</i></button>
        <button type="button" data-public-signup><span>06</span><b>التجارة الإلكترونية</b><small>المنتجات · الطلبات · التسويق</small><i>↗</i></button>
      </div>
    </section>

    <section class="ez-flow" id="flow">
      <div class="ez-flow-copy"><span>FROM MISSION TO RESULT</span><h2>المهمة تتحول إلى تنفيذ.<br><em>والتنفيذ يتحول إلى نتيجة.</em></h2><p>إنجاز يربط الموظف الرقمي بالأدوات وسير العمل والموافقات والتحقق — في مسار واحد قابل للتتبع.</p></div>
      <div class="ez-flow-line"><div class="ez-flow-item"><b>01</b><strong>Mission</strong><small>استقبال المهمة</small></div><div class="ez-flow-item"><b>02</b><strong>Plan</strong><small>بناء خطة التنفيذ</small></div><div class="ez-flow-item"><b>03</b><strong>Execute</strong><small>تنفيذ الأدوات</small></div><div class="ez-flow-item"><b>04</b><strong>Verify</strong><small>التحقق والمراجعة</small></div><div class="ez-flow-item"><b>05</b><strong>Result</strong><small>النتيجة و KPI</small></div></div>
    </section>

    <section class="ez-final"><div><span>ENJAZ · DIGITAL WORKFORCE OS</span><h2>جاهز لتشغيل أول موظف رقمي؟</h2><p>ابدأ بمؤسستك، اختر قطاعك، واترك الباقي لإنجاز.</p></div><button type="button" class="ez-cta" data-public-signup>ابدأ الآن <b>←</b></button></section>
  </main>
</section>\`;
const style=document.createElement('style');style.textContent=\`
.ez-landing{--ink:#062b52;--muted:#6c8195;--line:#dce7f1;--blue:#0b5cff;--cyan:#19dce0;--green:#18a46e;min-height:100%;background:#f7faff;color:var(--ink);font-family:"IBM Plex Sans Arabic","Cairo",sans-serif;overflow:hidden;position:relative}
.ez-landing *{box-sizing:border-box}.ez-nav{height:78px;display:flex;align-items:center;justify-content:space-between;max-width:1440px;margin:auto;padding:0 42px;position:relative;z-index:20;border-bottom:1px solid rgba(220,231,241,.65)}
.ez-logo{display:flex;align-items:center;gap:11px}.ez-logo>span:last-child{display:flex;flex-direction:column}.ez-logo strong{font-size:21px}.ez-logo small{font-size:8px;letter-spacing:.1em;color:#7b91a4}.ez-logo-mark{width:38px;height:38px;border-radius:12px;background:linear-gradient(145deg,#075bea,#18dfe0);display:flex;align-items:center;justify-content:center;gap:3px;box-shadow:0 10px 24px rgba(11,92,255,.18)}.ez-logo-mark b{display:block;width:4px;height:16px;border-radius:4px;background:#fff}.ez-logo-mark b:nth-child(2){height:23px}.ez-logo-mark b:nth-child(3){height:12px}
.ez-nav-links{display:flex;gap:8px}.ez-nav-links button,.ez-nav-login{border:0;background:transparent;padding:10px 14px;color:#536e84;font:inherit;cursor:pointer;border-radius:9px}.ez-nav-links button:hover{background:#edf5ff;color:var(--blue)}.ez-nav-login{border:1px solid #cfddea!important;background:#fff!important;color:var(--ink)!important}
.ez-hero{max-width:1440px;margin:auto;min-height:650px;display:grid;grid-template-columns:.9fr 1.1fr;gap:20px;align-items:center;padding:55px 42px 72px}.ez-hero-copy{position:relative;z-index:5}.ez-eyebrow{font-size:10px;font-weight:800;letter-spacing:.13em;color:var(--blue);display:flex;align-items:center;gap:8px}.ez-live{width:7px;height:7px;border-radius:50%;background:var(--green);box-shadow:0 0 0 5px rgba(24,164,110,.10);animation:ezPulse 1.8s infinite}.ez-hero h1{font-size:clamp(46px,6vw,82px);line-height:1.02;letter-spacing:-.06em;margin:16px 0 20px}.ez-hero h1 span{background:linear-gradient(90deg,#075bea,#10bcc9);-webkit-background-clip:text;background-clip:text;color:transparent}.ez-hero p{font-size:18px;line-height:2;max-width:670px;color:var(--muted)}.ez-hero-actions{display:flex;gap:12px;margin-top:28px}.ez-cta{border:0;cursor:pointer;background:linear-gradient(135deg,#075bea,#087cf4);color:#fff;border-radius:12px;min-height:52px;padding:0 23px;font:700 15px inherit;box-shadow:0 13px 28px rgba(11,92,255,.22);transition:.2s}.ez-cta:hover{transform:translateY(-2px);box-shadow:0 17px 34px rgba(11,92,255,.27)}.ez-cta b{margin-right:8px}.ez-play{border:1px solid #d6e3ee;background:#fff;color:#45647c;border-radius:12px;padding:0 18px;font:600 14px inherit;cursor:pointer}.ez-play span{display:inline-grid;place-items:center;width:25px;height:25px;border-radius:50%;background:#edf5ff;color:var(--blue);margin-left:7px}.ez-trust{display:flex;align-items:center;gap:10px;margin-top:30px;color:#8195a6;font-size:11px}.ez-trust i{height:3px;width:3px;background:#b7c7d4;border-radius:50%}
.ez-stage{height:535px;position:relative;perspective:900px;transform-style:preserve-3d}.ez-grid{position:absolute;inset:7% 3%;border:1px solid #dce8f3;border-radius:50%;background:radial-gradient(circle at center,rgba(11,92,255,.08),transparent 38%),repeating-radial-gradient(circle at center,transparent 0 58px,rgba(133,169,198,.11) 59px 60px);transform:rotateX(58deg) rotateZ(-8deg);opacity:.8}.ez-orbit{position:absolute;border:1px solid rgba(11,92,255,.16);border-radius:50%;inset:18% 12%;animation:ezSpin 18s linear infinite}.ez-o2{inset:28% 21%;border-color:rgba(24,164,110,.16);animation-duration:12s;animation-direction:reverse}.ez-core{position:absolute;left:50%;top:48%;transform:translate(-50%,-50%);width:145px;height:145px;border-radius:50%;display:flex;flex-direction:column;align-items:center;justify-content:center;background:rgba(255,255,255,.9);border:1px solid #d9e7f2;box-shadow:0 25px 70px rgba(11,65,115,.18),inset 0 0 40px rgba(11,92,255,.04);z-index:5}.ez-core-ring{position:absolute;inset:-9px;border:1px solid rgba(11,92,255,.22);border-radius:50%;animation:ezPulseRing 2.5s ease-in-out infinite}.ez-core strong{font-size:24px;letter-spacing:.08em}.ez-core small{font-size:8px;color:#71889a;letter-spacing:.12em}.ez-core em{font-style:normal;color:var(--green);font-size:9px;margin-top:7px}
.ez-node{position:absolute;width:190px;text-align:right;padding:15px 16px;background:rgba(255,255,255,.88);border:1px solid #d9e6f0;border-radius:16px;box-shadow:0 18px 40px rgba(8,54,94,.10);backdrop-filter:blur(12px);cursor:pointer;transition:.25s;z-index:7;font-family:inherit}.ez-node:hover,.ez-node.is-selected{transform:translateY(-6px) scale(1.02);border-color:#a8c8ec;box-shadow:0 25px 55px rgba(8,54,94,.15)}.ez-node-1{top:10%;right:8%;animation:ezFloat 5s ease-in-out infinite}.ez-node-2{top:38%;left:1%;animation:ezFloat 6s -1.5s ease-in-out infinite}.ez-node-3{bottom:9%;right:4%;animation:ezFloat 5.7s -2.5s ease-in-out infinite}.ez-node-4{bottom:19%;left:10%;animation:ezFloat 6.4s -3s ease-in-out infinite}.ez-node-icon{float:right;margin-left:10px;width:33px;height:33px;border-radius:10px;display:grid;place-items:center;background:#edf5ff;color:var(--blue);font-weight:800}.ez-node b{display:block;font-size:14px}.ez-node small{display:block;color:#7c90a1;font-size:10px;margin-top:4px}.ez-node i{position:absolute;top:10px;left:12px;color:var(--green);font-size:9px;font-style:normal}.ez-scene-pop{position:absolute;left:50%;top:48%;transform:translate(-50%,80px);width:220px;padding:12px 15px;background:#062e58;color:#fff;border-radius:13px;z-index:10;box-shadow:0 20px 45px rgba(4,40,76,.22);opacity:0;pointer-events:none;transition:.25s}.ez-scene-pop.show{opacity:1;transform:translate(-50%,70px)}.ez-scene-pop small{color:#67dfe1;font-size:8px;letter-spacing:.1em}.ez-scene-pop strong{display:block;font-size:13px;margin:4px 0}.ez-scene-pop span{font-size:9px;color:#b6cce0}.ez-scene-pop em{display:block;color:#5be1ae;font-style:normal;font-size:8px;margin-top:6px}
.ez-logo-wall{border-top:1px solid #e2ebf2;border-bottom:1px solid #e2ebf2;background:#fff;padding:22px 0;overflow:hidden}.ez-wall-title{text-align:center;font-size:9px;letter-spacing:.12em;color:#91a2b0;margin-bottom:17px}.ez-marquee{overflow:hidden}.ez-marquee-track{display:flex;width:max-content;gap:42px;align-items:center;animation:ezMarquee 28s linear infinite}.ez-company{display:flex;align-items:center;gap:9px;color:#61778a;min-width:130px;justify-content:center;filter:grayscale(1);opacity:.72;transition:.2s}.ez-company:hover{filter:none;opacity:1;transform:scale(1.06)}.ez-cmark{width:28px;height:28px;border-radius:8px;display:grid;place-items:center;background:#eef3f7;color:#173c5d;font-weight:800;font-size:13px}.ez-cmark.openai{border-radius:50%}.ez-cmark.lovable{color:#9c4cff}.ez-cmark.shopify{color:#16844a}.ez-cmark.stripe{color:#5a43d6}.ez-cmark.slack{color:#e54b70}.ez-cmark.github{color:#111}.ez-cmark.salesforce{color:#0b91d1}.ez-cmark.supabase{color:#20a36a}
.ez-workforce,.ez-sectors,.ez-flow{max-width:1440px;margin:auto;padding:100px 42px}.ez-section-head{display:flex;justify-content:space-between;gap:50px;align-items:end;margin-bottom:35px}.ez-section-head>div span,.ez-flow-copy>span,.ez-final span{font-size:9px;letter-spacing:.14em;color:var(--blue);font-weight:800}.ez-section-head h2,.ez-flow h2,.ez-final h2{font-size:clamp(30px,4vw,50px);letter-spacing:-.045em;line-height:1.1;margin:10px 0}.ez-section-head p{max-width:450px;color:var(--muted);line-height:1.9;font-size:14px}.ez-card-stack{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.ez-work-card{background:#fff;border:1px solid var(--line);border-radius:20px;padding:22px;min-height:240px;box-shadow:0 15px 40px rgba(7,47,83,.06);transition:.3s}.ez-work-card:hover,.ez-work-card.active{transform:translateY(-7px);box-shadow:0 25px 55px rgba(7,47,83,.12);border-color:#bdd4eb}.ez-card-top{display:flex;justify-content:space-between;align-items:center;color:#8798a6;font-size:9px}.ez-status{color:var(--green);font-size:9px}.ez-person{display:flex;align-items:center;gap:12px;margin:28px 0}.ez-avatar{width:49px;height:49px;border-radius:15px;display:grid;place-items:center;background:#eaf3ff;color:var(--blue);font-size:18px;font-weight:800}.ez-avatar.cyan{background:#e5fbfb;color:#079ba1}.ez-avatar.green{background:#e8f8f1;color:#12875c}.ez-person strong{display:block;font-size:17px}.ez-person small{color:#8798a6;font-size:10px}.ez-progress{height:7px;border-radius:9px;background:#edf2f6;overflow:hidden}.ez-progress span{display:block;width:82%;height:100%;background:linear-gradient(90deg,#075bea,#19dce0);border-radius:9px;animation:ezProgress 3s ease-in-out infinite}.ez-card-meta{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:20px}.ez-card-meta span{font-size:9px;color:#8a9baa}.ez-card-meta strong{display:block;color:var(--ink);font-size:14px;margin-top:4px}.ez-card-controls{display:flex;justify-content:center;align-items:center;gap:18px;margin-top:20px}.ez-card-controls button{width:38px;height:38px;border:1px solid var(--line);background:#fff;border-radius:10px;font-size:20px;color:#59748a;cursor:pointer}.ez-card-controls div{display:flex;gap:6px}.ez-card-controls div span{width:6px;height:6px;border-radius:50%;background:#ccd8e2}.ez-card-controls div span.is-on{width:20px;border-radius:9px;background:var(--blue)}
.ez-sectors{padding-top:45px}.centered{justify-content:center;text-align:center}.ez-sector-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.ez-sector-grid button{position:relative;text-align:right;min-height:160px;padding:22px;background:#fff;border:1px solid var(--line);border-radius:17px;cursor:pointer;font-family:inherit;transition:.22s}.ez-sector-grid button:hover{transform:translateY(-4px);border-color:#b7d0e8;box-shadow:0 20px 40px rgba(7,47,83,.08)}.ez-sector-grid span{font-size:9px;color:#8da0af}.ez-sector-grid b{display:block;font-size:19px;margin-top:25px}.ez-sector-grid small{color:#8093a4;font-size:10px}.ez-sector-grid i{position:absolute;left:18px;bottom:18px;color:var(--blue);font-style:normal;font-size:18px}
.ez-flow{display:grid;grid-template-columns:.8fr 1.2fr;gap:70px;align-items:center}.ez-flow-copy p{color:var(--muted);line-height:2;max-width:490px}.ez-flow h2 em{font-style:normal;color:var(--blue)}.ez-flow-line{display:grid;grid-template-columns:repeat(5,1fr);position:relative}.ez-flow-line:before{content:"";position:absolute;top:23px;left:6%;right:6%;height:1px;background:#d6e4ef}.ez-flow-item{text-align:center;position:relative;z-index:1}.ez-flow-item b{display:grid;place-items:center;margin:auto;width:46px;height:46px;border-radius:50%;background:#fff;border:1px solid #cfe0ee;color:var(--blue);font-size:10px}.ez-flow-item strong{display:block;margin-top:12px;font-size:11px}.ez-flow-item small{color:#8a9ba9;font-size:8px}.ez-final{max-width:1360px;margin:0 auto 70px;border-radius:26px;padding:55px 65px;background:linear-gradient(120deg,#062f62,#075bea 68%,#0caab9);color:#fff;display:flex;align-items:center;justify-content:space-between;gap:25px;box-shadow:0 30px 70px rgba(5,61,125,.20)}.ez-final h2{font-size:38px;margin-bottom:8px}.ez-final p{color:#d4e9ff}.ez-final .ez-cta{background:#fff;color:#075bea;box-shadow:none}
.ez-ambient{position:absolute;border-radius:50%;pointer-events:none;filter:blur(2px)}.ez-a1{width:500px;height:500px;right:-260px;top:80px;background:radial-gradient(circle,rgba(25,220,224,.11),transparent 68%)}.ez-a2{width:400px;height:400px;left:-220px;top:700px;background:radial-gradient(circle,rgba(11,92,255,.08),transparent 68%)}
@keyframes ezFloat{0%,100%{translate:0 0}50%{translate:0 -9px}}@keyframes ezSpin{to{rotate:360deg}}@keyframes ezPulse{50%{opacity:.45;box-shadow:0 0 0 8px rgba(24,164,110,.03)}}@keyframes ezPulseRing{50%{transform:scale(1.05);opacity:.4}}@keyframes ezMarquee{to{transform:translateX(-50%)}}@keyframes ezProgress{0%,100%{width:70%}50%{width:92%}}
@media(max-width:900px){.ez-nav{padding:0 18px}.ez-nav-links{display:none}.ez-hero{grid-template-columns:1fr;padding:40px 20px 30px}.ez-hero-copy{text-align:center}.ez-eyebrow,.ez-trust{justify-content:center}.ez-hero p{margin:auto}.ez-hero-actions{justify-content:center}.ez-stage{height:470px}.ez-node{width:165px}.ez-node-2{left:0}.ez-workforce,.ez-sectors,.ez-flow{padding:70px 20px}.ez-section-head{display:block}.ez-section-head p{margin-top:20px}.ez-card-stack,.ez-sector-grid{grid-template-columns:1fr}.ez-flow{grid-template-columns:1fr;gap:35px}.ez-final{margin:0 18px 45px;padding:35px 25px;display:block}.ez-final .ez-cta{margin-top:22px}.ez-flow-line{gap:5px}.ez-flow-item strong{font-size:9px}}
@media(max-width:560px){.ez-hero h1{font-size:44px}.ez-stage{height:420px;transform:scale(.9);transform-origin:center}.ez-node{width:145px;padding:11px}.ez-node b{font-size:11px}.ez-node small{font-size:8px}.ez-core{width:120px;height:120px}.ez-core strong{font-size:19px}.ez-trust{flex-wrap:wrap}.ez-final h2{font-size:28px}.ez-flow-line{grid-template-columns:1fr 1fr 1fr}.ez-flow-line:before{display:none}.ez-flow-item:nth-child(4),.ez-flow-item:nth-child(5){margin-top:20px}}
@media(prefers-reduced-motion:reduce){.ez-landing *{animation:none!important;transition:none!important}}
\`;
document.head.appendChild(style);
const stage=root.querySelector('#ez-stage');let tx=0,ty=0;
stage?.addEventListener('pointermove',e=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=stage.getBoundingClientRect();tx=((e.clientX-r.left)/r.width-.5)*8;ty=((e.clientY-r.top)/r.height-.5)*-6;stage.style.transform=\`perspective(900px) rotateY(\${tx}deg) rotateX(\${ty}deg)\`});
stage?.addEventListener('pointerleave',()=>{stage.style.transform=''});
const scenes={procurement:['تحليل الموردين','تمت مقارنة 12 عرض شراء','EXECUTING · 82%'],sales:['تأهيل العملاء','تمت جدولة 11 متابعة جديدة','RUNNING · 68%'],commerce:['مراقبة المتجر','تم اكتشاف انخفاض في 3 منتجات','MONITORING · 91%'],operations:['تنسيق العمليات','تم تسليم المهمة للموظف التالي','HANDOFF · READY']};
root.querySelectorAll('[data-scene]').forEach(n=>n.addEventListener('click',()=>{root.querySelectorAll('[data-scene]').forEach(x=>x.classList.remove('is-selected'));n.classList.add('is-selected');const s=scenes[n.dataset.scene]||scenes.operations,p=root.querySelector('#ez-scene-pop');p.innerHTML='<small>LIVE MISSION</small><strong>'+s[0]+'</strong><span>'+s[1]+'</span><em>'+s[2]+'</em>';p.classList.add('show');setTimeout(()=>p.classList.remove('show'),2800)}));
const cards=[...root.querySelectorAll('.ez-work-card')];let ci=0;const showCard=()=>{cards.forEach((x,i)=>x.classList.toggle('active',i===ci));root.querySelectorAll('.ez-card-controls div span').forEach((x,i)=>x.classList.toggle('is-on',i===ci))};root.querySelector('[data-card-next]')?.addEventListener('click',()=>{ci=(ci+1)%cards.length;showCard()});root.querySelector('[data-card-prev]')?.addEventListener('click',()=>{ci=(ci-1+cards.length)%cards.length;showCard()});
root.querySelectorAll('[data-scroll]').forEach(x=>x.addEventListener('click',()=>root.querySelector('#'+x.dataset.scroll)?.scrollIntoView({behavior:'smooth',block:'start'})));
root.querySelectorAll('[data-public-login]').forEach(x=>x.addEventListener('click',()=>goAuth(false)));root.querySelectorAll('[data-public-signup]').forEach(x=>x.addEventListener('click',()=>goAuth(true)));
}

if(q.has('auth')){root?.classList.add('is-auth-locked');setAuthState('auth');renderForm()}else if(authClient.token()){recover()}else{window.__ENJAZ_PUBLIC_SHOWN__=true;setAuthState('public');renderPublic()}
