import {mountEnjazVisualScenes} from './landing-visuals.js';
/* Canonical ENJAZ public experience. It renders product preview only; authentication stays in auth-gate-v2.js. */
export function renderLanding(root,{onLogin=()=>{},onSignup=()=>{}}={}){if(!root)return;root.innerHTML=`<div class="public-platform" id="enjaz-public">
<header><div class="pp-container pp-nav"><a class="pp-brand" href="#top"><span class="pp-mark">إ</span><span>إنجاز<small>INTELLIGENT OPERATING PLATFORM</small></span></a><button class="pp-mobile" type="button" aria-label="فتح القائمة" aria-expanded="false">☰</button><nav class="pp-links" aria-label="التنقل الرئيسي"><a href="#platform">المنصة</a><a href="#workforce">القوى العاملة</a><a href="#operations">كيف تعمل</a><a href="#industries">القطاعات</a><a href="#governance">الحوكمة</a></nav><div class="pp-actions"><button class="pp-btn ghost" data-public-login>تسجيل الدخول</button><button class="pp-btn primary" data-public-signup>ابدأ مع إنجاز</button></div></div></header>
<main id="top"><section><div class="pp-container pp-hero"><div class="pp-hero-copy"><span class="pp-kicker">INTELLIGENT ENTERPRISE OPERATING PLATFORM</span><h1>قوة عمل رقمية تعمل معك.<br><em>مؤسستك تعمل بذكاء.</em></h1><p>إنجاز توحّد المؤسسة والقوى العاملة البشرية والرقمية والمهام وسير العمل والحوكمة في طبقة تشغيل واحدة قابلة للمتابعة.</p><div class="pp-hero-actions"><button class="pp-btn primary" data-public-signup>أنشئ مساحة مؤسستك</button><a class="pp-btn ghost" href="#platform">استكشف المنصة ←</a></div><div class="pp-trust"><span>صلاحيات حسب الدور</span><span>موافقات بشرية</span><span>سجل تدقيق</span></div></div><div class="pp-preview" aria-label="معاينة توضيحية لمركز قيادة إنجاز"><div class="pp-window sf-command-card"><div class="pp-window-top"><span class="pp-preview-label">معاينة المنتج · PREVIEW</span><span>ENJAZ COMMAND CENTER</span></div><div class="pp-console"><aside><b>إنجاز</b><span class="active">مركز القيادة</span><span>القوى العاملة</span><span>العمليات</span><span>سير العمل</span><span>الحوكمة</span></aside><div class="pp-console-main"><div class="pp-console-head"><div><small>المشهد التشغيلي</small><h3>ماذا يحدث الآن؟</h3></div><span class="pp-live">عرض توضيحي</span></div><div class="pp-flow"><article><small>الطلب</small><strong>مهمة جديدة</strong><i></i></article><b>←</b><article><small>المسؤول</small><strong>منسق العمليات</strong><i></i></article><b>←</b><article><small>التحكم</small><strong>موافقة بشرية</strong><i></i></article></div><div class="pp-activity"><div class="pp-activity-row"><i>✓</i><span>تم تخطيط المهمة ضمن الصلاحيات</span></div><div class="pp-activity-row"><i>◇</i><span>القرار الحساس بانتظار المراجع</span></div><div class="pp-activity-row"><i>▤</i><span>يُوثق كل انتقال في سجل التدقيق</span></div></div></div></div></div></div></div></section>
<section class="pp-section soft"><div class="pp-container"><div class="pp-section-head center"><span class="pp-kicker">TECHNOLOGY & ECOSYSTEM</span><h2>طبقة تشغيل تتصل بأدوات مؤسستك</h2><p>نماذج ذكاء اصطناعي، أدوات، Webhooks وMCP عبر تكاملات محكومة. لا يُعرض أي اتصال على أنه فعّال قبل ربطه والتحقق منه.</p></div><div class="pp-ecosystem pp-capability-marquee" aria-label="قدرات التكامل المتاحة"><div class="pp-marquee-track"><span>AI Models</span><span>Enterprise APIs</span><span>Webhooks</span><span>MCP Tools</span><span>Databases</span><span>Communication</span><span>CRM & ERP</span><span>Custom Systems</span><span aria-hidden="true">AI Models</span><span aria-hidden="true">Enterprise APIs</span><span aria-hidden="true">Webhooks</span><span aria-hidden="true">MCP Tools</span><span aria-hidden="true">Databases</span><span aria-hidden="true">Communication</span></div></div></div></section>
<section class="pp-section" id="platform"><div class="pp-container"><div class="pp-section-head"><span class="pp-kicker">ENJAZ PLATFORM</span><h2>من القرار إلى التنفيذ، في نظام واحد.</h2><p>منتج تشغيلي حقيقي يربط المسؤوليات والمهام والتنفيذ والمراجعة دون فصل الذكاء الاصطناعي عن الحوكمة.</p></div><div class="pp-platform-grid pp-bento"><article class="pp-surface pp-card-command"><div class="pp-card-top"><span class="num">01 / COMMAND</span><span class="pp-card-orb"></span></div><h3>مركز قيادة المؤسسة</h3><p>كل ما يحدث داخل المؤسسة أمامك: المهام، سير العمل، الموافقات والتنبيهات — في مشهد تشغيلي واحد.</p><div class="pp-mini-console"><span>WORKFLOW</span><b>مهمة جديدة</b><i>→</i><strong>منسق العمليات</strong><em>موافقة بشرية</em></div></article><article class="pp-surface pp-card-chat"><div class="pp-card-top"><span class="num">02 / HUMAN × AI</span><span class="pp-card-live"><i></i>LIVE DEMO</span></div><h3>محادثة بين الإنسان والموظف الرقمي</h3><div class="pp-chat"><div class="pp-chat-row bot"><span>AI</span><p>تم تجهيز خطة المهمة. هل تريد مراجعتها قبل التنفيذ؟</p></div><div class="pp-chat-row human"><p>نعم، اعرض لي الخطوات والصلاحيات.</p><span>أنت</span></div><div class="pp-chat-row bot"><span>AI</span><p>هذه الخطوات ضمن السياسة. القرار الحساس يحتاج موافقة بشرية.</p></div></div></article><article class="pp-surface pp-card-workforce"><div class="pp-card-top"><span class="num">03 / WORKFORCE</span><span class="pp-card-icon">48</span></div><h3>48 موظفًا رقميًا، تخصص واحد قابل للتكييف</h3><p>الدور نفسه يعمل عبر القطاعات، ويتخصص عبر السياق والمهارات والمعرفة والأدوات والسياسات والصلاحيات.</p><div class="pp-skill-map"><span>Role</span><b>Skills</b><span>Knowledge</span><b>Tools</b><span>Policies</span><b>Permissions</b></div></article><article class="pp-surface pp-card-automation"><div class="pp-card-top"><span class="num">04 / AUTOMATION</span><span class="pp-signal">RUNNING</span></div><h3>من الطلب إلى التنفيذ</h3><div class="pp-pipeline"><span>هدف</span><i>→</i><span>خطة</span><i>→</i><span>موافقة</span><i>→</i><span>تنفيذ</span></div><p>سير واضح، ونقطة تحكم بشرية عند الأفعال الحساسة.</p></article><article class="pp-surface pp-card-governance"><div class="pp-card-top"><span class="num">05 / GOVERN</span><span class="pp-shield">✓</span></div><h3>الحوكمة لا تأتي بعد الذكاء</h3><p>السياسات والصلاحيات والميزانية والموافقات وسجل التدقيق مدمجة داخل طبقة التشغيل.</p><div class="pp-policy-stack"><span>POLICY</span><span>APPROVAL</span><span>AUDIT TRAIL</span></div></article><article class="pp-surface pp-card-sector"><div class="pp-card-top"><span class="num">06 / INDUSTRY</span><span class="pp-sector-dots"><i></i><i></i><i></i></span></div><h3>إنجاز تتشكل حسب مؤسستك</h3><div class="pp-sector-tiles"><span>مطاعم</span><span>مستشفيات</span><span>فنادق</span><span>شركات</span><span>حكومة</span></div></article></div></div></section>
<section class="pp-section dark" id="workforce"><div class="pp-container pp-workforce"><div class="pp-workforce-copy"><span class="pp-kicker">DIGITAL WORKFORCE</span><h2>البشر والموظفون الرقميون. فريق واحد.</h2><p>الإنسان يقود ويقرر. الموظف الرقمي يخطط وينفذ ضمن دوره وأدواته وسياساته. إنجاز تربط الطرفين بمسؤولية واضحة.</p><div class="pp-equation"><span>Human Workforce</span><b>+</b><span>Digital Workforce</span><b>= ENJAZ</b></div></div><div class="pp-workforce-right"><div class="pp-workforce-visual" aria-label="كتالوج القوى العاملة الرقمية"><div class="pp-orbit pp-orbit-a"></div><div class="pp-orbit pp-orbit-b"></div><div class="pp-core"><span>48</span><small>Digital<br/>Workforce</small></div><span class="pp-node n1">AI</span><span class="pp-node n2">Ops</span><span class="pp-node n3">Data</span><span class="pp-node n4">CX</span><span class="pp-node n5">Finance</span></div><div class="pp-role-list"><article class="pp-role"><span>ق</span><div><strong>AI Manager</strong><small>تنسيق العمل والتصعيد والقرارات</small></div><em>بإشراف بشري</em></article><article class="pp-role"><span>ت</span><div><strong>AI Analyst</strong><small>تحليل البيانات وإعداد الرؤى</small></div><em>ضمن الصلاحيات</em></article><article class="pp-role"><span>ع</span><div><strong>AI Operations Worker</strong><small>تنفيذ إجراءات التشغيل المتكررة</small></div><em>قابل للتدقيق</em></article><article class="pp-role"><span>ن</span><div><strong>AI Coordinator</strong><small>ربط الفرق والمهام وسير العمل</small></div><em>تحت السياسة</em></article><article class="pp-role"><span>خ</span><div><strong>AI Customer Service Worker</strong><small>دعم الخدمة والتنسيق والاستجابة</small></div><em>بتصعيد واضح</em></article></div></div></div></section>
<section class="pp-section soft" id="operations"><div class="pp-container"><div class="pp-section-head center"><span class="pp-kicker">HOW ENJAZ WORKS</span><h2>تدفق واضح. تحكم مستمر.</h2></div><div class="pp-process"><article class="pp-step"><b>01</b><strong>حدّد الهدف</strong><small>مهمة مرتبطة بالمؤسسة والفريق.</small></article><article class="pp-step"><b>02</b><strong>خطّط</strong><small>خطة قابلة للفحص قبل التنفيذ.</small></article><article class="pp-step"><b>03</b><strong>نفّذ</strong><small>أدوات ممنوحة بصلاحيات محددة.</small></article><article class="pp-step"><b>04</b><strong>وافق</strong><small>الإنسان يراجع الأفعال الحساسة.</small></article><article class="pp-step"><b>05</b><strong>تتبّع</strong><small>الحالة والنتيجة محفوظتان للتدقيق.</small></article></div></div></section>
<section class="pp-section" id="industries"><div class="pp-container"><div class="pp-section-head"><span class="pp-kicker">INDUSTRY CONFIGURATION</span><h2>يتهيأ لقطاعك، ولا يفرض قالبًا عامًا.</h2><p>طبقة القطاع تحدد الأدوار والقوى العاملة والعمليات والمصطلحات والتجهيز الأولي، مع قابلية التوسع.</p></div><div class="pp-industries"><article class="pp-industry"><i>01</i><strong>المطاعم</strong><small>الفروع والطلبات والمخزون والجودة.</small></article><article class="pp-industry"><i>02</i><strong>المستشفيات</strong><small>التنسيق والجودة وخدمة المرضى.</small></article><article class="pp-industry"><i>03</i><strong>الفنادق</strong><small>الحجوزات والضيافة والتشغيل.</small></article><article class="pp-industry"><i>04</i><strong>الشركات</strong><small>العمليات والإدارات وخدمة العملاء.</small></article><article class="pp-industry"><i>05</i><strong>الحكومة</strong><small>الخدمات والمعاملات والامتثال.</small></article></div></div></section>
<section class="pp-section soft" id="governance"><div class="pp-container"><div class="pp-section-head center"><span class="pp-kicker">OPERATIONS & GOVERNANCE</span><h2>استقلالية مسؤولة، وليست تنفيذًا بلا حدود.</h2><p>هوية ودور وهدف ومهارات وأدوات ومعرفة ونموذج واستقلالية وميزانية وسياسات وجدول — ثم معاينة ونشر ومتابعة التنفيذ والموافقات والتاريخ.</p></div><div class="pp-ecosystem"><span>Identity</span><span>Role & Goals</span><span>Skills & Tools</span><span>Knowledge</span><span>Model Strategy</span><span>Autonomy</span><span>Budget</span><span>Policies</span><span>Approvals</span><span>Audit Trail</span></div></div></section>
<section class="pp-cta"><div class="pp-container"><div class="pp-cta-box"><div><span class="pp-kicker">BUILD YOUR OPERATING LAYER</span><h2>ابدأ من مؤسستك، لا من واجهة وهمية.</h2><p>أنشئ مساحة العمل ثم فعّل القوة العاملة المناسبة لقطاعك.</p></div><button class="pp-btn" data-public-signup>ابدأ مع إنجاز ←</button></div></div></section></main>
<footer class="pp-footer"><div class="pp-container pp-footer-inner"><div class="pp-brand"><span class="pp-mark">إ</span><span>إنجاز<small>INTELLIGENT OPERATING PLATFORM</small></span></div><div class="pp-footer-links"><a href="/privacy.html">الخصوصية</a><a href="/terms.html">شروط الاستخدام</a><button class="pp-btn ghost" data-public-login>دخول مساحة العمل</button></div></div></footer></div>`;mountEnjazVisualScenes(root);root.querySelectorAll('[data-public-login]').forEach(button=>button.addEventListener('click',()=>onLogin()));root.querySelectorAll('[data-public-signup]').forEach(button=>button.addEventListener('click',()=>onSignup()));
const platformGrid=root.querySelector('.pp-platform-grid');
if(platformGrid){
  const demo=document.createElement('div');
  demo.className='pp-live-demo';
  demo.innerHTML=`<div class="pp-live-demo-head"><div><span class="pp-kicker">INTERACTIVE PRODUCT DEMO</span><h3>شاهد إنجاز وهي تدير العمل</h3><p>معاينة تفاعلية توضيحية — ليست بيانات إنتاج فعلية.</p></div><span class="pp-demo-status"><i></i>DEMO MODE</span></div>
  <div class="pp-demo-tabs" role="tablist" aria-label="معاينة وظائف المنصة">
    <button class="is-active" type="button" data-demo-tab="command" role="tab" aria-selected="true">مركز القيادة</button>
    <button type="button" data-demo-tab="workforce" role="tab" aria-selected="false">القوى العاملة</button>
    <button type="button" data-demo-tab="workflow" role="tab" aria-selected="false">سير العمل</button>
  </div>
  <div class="pp-demo-stage">
    <div class="pp-demo-panel is-active" data-demo-panel="command"><div class="pp-demo-sidebar"><b>ENJAZ</b><span class="active">Command Center</span><span>Tasks</span><span>Workflows</span><span>Governance</span></div><div class="pp-demo-body"><div class="pp-demo-top"><div><small>COMMAND CENTER</small><strong>المشهد التشغيلي</strong></div><em>Preview</em></div><div class="pp-demo-grid"><article><small>WORK QUEUE</small><b>12</b><span>مهام تحتاج متابعة</span></article><article><small>APPROVAL</small><b>03</b><span>قرارات بانتظار المراجعة</span></article><article class="wide"><small>ACTIVITY</small><div class="pp-demo-line"><i></i><span>تم تخطيط مهمة ضمن السياسة</span><time>الآن</time></div><div class="pp-demo-line"><i></i><span>تمت إحالة خطوة إلى المراجع</span><time>الآن</time></div></article></div></div></div>
    <div class="pp-demo-panel" data-demo-panel="workforce"><div class="pp-demo-workforce"><div class="pp-demo-avatar">AI</div><div><small>DIGITAL WORKFORCE</small><strong>اختيار الموظف الرقمي المناسب</strong><p>الدور ← المهارات ← المعرفة ← الأدوات ← السياسات ← الصلاحيات</p><div class="pp-demo-role-chips"><span>AI Manager</span><span>AI Analyst</span><span>AI Operations</span><span>AI Coordinator</span></div></div></div></div>
    <div class="pp-demo-panel" data-demo-panel="workflow"><div class="pp-demo-workflow"><div class="pp-demo-flow-step done"><b>01</b><strong>الهدف</strong><small>طلب تشغيلي</small></div><i>←</i><div class="pp-demo-flow-step done"><b>02</b><strong>التخطيط</strong><small>خطة قابلة للفحص</small></div><i>←</i><div class="pp-demo-flow-step active"><b>03</b><strong>الموافقة</strong><small>مراجعة بشرية</small></div><i>←</i><div class="pp-demo-flow-step"><b>04</b><strong>التنفيذ</strong><small>ضمن الصلاحيات</small></div></div></div>
  </div>`;
  platformGrid.parentElement.insertBefore(demo,platformGrid);
  const tabs=demo.querySelectorAll('[data-demo-tab]'), panels=demo.querySelectorAll('[data-demo-panel]');
  tabs.forEach(tab=>tab.addEventListener('click',()=>{const key=tab.dataset.demoTab;tabs.forEach(t=>{const active=t===tab;t.classList.toggle('is-active',active);t.setAttribute('aria-selected',String(active))});panels.forEach(p=>p.classList.toggle('is-active',p.dataset.demoPanel===key))}));
}
const mobile=root.querySelector('.pp-mobile');if(mobile){mobile.addEventListener('click',()=>{const nav=root.querySelector('.pp-links');const open=mobile.getAttribute('aria-expanded')==='true';mobile.setAttribute('aria-expanded',String(!open));nav?.classList.toggle('is-open',!open);});root.querySelectorAll('.pp-links a').forEach(a=>a.addEventListener('click',()=>{mobile.setAttribute('aria-expanded','false');root.querySelector('.pp-links')?.classList.remove('is-open')}));}}
