const enhanceLanding=()=>{const root=document.querySelector('.landing');if(!root||root.dataset.enhanced)return;root.dataset.enhanced='1';
const nav=root.querySelector('.landing-nav');
const hero=root.querySelector('.landing-hero');
if(hero){const signal=document.createElement('div');signal.className='hero-signal';signal.innerHTML='<span class="signal-dot"></span><span>قوة العمل تعمل الآن</span><b>LIVE</b>';hero.appendChild(signal);
const metrics=document.createElement('div');metrics.className='hero-metrics';metrics.innerHTML='<div><strong data-count="1200">1,200+</strong><span>موظف رقمي جاهز</span></div><div><strong data-count="5">5</strong><span>قطاعات رئيسية</span></div><div><strong>24/7</strong><span>تشغيل مستمر</span></div>';hero.appendChild(metrics);}
const industries=root.querySelector('#industries');if(industries){const strip=document.createElement('div');strip.className='industry-marquee';strip.innerHTML='<span>RESTAURANTS</span><i>✦</i><span>HEALTHCARE</span><i>✦</i><span>HOSPITALITY</span><i>✦</i><span>ENTERPRISE</span><i>✦</i><span>GOVERNMENT</span><i>✦</i><span>RESTAURANTS</span><i>✦</i><span>HEALTHCARE</span>';industries.insertBefore(strip,industries.querySelector('.section-head'));}
const platform=root.querySelector('#platform');if(platform){const banner=document.createElement('div');banner.className='platform-demo reveal in';banner.innerHTML='<div class="demo-copy"><small>ENJAZ CONTROL PLANE</small><h3>منصة واحدة. قوة عمل كاملة.</h3><p>راقب الموظفين، المهام، الموافقات والتكاملات من مركز قيادة واحد.</p></div><div class="demo-screen"><div class="demo-top"><span>WORKFORCE COMMAND</span><b>● SYSTEM OPERATIONAL</b></div><div class="demo-body"><div class="demo-row"><span class="avatar">م</span><div><strong>مدير العمليات الرقمي</strong><small>Restaurant Operations</small></div><em>تنفيذ مهمة</em><i>98%</i></div><div class="demo-row"><span class="avatar">خ</span><div><strong>موظف خدمة العملاء</strong><small>Customer Experience</small></div><em>بانتظار موافقة</em><i>94%</i></div><div class="demo-row"><span class="avatar">ت</span><div><strong>محلل الأعمال الرقمي</strong><small>Enterprise Analytics</small></div><em>يحلل البيانات</em><i>99%</i></div></div></div>';platform.querySelector('.section-head')?.after(banner);}
root.querySelectorAll('.industry-card').forEach(card=>card.addEventListener('mousemove',e=>{const r=card.getBoundingClientRect();card.style.setProperty('--mx',`${e.clientX-r.left}px`);card.style.setProperty('--my',`${e.clientY-r.top}px`)}));
let glow=document.querySelector('.landing-pointer-glow');if(!glow){glow=document.createElement('div');glow.className='landing-pointer-glow';document.body.appendChild(glow);root.addEventListener('pointermove',e=>{glow.style.transform=`translate3d(${e.clientX-180}px,${e.clientY-180}px,0)`},{passive:true});root.addEventListener('pointerleave',()=>glow.classList.remove('show'));root.addEventListener('pointerenter',()=>glow.classList.add('show'));}
const tick=()=>root.querySelectorAll('[data-count]').forEach(el=>{if(el.dataset.done)return;const target=Number(el.dataset.count);let n=0;const step=Math.max(1,Math.ceil(target/45));const run=()=>{n=Math.min(target,n+step);el.textContent=n.toLocaleString('en-US')+'+';if(n<target)requestAnimationFrame(run);else el.dataset.done='1'};run()});setTimeout(tick,350);
if(nav){const observer=new MutationObserver(()=>{});observer.observe(nav,{attributes:true});}
};
const boot=()=>enhanceLanding();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();new MutationObserver(enhanceLanding).observe(document.body,{childList:true,subtree:true});