import {apiClient} from './api-client.js';
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const arr=v=>Array.isArray(v)?v:[];
const state=()=>({workspaceId:window.ENJAZ_WORKSPACE_ID||'',token:window.ENJAZ_ACCESS_TOKEN||''});
export async function openTask360(taskId){
 if(!taskId)return; const {workspaceId,token}=state(); const host=document.querySelector('#task360-root')||document.body.appendChild(Object.assign(document.createElement('div'),{id:'task360-root'}));
 host.innerHTML='<div class="t360-backdrop"><section class="t360-drawer"><div class="t360-loading">جاري تحميل مركز المهمة…</div></section></div>';
 try{const r=await apiClient.getTask(workspaceId,token,taskId);const t=r?.data||r?.task||r;const out=t.output||{};const input=t.input||{};const plan=arr(out.plan||out.steps||t.plan);host.innerHTML=`<div class="t360-backdrop" data-t360-close><section class="t360-drawer" onclick="event.stopPropagation()"><header class="t360-head"><button data-t360-close>×</button><div><span>TASK 360 · EXECUTION CONTROL</span><h2>${esc(t.title||'مهمة')}</h2><p>${esc(t.objective||'—')}</p></div><strong class="t360-status">${esc(t.status||'—')}</strong></header><div class="t360-strip"><div><small>الأولوية</small><b>${esc(t.priority??'—')}</b></div><div><small>الموظف</small><b>${esc(t.employee_id||'غير مرتبط')}</b></div><div><small>أنشئت</small><b>${esc(t.created_at||'—')}</b></div><div><small>اكتملت</small><b>${esc(t.completed_at||'—')}</b></div></div><main class="t360-main"><section class="t360-card"><h3>دورة التنفيذ</h3><div class="t360-flow"><i>01<br><b>فهم</b></i><em>→</em><i>02<br><b>تخطيط</b></i><em>→</em><i>03<br><b>سياسة</b></i><em>→</em><i>04<br><b>تنفيذ</b></i><em>→</em><i>05<br><b>تحقق</b></i><em>→</em><i>06<br><b>تدقيق</b></i></div></section><section class="t360-card"><h3>خطة المهمة</h3><ol>${plan.map((x,i)=>`<li><b>${i+1}</b><span>${esc(typeof x==='string'?x:(x.title||x.action||JSON.stringify(x)))}</span><small>قيد التتبع</small></li>`).join('')||'<li><span>الخطة ستظهر بعد بدء التنفيذ.</span></li>'}</ol></section><div class="t360-two"><section class="t360-card"><h3>المدخلات</h3><pre>${esc(JSON.stringify(input,null,2))}</pre></section><section class="t360-card"><h3>المخرجات</h3><pre>${esc(JSON.stringify(out,null,2))}</pre></section></div><section class="t360-card"><h3>الحوكمة والنتيجة</h3><div class="t360-governance"><span>الموافقات: <b>${esc(t.status==='waiting_approval'?'مطلوبة':'غير مطلوبة')}</b></span><span>التدقيق: <b>مسجل</b></span><span>إعادة المحاولة: <b>متاحة عبر المشغل</b></span></div></section></main></section></div>`;host.querySelectorAll('[data-t360-close]').forEach(x=>x.onclick=()=>host.innerHTML='');
 }catch(e){host.innerHTML=`<div class="t360-backdrop"><section class="t360-drawer"><button data-t360-close>×</button><div class="t360-loading">تعذر تحميل المهمة<br><small>${esc(e.message)}</small></div></section></div>`;host.querySelector('[data-t360-close]').onclick=()=>host.innerHTML='';}
}
const boot=()=>{if(window.__enjazTask360)return;window.__enjazTask360=1;document.addEventListener('click',e=>{const b=e.target.closest('[data-task-360],[data-task-id]');if(b?.dataset.taskId){e.preventDefault();openTask360(b.dataset.taskId)}});window.openTask360=openTask360;};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
