import {apiClient} from './api-client.js';

const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const workspace=()=>window.ENJAZ_WORKSPACE_ID||'';
const token=()=>window.ENJAZ_ACCESS_TOKEN||'';
const nav=[['dashboard','لوحة التحكم','⌂'],['employees','الموظفون الرقميون','◉'],['tasks','المهام','✓'],['teams','الفرق الذكية','◌'],['workflows','سير العمل','↯'],['approvals','الموافقات','◇'],['integrations','التكاملات','⊕'],['audit','سجل التدقيق','▤']];
const state={section:'dashboard',employees:[],tasks:[],approvals:[],workflows:[],integrations:[],audit:[],loading:false,error:null,taskFilter:'all',employeeFilter:'all'};
const root=()=>document.getElementById('content');
const active=x=>!['paused','disabled','inactive','offline'].includes(String(x?.status||'').toLowerCase());
const done=x=>['completed','done','success'].includes(String(x?.status||'').toLowerCase());
const running=x=>['running','in_progress','processing'].includes(String(x?.status||'').toLowerCase());
const queued=x=>['queued','pending'].includes(String(x?.status||'').toLowerCase());
const listify=x=>Array.isArray(x?.data)?x.data:Array.isArray(x)?x:[];
const ago=v=>{if(!v)return '—';const d=new Date(v);if(Number.isNaN(d.getTime()))return esc(v);const m=Math.max(0,Math.floor((Date.now()-d.getTime())/60000));if(m<1)return 'الآن';if(m<60)return `منذ ${m} د`;const h=Math.floor(m/60);if(h<24)return `منذ ${h} س`;return `منذ ${Math.floor(h/24)} ي`};
const status=v=>`<span class="status status-${esc(String(v||'unknown').toLowerCase().replace(/[^a-z0-9_-]/g,''))}">${esc(v||'—')}</span>`;
const employeeName=id=>state.employees.find(x=>String(x.id)===String(id))?.name||'غير محدد';
const initial=x=>(x?.name||'م').trim().charAt(0);

function showError(error){state.error=error?.message||String(error||'تعذر تشغيل مساحة العمل.');render();}
function openLibrary(){
  const button=document.querySelector('[data-enjaz-library]');
  if(button){button.click();return;}
  if(typeof window.ENJAZ_OPEN_WORKFORCE_LIBRARY==='function'){window.ENJAZ_OPEN_WORKFORCE_LIBRARY();return;}
  state.error='مكتبة الموظفين الجاهزين لم تُحمّل بعد. أعد المحاولة.';render();
}
function wire(){
  document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{state.section=b.dataset.nav;render();});
  document.querySelectorAll('[data-open-library]').forEach(b=>b.onclick=openLibrary);
  document.querySelectorAll('[data-action="refresh"]').forEach(b=>b.onclick=load);
  document.querySelectorAll('[data-action="tasks"]').forEach(b=>b.onclick=()=>{state.section='tasks';render();});
  document.querySelectorAll('[data-action="employees"]').forEach(b=>b.onclick=()=>{state.section='employees';render();});
  document.querySelectorAll('[data-task-filter]').forEach(b=>b.onclick=()=>{state.taskFilter=b.dataset.taskFilter;render();});
  document.querySelectorAll('[data-employee-filter]').forEach(b=>b.onclick=()=>{state.employeeFilter=b.dataset.employeeFilter;render();});
  document.querySelectorAll('[data-run-task]').forEach(b=>b.onclick=()=>runTask(b.dataset.runTask,b.dataset.employeeId));
  document.querySelectorAll('[data-plan-task]').forEach(b=>b.onclick=()=>planTask(b.dataset.planTask));
  document.querySelectorAll('[data-approval-decision]').forEach(b=>b.onclick=()=>decideApproval(b.dataset.approvalDecision,b.dataset.approvalId));
  document.querySelectorAll('[data-revoke-integration]').forEach(b=>b.onclick=()=>revokeIntegration(b.dataset.revokeIntegration));
  document.querySelectorAll('[data-action="create-task"]').forEach(b=>b.onclick=openTaskForm);
}
function render(){
  const el=root();if(!el)return;
  const pages={dashboard:dashboardPage,employees:employeesPage,tasks:tasksPage,teams:teamsPage,workflows:workflowsPage,approvals:approvalsPage,integrations:integrationsPage,audit:auditPage};
  try{el.innerHTML=(pages[state.section]||dashboardPage)();wire();}catch(error){el.innerHTML=`<div class="boot-error" role="alert"><strong>تعذر عرض مساحة العمل</strong><span>${esc(error.message||'خطأ غير متوقع')}</span><button class="primary" type="button" data-action="refresh">إعادة المحاولة</button></div>`;wire();console.error('[ENJAZ_WORKSPACE_RENDER]',error);}
}
function header(eyebrow,title,sub='',actions=''){return `<div class="pagehead"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1>${sub?`<p>${sub}</p>`:''}</div><div>${actions}</div></div>`;}
function dashboardPage(){
 const a=state.employees.filter(active).length,q=state.tasks.filter(queued).length,r=state.tasks.filter(running).length,d=state.tasks.filter(done).length,p=state.approvals.filter(x=>x.status==='pending').length;
 const latest=state.tasks.slice(0,6),recent=state.audit.slice(0,6);
 return `<section class="hero"><div><div class="eyebrow">ENJAZ / DIGITAL WORKFORCE</div><h1>مركز قيادة العمل الرقمي</h1><p>منصة تشغيل مؤسسية لإدارة الموظفين الرقميين الجاهزين، المهام، سير العمل، الموافقات والنتائج من مساحة واحدة.</p><div class="hero-meta"><span>● ${a} موظف نشط</span><span>● ${r} قيد التنفيذ</span><span>● ${p} موافقة معلقة</span></div></div><div class="hero-actions"><button class="primary" data-open-library>مكتبة الموظفين</button><button class="ghost" data-action="create-task" ${a?'':'disabled'}>+ مهمة جديدة</button></div></section>${state.error?`<div class="error" style="margin:0 35px 15px">${esc(state.error)}</div>`:''}
 <section class="stats"><div><span>الموظفون الرقميون</span><b>${state.employees.length}</b><small>${a} نشط الآن</small></div><div><span>المهام</span><b>${state.tasks.length}</b><small>${q} انتظار · ${r} تعمل</small></div><div><span>معدل الإنجاز</span><b>${state.tasks.length?Math.round(d/state.tasks.length*100):0}%</b><small>${d} مكتملة</small></div><div><span>الموافقات</span><b>${p}</b><small>تحتاج قرارًا</small></div></section>
 <section class="dashboard-grid"><div class="panel dashboard-main"><div class="section-head"><div><div class="eyebrow">OPERATIONS</div><h2>طابور التنفيذ</h2><p>المهام الأقرب إلى التنفيذ والمتابعة.</p></div><button class="ghost" data-action="refresh">${state.loading?'جارٍ التحديث…':'تحديث'}</button></div>${latest.length?`<div class="task-table"><div class="table-head"><span>المهمة</span><span>الموظف</span><span>الحالة</span><span>الإجراء</span></div>${latest.map(taskRow).join('')}</div>`:'<div class="empty compact-empty"><h2>لا توجد مهام بعد</h2><p>فعّل موظفًا رقميًا من المكتبة ثم أسند له أول مهمة.</p><button class="primary" data-open-library>فتح مكتبة الموظفين</button></div>'}</div><aside class="dashboard-side"><div class="panel"><div class="section-head"><div><div class="eyebrow">WORKFORCE</div><h2>الفريق الرقمي</h2></div><button class="ghost compact" data-action="employees">عرض الكل</button></div>${state.employees.slice(0,5).map(personRow).join('')||'<div class="empty"><p>لم تُفعّل قوة عمل بعد.</p><button class="primary" data-open-library>استكشاف الموظفين الجاهزين</button></div>'}</div><div class="panel"><div class="section-head"><div><div class="eyebrow">ACTIVITY</div><h2>آخر النشاط</h2></div></div>${recent.map(x=>`<div class="activity-row"><span class="activity-mark"></span><div><strong>${esc(x.action||x.event_type||'نشاط تشغيلي')}</strong><small>${ago(x.created_at)}</small></div></div>`).join('')||'<div class="empty"><p>سيظهر النشاط التشغيلي هنا.</p></div>'}</div></aside></section>
 <section class="panel quick-panel"><div><div class="eyebrow">READY WORKFORCE</div><h2>ابدأ من الموظف الجاهز</h2><p>اختر القطاع والدور، ثم فعّل قوة العمل داخل مؤسستك.</p></div><div class="quick-actions"><button class="quick-action" data-open-library><b>01</b><span><strong>استكشف المكتبة</strong><small>مطاعم · مستشفيات · فنادق · شركات · حكومة</small></span>←</button><button class="quick-action" data-action="employees"><b>02</b><span><strong>إدارة الفريق</strong><small>ملفات الموظفين والأداء والمهام</small></span>←</button><button class="quick-action" data-action="tasks" ${a?'':'disabled'}><b>03</b><span><strong>شغّل العمل</strong><small>المهام · التنفيذ · النتائج</small></span>←</button></div></section>`;
}
function taskRow(x){return `<div class="table-row"><div><strong>${esc(x.title||'مهمة')}</strong><small>${esc(x.objective||x.description||'بدون وصف')}</small></div><span>${esc(employeeName(x.employee_id))}</span><span>${status(x.status)}</span><div>${queued(x)?`<button class="ghost compact" data-plan-task="${esc(x.id)}">تخطيط</button><button class="ghost compact" data-run-task="${esc(x.id)}" data-employee-id="${esc(x.employee_id||'')}">تشغيل</button>`:running(x)?'<span class="muted-label">قيد التنفيذ</span>':'—'}</div></div>`;}
function personRow(x){return `<div class="person-row"><span class="avatar">${esc(initial(x))}</span><div><strong>${esc(x.name||'موظف رقمي')}</strong><small>${esc(x.role||'موظف عمليات')}</small></div><span class="dot-status ${active(x)?'':'off'}"></span></div>`;}
function employeesPage(){const a=state.employees.filter(active).length,paused=state.employees.length-a;const list=state.employees.filter(x=>state.employeeFilter==='all'||(state.employeeFilter==='active'?active(x):!active(x)));return `${header('WORKFORCE','الموظفون الرقميون','أصول تشغيلية رقمية جاهزة للعمل داخل المؤسسة.', '<button class="primary" data-open-library>مكتبة الموظفين الجاهزين</button>')}<div class="stats mini-stats"><div><span>إجمالي الفريق</span><b>${state.employees.length}</b></div><div><span>نشط</span><b>${a}</b></div><div><span>متوقف</span><b>${paused}</b></div><div><span>المهام</span><b>${state.tasks.length}</b></div></div><div class="toolbar"><div><button class="filter ${state.employeeFilter==='all'?'selected':''}" data-employee-filter="all">الكل</button><button class="filter ${state.employeeFilter==='active'?'selected':''}" data-employee-filter="active">نشط</button><button class="filter ${state.employeeFilter==='inactive'?'selected':''}" data-employee-filter="inactive">متوقف</button></div><button class="ghost" data-action="refresh">تحديث</button></div><div class="employee-grid">${list.map(employeeCard).join('')||`<div class="empty"><h2>لا توجد قوة عمل مفعّلة</h2><p>لا تنشئ موظفًا من الصفر. اختر موظفًا متخصصًا جاهزًا من مكتبة إنجاز.</p><button class="primary" data-open-library>فتح مكتبة الموظفين</button></div>`}</div>`;}
function employeeCard(x){const ts=state.tasks.filter(t=>String(t.employee_id)===String(x.id)),f=ts.filter(done).length;return `<article class="employee-card" data-open-employee="${esc(x.id)}" tabindex="0" role="button"><div class="employee-card-head"><span class="avatar avatar-lg">${esc(initial(x))}</span><div><h3>${esc(x.name||'موظف رقمي')}</h3><p>${esc(x.role||'موظف عمليات')}</p></div><span class="dot-status ${active(x)?'':'off'}"></span></div><div class="employee-tags"><span>${esc(x.status||'active')}</span><span>${ts.length} مهمة</span></div><div class="employee-metrics"><div><b>${f}</b><small>مكتملة</small></div><div><b>${ts.length-f}</b><small>مفتوحة</small></div><div><b>${ts.length?Math.round(f/ts.length*100):0}%</b><small>إنجاز</small></div></div><div class="employee-card-action">فتح ملف الموظف 360 ←</div></article>`;}
function tasksPage(){const filtered=state.tasks.filter(x=>state.taskFilter==='all'||(state.taskFilter==='queued'&&queued(x))||(state.taskFilter==='running'&&running(x))||(state.taskFilter==='done'&&done(x)));return `${header('EXECUTION','المهام','حوّل العمل إلى وحدات قابلة للتنفيذ والمتابعة.','<button class="ghost" data-action="refresh">تحديث</button>')}<div class="stats mini-stats"><div><span>الكل</span><b>${state.tasks.length}</b></div><div><span>انتظار</span><b>${state.tasks.filter(queued).length}</b></div><div><span>تنفيذ</span><b>${state.tasks.filter(running).length}</b></div><div><span>مكتملة</span><b>${state.tasks.filter(done).length}</b></div></div><div class="toolbar"><div><button class="filter ${state.taskFilter==='all'?'selected':''}" data-task-filter="all">الكل</button><button class="filter ${state.taskFilter==='queued'?'selected':''}" data-task-filter="queued">انتظار</button><button class="filter ${state.taskFilter==='running'?'selected':''}" data-task-filter="running">تنفيذ</button><button class="filter ${state.taskFilter==='done'?'selected':''}" data-task-filter="done">مكتملة</button></div><span class="toolbar-count">${filtered.length} مهمة</span></div><div class="panel task-list">${filtered.map(taskRow).join('')||'<div class="empty"><h2>لا توجد نتائج</h2><p>فعّل موظفًا رقميًا ثم أنشئ مهمة تشغيلية.</p><button class="primary" data-open-library>مكتبة الموظفين</button></div>'}</div>`;}
function teamsPage(){const grouped=state.employees.reduce((m,x)=>{const k=x.team||x.department||'القوة العاملة';(m[k]??=[]).push(x);return m},{});return `${header('ORGANIZATION','الفرق الذكية','التوزيع التنظيمي للقوة العاملة الرقمية.','<button class="ghost" data-action="refresh">تحديث</button>')}<div class="team-grid">${Object.entries(grouped).map(([name,list])=>`<article class="team-card"><div class="team-card-head"><div><div class="eyebrow">TEAM</div><h2>${esc(name)}</h2></div><b>${list.length}</b></div>${list.slice(0,6).map(personRow).join('')}</article>`).join('')||'<div class="empty"><h2>لا توجد فرق بعد</h2><p>ابدأ من مكتبة الموظفين الجاهزين.</p><button class="primary" data-open-library>استكشاف المكتبة</button></div>'}</div>`;}
function workflowsPage(){return `${header('ORCHESTRATION','سير العمل','تتبّع التنفيذ متعدد الخطوات والنتائج.','<button class="ghost" data-action="refresh">تحديث</button>')}<div class="panel workflow-list">${state.workflows.map(x=>{const total=Number(x.step_count||0),ok=Number(x.succeeded_steps||0),pct=total?Math.round(ok/total*100):0;return `<article class="workflow-row"><div><strong>${esc(x.goal||'سير عمل')}</strong><small>${ago(x.created_at)}</small></div><div class="progress"><i style="width:${Math.min(100,pct)}%"></i></div><span>${ok}/${total} خطوات</span>${status(x.status)}</article>`}).join('')||'<div class="empty"><h2>لا توجد تنفيذات</h2><p>ستظهر سير العمل هنا عند بدء التنفيذ.</p></div>'}</div>`;}
function approvalsPage(){return `${header('CONTROL','الموافقات','نقطة التحكم البشرية قبل الإجراءات الحساسة.','<button class="ghost" data-action="refresh">تحديث</button>')}<div class="stats mini-stats"><div><span>الإجمالي</span><b>${state.approvals.length}</b></div><div><span>معلقة</span><b>${state.approvals.filter(x=>x.status==='pending').length}</b></div><div><span>موافق عليها</span><b>${state.approvals.filter(x=>x.status==='approved').length}</b></div><div><span>مرفوضة</span><b>${state.approvals.filter(x=>x.status==='rejected').length}</b></div></div><div class="panel approval-list">${state.approvals.map(x=>`<article class="approval-row"><div><strong>${esc(x.reason||x.action||'طلب موافقة')}</strong><small>${ago(x.created_at)}</small></div><div>${status(x.status)} ${x.status==='pending'?`<button class="ghost compact" data-approval-decision="approve" data-approval-id="${esc(x.id)}">موافقة</button><button class="ghost compact" data-approval-decision="reject" data-approval-id="${esc(x.id)}">رفض</button>`:''}</div></article>`).join('')||'<div class="empty"><h2>لا توجد طلبات</h2><p>الطلبات التي تحتاج قرارًا ستظهر هنا.</p></div>'}</div>`;}
function integrationsPage(){return `${header('CONNECTIVITY','التكاملات','اربط إنجاز بالأنظمة التي يعمل عليها فريقك.','<button class="ghost" data-action="refresh">تحديث</button>')}<div class="integration-grid">${state.integrations.map(x=>`<article class="integration-card"><div class="integration-icon">${esc((x.provider||'I').charAt(0).toUpperCase())}</div><div class="integration-info"><h3>${esc(x.name||x.provider||'تكامل')}</h3><p>${esc(x.provider||'provider')} · ${x.enabled?'مفعّل':'معطّل'}</p></div>${x.enabled?`<button class="ghost compact" data-revoke-integration="${esc(x.id||x.connection_id||'')}">إلغاء الربط</button>`:''}</article>`).join('')||'<div class="empty"><h2>لا توجد تكاملات</h2><p>أضف التكاملات من إعدادات المؤسسة عندما تحتاجها.</p></div>'}</div>`;}
function auditPage(){return `${header('GOVERNANCE','سجل التدقيق','سجل زمني للأنشطة والأحداث داخل مساحة العمل.','<button class="ghost" data-action="refresh">تحديث</button>')}<div class="panel audit-list">${state.audit.map(x=>`<article class="audit-row"><span class="audit-mark"></span><div><strong>${esc(x.action||x.event_type||'سجل تشغيلي')}</strong><small>${esc(x.actor||x.user_id||'النظام')} · ${ago(x.created_at)}</small></div><span>${esc(x.entity_type||'event')}</span></article>`).join('')||'<div class="empty"><h2>لا توجد أحداث</h2><p>سيظهر السجل عند بدء العمليات.</p></div>'}</div>`;}

async function load(){
 if(state.loading)return;state.loading=true;state.error=null;render();
 if(!workspace()||!token()){state.loading=false;showError(new Error('جلسة مساحة العمل غير مكتملة. أعد تسجيل الدخول.'));return;}
 try{
  const results=await Promise.allSettled([apiClient.employees(workspace(),token()),apiClient.tasks(workspace(),token()),apiClient.approvals(workspace(),token()),apiClient.workflows(workspace(),token()),apiClient.integrations(workspace(),token()),apiClient.audit(workspace(),token())]);
  const [e,t,a,w,i,d]=results;
  state.employees=e.status==='fulfilled'?listify(e.value):[];state.tasks=t.status==='fulfilled'?listify(t.value):[];state.approvals=a.status==='fulfilled'?listify(a.value):[];state.workflows=w.status==='fulfilled'?listify(w.value):[];state.integrations=i.status==='fulfilled'?listify(i.value):[];state.audit=d.status==='fulfilled'?listify(d.value):[];
  const failures=results.filter(x=>x.status==='rejected');if(failures.length)state.error=`تم تشغيل مساحة العمل، لكن تعذر تحميل ${failures.length} من الخدمات. يمكنك إعادة المحاولة.`;
 }catch(error){state.error=error.message||'تعذر تحميل بيانات مساحة العمل.';}finally{state.loading=false;render();}
}
async function runTask(id,employeeId){try{await apiClient.runTask(workspace(),token(),id,{employeeId,action:'data.analyze',input:{}});await load();}catch(e){alert(e.message);}}
async function planTask(id){try{const r=await apiClient.planTask(workspace(),token(),id,{});const p=r.data?.plan||r.data||{};alert(`خطة AI جاهزة\nالهدف: ${p.goal||'—'}\nالخطوات: ${Array.isArray(p.steps)?p.steps.length:0}`);}catch(e){alert(e.message);}}
async function decideApproval(decision,id){try{await apiClient.decideApproval(workspace(),token(),id,decision);await load();}catch(e){alert(e.message);}}
async function revokeIntegration(id){if(!id||!confirm('هل تريد إلغاء ربط هذا التكامل؟'))return;try{await apiClient.revokeIntegration(workspace(),token(),id);await load();}catch(e){alert(e.message);}}
function openTaskForm(){const el=document.createElement('div');el.className='modal';el.innerHTML=`<div class="modal-card"><header><h2>إنشاء مهمة</h2><button class="ghost" type="button" data-close>×</button></header><form id="task-form" class="employee-form"><div class="form-grid"><label>عنوان المهمة<input name="title" required maxlength="160" placeholder="مثال: تحليل مبيعات هذا الأسبوع"></label><label>الموظف الرقمي<select name="employeeId" required>${state.employees.filter(active).map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('')||'<option value="">لا يوجد موظفون نشطون</option>'}</select></label><label class="full">الهدف<textarea name="objective" required maxlength="4000" placeholder="ما النتيجة المطلوبة من هذه المهمة؟"></textarea></label><label>الأولوية<select name="priority"><option value="5">متوسطة</option><option value="1">عاجلة</option><option value="3">عالية</option><option value="7">منخفضة</option></select></label></div><div class="form-actions"><button class="ghost" type="button" data-close>إلغاء</button><button class="primary" type="submit" ${state.employees.some(active)?'':'disabled'}>إنشاء المهمة</button></div></form></div>`;document.body.appendChild(el);el.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>el.remove());el.querySelector('#task-form').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('[type=submit]');b.disabled=true;try{const f=new FormData(e.currentTarget);await apiClient.createTask(workspace(),token(),{title:String(f.get('title')).trim(),employeeId:String(f.get('employeeId')),objective:String(f.get('objective')).trim(),priority:Number(f.get('priority')||5)});el.remove();state.section='tasks';await load();}catch(err){b.disabled=false;alert(err.message);}};}

window.ENJAZ_WORKSPACE_V3={render,load,openLibrary};
window.addEventListener('error',e=>{if(!root()?.children.length)showError(e.error||new Error(e.message||'تعذر تشغيل مساحة العمل.'));});
window.addEventListener('unhandledrejection',e=>{console.error('[ENJAZ_WORKSPACE_UNHANDLED]',e.reason);if(!root()?.children.length)showError(e.reason||new Error('تعذر تشغيل مساحة العمل.'));});
render();
load();
