import {apiClient} from './api-client.js';
const WORKSPACE_ID=window.ENJAZ_WORKSPACE_ID||'';const TOKEN=window.ENJAZ_ACCESS_TOKEN||'';
const sectors={restaurant:['🍽️','المطاعم'],hospital:['🏥','المستشفيات'],hotel:['🏨','الفنادق'],enterprise:['🏢','الشركات'],government:['🏛️','الجهات الحكومية']};
const nav=[['home','الرئيسية'],['library','مكتبة الموظفين'],['workforce','قوة العمل'],['tasks','المهام والتنفيذ'],['approvals','الموافقات'],['integrations','التكاملات'],['audit','سجل العمليات']];
const state={page:'home',sector:null,employees:[],templates:[],tasks:[],approvals:[],audit:[],busy:false,message:null,error:null};const app=document.querySelector('#content');
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const localKey=`ENJAZ_CATALOG_DEPLOYED:${WORKSPACE_ID||'preview'}`;const local=()=>{try{return JSON.parse(localStorage.getItem(localKey)||'[]')}catch{return[]}};const saveLocal=e=>{const a=local().filter(x=>x.catalog_key!==e.catalog_key);a.unshift(e);localStorage.setItem(localKey,JSON.stringify(a))};
const fallbackTemplates=[['restaurant','🍽️','المطاعم',['مدير المطعم','موظف الاستقبال والحجوزات','موظف خدمة العملاء','مسؤول الطلبات','مسؤول المشتريات','مسؤول المخزون','مدير العمليات','محلل أداء المطعم']],['hospital','🏥','المستشفيات',['مدير العمليات الطبية','منسق المواعيد','موظف خدمة المرضى','مسؤول المشتريات الطبية','مسؤول الجودة والامتثال','محلل أداء المستشفى','منسق الموارد','مدير تجربة المريض']],['hotel','🏨','الفنادق',['مدير الفندق','موظف الحجوزات','موظف الاستقبال','مدير الإيرادات','مسؤول التدبير الفندقي','مسؤول الصيانة','خدمة النزلاء','محلل أداء الفندق']],['enterprise','🏢','الشركات',['المدير التنفيذي الرقمي','مدير العمليات','مدير الموارد البشرية','مدير المالية','مدير المبيعات','مسؤول التسويق','مسؤول المشتريات','مدير المشاريع']],['government','🏛️','الجهات الحكومية',['مدير الخدمات الحكومية','مدير المعاملات','منسق العمليات الحكومية','محلل التقارير الحكومية','مراجع الامتثال','مسؤول تجربة المستفيد','مدير الخدمات','محلل أداء الجهة']]];
const fallback=()=>fallbackTemplates.flatMap(([sector,icon,sectorName,names])=>names.map(name=>({sector,sector_label:sectorName,name,description:`موظف رقمي متخصص في ${name}`,skills:['التخطيط','التنفيذ','المتابعة','التقارير'],tools:[],autonomy:'balanced',key:`${sector}:${name}`})));
async function load(){try{const [e,t,a,u]=await Promise.allSettled([apiClient.employees(WORKSPACE_ID,TOKEN),apiClient.tasks(WORKSPACE_ID,TOKEN),apiClient.approvals(WORKSPACE_ID,TOKEN),apiClient.audit(WORKSPACE_ID,TOKEN)]);state.employees=e.status==='fulfilled'?(e.value.data||[]):[];state.tasks=t.status==='fulfilled'?(t.value.data||[]):[];state.approvals=a.status==='fulfilled'?(a.value.data||[]):[];state.audit=u.status==='fulfilled'?(u.value.data||[]):[];try{const p=await apiClient.industryPacks(WORKSPACE_ID,TOKEN);if(p?.data?.templates)state.templates=p.data.templates}catch{} }catch(e){state.error=e.message}render()}
function templates(){return state.templates.length?state.templates.map(x=>({...x,key:`${x.sector}:${x.name}`,sector_label:x.sector_label||sectors[x.sector]?.[1]})):fallback()}
function deployed(){return new Set([...state.employees.map(e=>e.catalog_key).filter(Boolean),...local().map(e=>e.catalog_key)])}
async function activate(item){if(deployed().has(item.key)){state.message='هذا الموظف مفعّل بالفعل.';render();return}state.busy=true;state.message=null;state.error=null;render();try{const body={name:item.name,role:item.name,goal:item.default_goal||`إدارة وتنفيذ مسؤوليات ${item.name}`,sector:item.sector,autonomy:item.autonomy||'balanced',skills:item.skills||[],tools:item.tools||[],budgetCents:item.default_budget_cents||0,schedule:{type:'always'},policy:{approvalMode:'required'}};const r=await apiClient.createEmployee(WORKSPACE_ID,TOKEN,body);const e={...(r.data||body),catalog_key:item.key,sector:item.sector,sector_label:item.sector_label};saveLocal(e);state.employees=[e,...state.employees];state.page='workforce';state.message=`تم تفعيل ${item.name} داخل قوة العمل.`}catch(e){state.error=e.message}finally{state.busy=false;render()}}
async function createTask(employeeId){const title=prompt('عنوان المهمة');if(!title)return;const objective=prompt('ما الهدف الذي تريد من الموظف تنفيذه؟',title);if(!objective)return;state.busy=true;render();try{const r=await apiClient.createTask(WORKSPACE_ID,TOKEN,{employeeId,title,objective,priority:2,input:{source:'enjaz-console'}});state.tasks=[r.data,...state.tasks];state.page='tasks';state.message='تم إنشاء المهمة وإسنادها للموظف.'}catch(e){state.error=e.message}finally{state.busy=false;render()}}
async function runTask(id){state.busy=true;render();try{const r=await apiClient.runTask(WORKSPACE_ID,TOKEN,id,{});state.message=r?.message||'تم إرسال المهمة إلى محرك التنفيذ.';await load()}catch(e){state.error=e.message;state.busy=false;render()}}
async function decide(id,d){state.busy=true;render();try{await apiClient.decideApproval(WORKSPACE_ID,TOKEN,id,d);state.message=d==='approve'?'تمت الموافقة على العملية.':'تم رفض العملية.';await load()}catch(e){state.error=e.message;state.busy=false;render()}}
function shell(body){app.innerHTML=`<div class="enjaz"><aside><div class="brand"><b>إ</b><strong>إنجاز</strong><small>AI DIGITAL WORKFORCE</small></div><nav>${nav.map(n=>`<button class="${state.page===n[0]?'active':''}" data-page="${n[0]}">${n[1]}</button>`).join('')}</nav><footer><b>مساحة العمل</b>${WORKSPACE_ID?'متصلة':'وضع المعاينة'}<br>● النظام جاهز</footer></aside><main><header><span>إنجاز / ${nav.find(n=>n[0]===state.page)?.[1]||'الرئيسية'}</span><span><i>م</i></span></header>${state.message?`<div class="toast">${esc(state.message)}</div>`:''}${state.error?`<div class="toast">${esc(state.error)}</div>`:''}${body}</main></div>`;bind()}
function home(){const t=templates();return `<section class="hero"><small>ENJAZ WORKFORCE OS</small><h1>قوة عمل رقمية <em>جاهزة لمؤسستك</em></h1><p>لا تبنِ موظف الذكاء الاصطناعي من الصفر. اختر موظفًا متخصصًا، فعّله، ثم أسند له العمل ودعه يعمل ضمن الصلاحيات والموافقات وسجل التدقيق.</p><button data-page="library">استكشف مكتبة الموظفين</button></section><section class="stats"><div><small>موظفون جاهزون</small><b>${t.length}</b></div><div><small>موظفون مفعّلون</small><b>${state.employees.length}</b></div><div><small>مهام مفتوحة</small><b>${state.tasks.filter(x=>!['completed','failed','cancelled'].includes(x.status)).length}</b></div><div><small>موافقات معلقة</small><b>${state.approvals.filter(x=>x.status==='pending').length}</b></div></section><h2>اختر نوع مؤسستك</h2><section class="sectors">${Object.entries(sectors).map(([k,v])=>`<button data-sector="${k}"><i>${v[0]}</i><b>${v[1]}</b><small>موظفون متخصصون جاهزون</small></button>`).join('')}</section><div class="promise"><b>موظف رقمي، وليس روبوت محادثة</b><span>دور واضح · مهارات · أدوات · ذاكرة · صلاحيات · أهداف · تنفيذ · موافقات · سجل تدقيق</span></div>`}
function library(){const d=deployed(),all=templates(),list=state.sector?all.filter(x=>x.sector===state.sector):all;return `<section class="page"><small>EMPLOYEE MARKETPLACE</small><h1>مكتبة الموظفين الرقميين</h1><p>موظفون متخصصون جاهزون للتفعيل داخل مؤسستك.</p><div class="filters"><button class="${!state.sector?'selected':''}" data-sector="all">الكل</button>${Object.entries(sectors).map(([k,v])=>`<button class="${state.sector===k?'selected':''}" data-sector="${k}">${v[0]} ${v[1]}</button>`).join('')}</div><section class="employees">${list.map(x=>{const on=d.has(x.key);return `<article class="employee"><span class="icon">${x.sector_label?.startsWith('الم')?x.sector==='restaurant'?'🍽️':'🏥':sectors[x.sector]?.[0]||'◈'}</span><div class="grow"><b>${esc(x.name)}</b><small>${esc(x.sector_label||sectors[x.sector]?.[1]||'المؤسسة')} · موظف متخصص</small></div><label>${on?'مفعّل':'جاهز'}</label><p>${esc(x.description||'دور متخصص مصمم للعمل داخل أنظمة المؤسسة.')}</p><button data-deploy="${esc(x.key)}" ${on||state.busy?'disabled':''}>${on?'✓ الموظف مفعّل':state.busy?'جارٍ التفعيل…':'تفعيل الموظف'}</button></article>`}).join('')}</section></section>`}
function workforce(){return `<section class="page"><small>ACTIVE WORKFORCE</small><h1>قوة العمل الرقمية</h1><p>هنا يظهر كل موظف حقيقي تم تفعيله داخل مساحة العمل.</p>${state.employees.length?`<section class="employees">${state.employees.map(e=>`<article class="employee"><span class="icon">${sectors[e.sector]?.[0]||'◈'}</span><div class="grow"><b>${esc(e.name)}</b><small>${esc(e.role||'موظف رقمي')} · ${esc(e.sector_label||sectors[e.sector]?.[1]||'المؤسسة')}</small></div><label>${esc(e.status||'active')}</label><p>هدف: ${esc(e.goal||'تنفيذ مسؤوليات الدور بكفاءة وحوكمة.')}</p><button data-task="${esc(e.id)}">إسناد مهمة</button></article>`).join('')}</section>`:'<div class="empty"><b>لا يوجد موظفون مفعّلون بعد</b><br>ابدأ من مكتبة الموظفين.</div>'}</section>`}
const status=x=>({pending:'قيد الانتظار',running:'قيد التنفيذ',waiting_approval:'بانتظار الموافقة',completed:'مكتملة',failed:'فشلت',cancelled:'ملغاة'}[x]||x||'—');
function tasks(){return `<section class="page"><small>EXECUTION CENTER</small><h1>المهام والتنفيذ</h1><p>المهمة الحقيقية تمر من الإسناد إلى التخطيط والتنفيذ ثم النتيجة أو الموافقة.</p>${state.tasks.length?`<div class="ops-list">${state.tasks.map(t=>`<article class="op"><div><b>${esc(t.title)}</b><small>${esc(t.objective)}</small></div><label>${status(t.status)}</label><span>أولوية ${t.priority}</span>${['pending','failed'].includes(t.status)?`<button data-run="${t.id}" ${state.busy?'disabled':''}>تشغيل</button>`:''}</article>`).join('')}</div>`:'<div class="empty"><b>لا توجد مهام بعد</b><br>اذهب إلى قوة العمل وأسند أول مهمة لموظفك.</div>'}</section>`}
function approvals(){return `<section class="page"><small>HUMAN GOVERNANCE</small><h1>الموافقات</h1><p>العمليات الحساسة لا تتجاوز سياسة المؤسسة دون قرار بشري.</p>${state.approvals.length?`<div class="ops-list">${state.approvals.map(a=>`<article class="op"><div><b>${esc(a.action)}</b><small>${esc(a.reason||'طلب موافقة على إجراء من الموظف الرقمي')}</small></div><label>${status(a.status)}</label>${a.status==='pending'?`<button data-approve="${a.id}" data-decision="approve">موافقة</button><button data-approve="${a.id}" data-decision="reject">رفض</button>`:''}</article>`).join('')}</div>`:'<div class="empty"><b>لا توجد موافقات معلقة</b><br>سيظهر هنا كل إجراء يحتاج قرارًا بشريًا.</div>'}</section>`}
function audit(){return `<section class="page"><small>IMMUTABLE AUDIT TRAIL</small><h1>سجل العمليات</h1><p>تتبع من فعل ماذا، وعلى أي موظف ومهمة، ومتى.</p>${state.audit.length?`<div class="ops-list">${state.audit.slice(0,50).map(a=>`<article class="op"><div><b>${esc(a.action||a.event_type)}</b><small>${esc(a.actor_type||'system')} · ${new Date(a.created_at).toLocaleString('ar')}</small></div><label>${esc(a.event_type||'event')}</label></article>`).join('')}</div>`:'<div class="empty"><b>السجل فارغ حاليًا</b></div>'}</section>`}
function simple(title,sub,items){return `<section class="page"><small>ENJAZ CONTROL CENTER</small><h1>${title}</h1><p>${sub}</p><div class="ops-list">${items.map(x=>`<article class="op"><div><b>${esc(x.name||x.provider||'تكامل')}</b><small>${esc(x.status||'متاح')}</small></div></article>`).join('')||'<div class="empty">لا توجد بيانات بعد.</div>'}</div></section>`}
async function integrations(){try{const r=await apiClient.integrations(WORKSPACE_ID,TOKEN);state._integrations=r.data||[]}catch(e){state._integrations=[]}return simple('التكاملات','اربط الموظفين بالأنظمة التي يعملون داخلها.',state._integrations)}
function bind(){document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>{state.message=null;state.error=null;state.page=x.dataset.page;render()});document.querySelectorAll('[data-sector]').forEach(x=>x.onclick=()=>{state.sector=x.dataset.sector==='all'?null:x.dataset.sector;state.page='library';render()});document.querySelectorAll('[data-deploy]').forEach(x=>x.onclick=()=>{const item=templates().find(i=>i.key===x.dataset.deploy);if(item)activate(item)});document.querySelectorAll('[data-task]').forEach(x=>x.onclick=()=>createTask(x.dataset.task));document.querySelectorAll('[data-run]').forEach(x=>x.onclick=()=>runTask(x.dataset.run));document.querySelectorAll('[data-approve]').forEach(x=>x.onclick=()=>decide(x.dataset.approve,x.dataset.decision))}
async function render(){let body;if(state.page==='home')body=home();else if(state.page==='library')body=library();else if(state.page==='workforce')body=workforce();else if(state.page==='tasks')body=tasks();else if(state.page==='approvals')body=approvals();else if(state.page==='audit')body=audit();else if(state.page==='integrations')body=await integrations();else body=home();shell(body)}
render();load();