import {apiClient} from './api-client.js';
import {getSession,token,user,signIn,signUp,signOut,configured} from './auth.js';
const app=document.querySelector('#content');
const sectors={restaurant:['🍽️','المطاعم'],hospital:['🏥','المستشفيات'],hotel:['🏨','الفنادق'],enterprise:['🏢','الشركات'],government:['🏛️','الجهات الحكومية']};
const nav=[['home','نظرة عامة'],['library','مكتبة الموظفين'],['workforce','قوة العمل'],['tasks','المهام'],['approvals','الموافقات'],['integrations','التكاملات'],['audit','سجل التدقيق']];
const state={page:'home',sector:null,employees:[],templates:[],tasks:[],approvals:[],integrations:[],audit:[],workspace:null,busy:false,message:'',error:''};
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const status=x=>({pending:'قيد الانتظار',queued:'في التنفيذ',running:'قيد التنفيذ',waiting_approval:'بانتظار الموافقة',completed:'مكتملة',failed:'فشلت',cancelled:'ملغاة',active:'نشط',paused:'متوقف',disabled:'معطل'}[x]||x||'—');
const data=r=>Array.isArray(r?.data)?r.data:[];
function session(){return getSession()}
async function bootstrap(){const s=session();if(!s?.access_token)return false;try{const r=await apiClient.onboardingBootstrap(s.access_token,{authUserId:s.user?.id,email:s.user?.email,name:s.user?.user_metadata?.full_name||s.user?.email?.split('@')[0]||'مستخدم إنجاز',organizationName:'مؤسسة إنجاز',workspaceName:'مساحة العمل الرئيسية'});state.workspace=r?.workspaces?.[0]||null;window.ENJAZ_WORKSPACE_ID=state.workspace?.id||'';window.ENJAZ_ACCESS_TOKEN=s.access_token;return Boolean(state.workspace?.id)}catch(e){state.error=e.message||'تعذر تهيئة مساحة العمل.';return false}}
function authScreen(mode='login',error=''){const signup=mode==='signup';app.innerHTML=`<div class="auth-shell"><section class="auth-brand"><div class="auth-logo"><b>إ</b><div><strong>إنجاز</strong><small>GLOBAL DIGITAL WORKFORCE</small></div></div><div class="auth-copy"><small>ENJAZ WORKFORCE OS</small><h1>حوّل مؤسستك إلى <span>قوة عمل رقمية.</span></h1><p>موظفون رقميون متخصصون يعملون داخل مؤسستك: يخططون، ينفذون، يتعاملون مع أدواتك، ويحافظون على الحوكمة وسجل التدقيق.</p></div><div class="auth-proof"><span>AI Employees</span><span>Enterprise Security</span><span>Human Governance</span><span>Multi‑Industry</span></div></section><section class="auth-panel"><div class="auth-card"><span class="eyebrow">${signup?'CREATE YOUR WORKSPACE':'ENTERPRISE ACCESS'}</span><h2>${signup?'ابدأ مع إنجاز':'تسجيل الدخول'}</h2><p>${signup?'أنشئ حسابك وابدأ ببناء أول قوة عمل رقمية.':'ادخل إلى مساحة عملك وإدارة موظفيك الرقميين.'}</p>${error?`<div class="auth-error">${esc(error)}</div>`:''}<form class="auth-form" id="authForm">${signup?`<div class="auth-field"><label>الاسم</label><input name="name" autocomplete="name" placeholder="اسمك أو اسم المسؤول" required></div>`:''}<div class="auth-field"><label>البريد الإلكتروني</label><input name="email" type="email" autocomplete="email" placeholder="name@company.com" required></div><div class="auth-field"><label>كلمة المرور</label><input name="password" type="password" autocomplete="${signup?'new-password':'current-password'}" placeholder="••••••••" minlength="6" required></div><button class="auth-submit" type="submit">${signup?'إنشاء الحساب':'دخول إلى إنجاز'}</button></form><div class="auth-switch">${signup?'لديك حساب بالفعل؟':'ليس لديك حساب؟'} <button id="authSwitch">${signup?'تسجيل الدخول':'إنشاء حساب'}</button></div><div class="auth-note">تستخدم إنجاز مصادقة مؤسسية مرتبطة بـ Supabase. لا يتم وضع مفاتيح الخدمة أو الأسرار داخل المتصفح.</div></div></section></div>`;document.querySelector('#authForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const email=f.get('email'),password=f.get('password'),name=f.get('name')||'';const btn=e.currentTarget.querySelector('button');btn.disabled=true;try{const s=signup?await signUp(email,password,name):await signIn(email,password);if(signup&&!s?.access_token){authScreen('login','تم إنشاء الحساب. إذا كان تأكيد البريد مفعّلًا، أكد بريدك ثم سجّل الدخول.');return}await start()}catch(err){authScreen(mode,err.message||'تعذر تسجيل الدخول.')}finally{btn.disabled=false}});document.querySelector('#authSwitch').onclick=()=>authScreen(signup?'login':'signup')}
async function start(){const s=session();if(!s?.access_token){authScreen('login');return}window.ENJAZ_ACCESS_TOKEN=s.access_token;if(!state.workspace)await bootstrap();if(!state.workspace){authScreen('login',state.error||'تعذر إنشاء مساحة العمل.');return}await load()}
async function load(){state.error='';const w=state.workspace?.id,t=token();const jobs=await Promise.allSettled([apiClient.employees(w,t),apiClient.tasks(w,t),apiClient.approvals(w,t),apiClient.integrations(w,t),apiClient.audit(w,t),apiClient.industryPacks(w,t)]);const[e,ta,a,i,u,p]=jobs;state.employees=data(e.value);state.tasks=data(ta.value);state.approvals=data(a.value);state.integrations=data(i.value);state.audit=data(u.value);state.templates=data(p.value?.templates?{data:p.value.templates}:p.value);render()}
function templates(){return state.templates.map(x=>({...x,key:`${x.sector}:${x.name}`,sector_label:x.sector_label||sectors[x.sector]?.[1]}))}
function shell(body){const u=user();app.innerHTML=`<div class="enjaz"><aside><div class="brand"><b>إ</b><strong>إنجاز</strong><small>GLOBAL DIGITAL WORKFORCE</small></div><nav>${nav.map(n=>`<button class="${state.page===n[0]?'active':''}" data-page="${n[0]}">${n[1]}</button>`).join('')}</nav><footer>مساحة العمل<br>● متصلة</footer></aside><main><header><span>إنجاز / ${nav.find(n=>n[0]===state.page)?.[1]||'الرئيسية'}</span><div class="app-topbar"><span>${esc(state.workspace?.name||'مساحة العمل')}</span><span class="app-user"><i>${esc((u?.user_metadata?.full_name||u?.email||'إ')[0].toUpperCase())}</i><button id="logout">خروج</button></span></div></header>${state.message?`<div class="toast">${esc(state.message)}</div>`:''}${state.error?`<div class="toast">${esc(state.error)}</div>`:''}${body}</main></div>`;bind()}
function home(){const t=templates(),open=state.tasks.filter(x=>!['completed','failed','cancelled'].includes(x.status)).length,pending=state.approvals.filter(x=>x.status==='pending').length;return `<section class="hero"><small>ENJAZ WORKFORCE OS</small><h1>إدارة المؤسسة عبر <em>قوة عمل رقمية</em></h1><p>لا تبنِ روبوتًا لكل مهمة. اختر موظفًا متخصصًا، امنحه الأدوات والصلاحيات والذاكرة، ثم دعه ينفذ العمل تحت حوكمة مؤسستك.</p><button data-page="library">استكشف مكتبة الموظفين</button></section><section class="metric-row"><div><small>موظفون جاهزون</small><b>${t.length}</b></div><div><small>موظفون مفعّلون</small><b>${state.employees.length}</b></div><div><small>مهام مفتوحة</small><b>${open}</b></div><div><small>موافقات معلقة</small><b>${pending}</b></div></section><div class="home-grid"><div class="home-card"><h3>مركز القيادة</h3><p>من هنا تدير القوة العاملة، التنفيذ، الموافقات والتكاملات من مساحة واحدة.</p><div class="quick-actions"><button data-page="library">+ إضافة موظف رقمي</button><button data-page="workforce">إدارة قوة العمل</button><button data-page="tasks">متابعة التنفيذ</button><button data-page="approvals">مراجعة الموافقات</button></div></div><div class="home-card"><h3>قطاعات إنجاز</h3><p>قوالب جاهزة للعمل الفعلي.</p>${Object.entries(sectors).map(([k,v])=>`<button class="sector-line" data-page="library" data-sector="${k}">${v[0]} ${v[1]} <span>›</span></button>`).join('')}</div></div></section>`}
function library(){const all=templates(),list=state.sector?all.filter(x=>x.sector===state.sector):all,deployed=new Set(state.employees.map(e=>e.catalog_key).filter(Boolean));return `<section class="app-page page"><small>EMPLOYEE MARKETPLACE</small><h1>مكتبة الموظفين</h1><p>موظفون رقميون جاهزون حسب القطاع والوظيفة، بدل البدء من صفحة فارغة.</p><div class="filters"><button class="${!state.sector?'selected':''}" data-sector="all">الكل</button>${Object.entries(sectors).map(([k,v])=>`<button class="${state.sector===k?'selected':''}" data-sector="${k}">${v[0]} ${v[1]}</button>`).join('')}</div><section class="employees">${list.map(x=>{const on=deployed.has(x.key);return `<article class="employee"><span class="icon">${sectors[x.sector]?.[0]||'◈'}</span><div class="grow"><b>${esc(x.name)}</b><small>${esc(x.sector_label||'المؤسسة')} · موظف رقمي متخصص</small></div><label>${on?'مفعّل':'جاهز'}</label><p>${esc(x.description||'موظف متخصص مصمم للعمل داخل أنظمة المؤسسة.')}</p><button data-deploy="${esc(x.key)}" ${on||state.busy?'disabled':''}>${on?'✓ مفعّل':'تفعيل الموظف'}</button></article>`}).join('')}</section></section>`}
function workforce(){return `<section class="app-page page"><small>ACTIVE WORKFORCE</small><h1>قوة العمل</h1><p>موظفون حقيقيون مرتبطون بمساحة العمل الحالية.</p>${state.employees.length?`<section class="employees">${state.employees.map(e=>`<article class="employee"><span class="icon">${sectors[e.sector]?.[0]||'◈'}</span><div class="grow"><b>${esc(e.name)}</b><small>${esc(e.role||'موظف رقمي')}</small></div><label>${status(e.status)}</label><p>${esc(e.goal||'تنفيذ مسؤوليات الدور ضمن سياسة المؤسسة.')}</p><button data-task="${e.id}">إسناد مهمة</button></article>`).join('')}</section>`:'<div class="empty"><b>لم تُفعّل أي قوة عمل بعد</b>ابدأ من مكتبة الموظفين.</div>'}</section>`}
function tasks(){return `<section class="app-page page"><small>EXECUTION CENTER</small><h1>المهام والتنفيذ</h1><p>راقب دورة المهمة من الإسناد والتخطيط حتى النتيجة أو الموافقة.</p>${state.tasks.length?`<div class="ops-list">${state.tasks.map(t=>`<article class="op"><div><b>${esc(t.title)}</b><small>${esc(t.objective)}</small></div><label>${status(t.status)}</label>${['pending','queued','failed'].includes(t.status)?`<button data-run="${t.id}">تشغيل</button>`:''}</article>`).join('')}</div>`:'<div class="empty"><b>لا توجد مهام</b>أسند أول مهمة من قوة العمل.</div>'}</section>`}
function approvals(){return `<section class="app-page page"><small>HUMAN GOVERNANCE</small><h1>الموافقات</h1><p>الإجراءات الحساسة تتوقف حتى يقرر الإنسان.</p>${state.approvals.length?`<div class="ops-list">${state.approvals.map(a=>`<article class="op"><div><b>${esc(a.action)}</b><small>${esc(a.reason||'طلب موافقة')}</small></div><label>${status(a.status)}</label>${a.status==='pending'?`<button data-approve="${a.id}" data-decision="approve">موافقة</button><button data-approve="${a.id}" data-decision="reject">رفض</button>`:''}</article>`).join('')}</div>`:'<div class="empty"><b>لا توجد موافقات معلقة</b>سيظهر هنا كل إجراء يحتاج قرارًا بشريًا.</div>'}</section>`}
function simple(title,kicker,text,items){return `<section class="app-page page"><small>${kicker}</small><h1>${title}</h1><p>${text}</p><div class="ops-list">${items.length?items.map(x=>`<article class="op"><div><b>${esc(x.name||x.action||x.event_type||'عملية')}</b><small>${esc(x.status||x.action||x.event_type||'')}</small></div></article>`).join(''):'<div class="empty"><b>لا توجد بيانات بعد</b>ستظهر العمليات هنا عند بدء استخدام المنصة.</div>'}</div></section>`}
function render(){if(!session()?.access_token){authScreen('login');return}const body=state.page==='home'?home():state.page==='library'?library():state.page==='workforce'?workforce():state.page==='tasks'?tasks():state.page==='approvals'?approvals():state.page==='integrations'?simple('التكاملات','CONNECTED SYSTEMS','اربط أنظمة مؤسستك واحتفظ بالتحكم والصلاحيات وسجل التدقيق.',state.integrations):simple('سجل التدقيق','AUDIT TRAIL','سجل مركزي للقرارات والتنفيذ والأحداث.',state.audit);shell(body)}
async function deploy(key){const item=templates().find(x=>x.key===key);if(!item)return;state.busy=true;render();try{await apiClient.createEmployee(state.workspace.id,token(),{name:item.name,role:item.name,goal:item.default_goal||`إدارة وتنفيذ مسؤوليات ${item.name}`,sector:item.sector,autonomy:item.autonomy||'balanced',skills:item.skills||[],tools:item.tools||[],budgetCents:item.default_budget_cents||0,schedule:{type:'always'},policy:{approvalMode:'required'},catalog_key:item.key});state.message=`تم تفعيل ${item.name}.`;await load()}catch(e){state.error=e.message||'تعذر التفعيل.';state.busy=false;render()}}
async function createTask(id){const title=prompt('عنوان المهمة');if(!title)return;state.busy=true;render();try{await apiClient.createTask(state.workspace.id,token(),{employeeId:id,title:title.trim(),objective:title.trim(),priority:2,input:{source:'enjaz'}});state.message='تم إنشاء المهمة.';await load();state.page='tasks';render()}catch(e){state.error=e.message;state.busy=false;render()}}
async function run(id){state.busy=true;render();try{await apiClient.runTask(state.workspace.id,token(),id,{});state.message='تم إرسال المهمة إلى محرك التنفيذ.';await load()}catch(e){state.error=e.message;state.busy=false;render()}}
async function decide(id,d){state.busy=true;render();try{await apiClient.decideApproval(state.workspace.id,token(),id,d);state.message=d==='approve'?'تمت الموافقة.':'تم الرفض.';await load()}catch(e){state.error=e.message;state.busy=false;render()}}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;state.sector=b.dataset.sector&&b.dataset.sector!=='all'?b.dataset.sector:null;render()});document.querySelectorAll('[data-sector]').forEach(b=>b.onclick=()=>{state.sector=b.dataset.sector==='all'?null:b.dataset.sector;state.page='library';render()});document.querySelectorAll('[data-deploy]').forEach(b=>b.onclick=()=>deploy(b.dataset.deploy));document.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>createTask(b.dataset.task));document.querySelectorAll('[data-run]').forEach(b=>b.onclick=()=>run(b.dataset.run));document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>decide(b.dataset.approve,b.dataset.decision));document.querySelector('#logout')?.addEventListener('click',async()=>{await signOut();state.workspace=null;state.page='home';authScreen('login')})}
if(!configured()&&!session()){authScreen('login','تسجيل الدخول يحتاج ربط Supabase في متغيرات VITE_SUPABASE_URL و VITE_SUPABASE_ANON_KEY.')}else{start()}
