import {apiClient} from './api-client.js';
const WORKSPACE_ID=window.ENJAZ_WORKSPACE_ID||'';
const TOKEN=window.ENJAZ_ACCESS_TOKEN||'';
const sectors={restaurant:['🍽️','المطاعم',['مدير المطعم','موظف الاستقبال والحجوزات','موظف خدمة العملاء','مسؤول الطلبات','مسؤول المشتريات','مسؤول المخزون','مدير العمليات','محلل أداء المطعم']],hospital:['🏥','المستشفيات',['مدير العمليات الطبية','منسق المواعيد','موظف خدمة المرضى','مسؤول المشتريات الطبية','مسؤول الجودة والامتثال','محلل أداء المستشفى','منسق الموارد','مدير تجربة المريض']],hotel:['🏨','الفنادق',['مدير الفندق','موظف الحجوزات','موظف الاستقبال','مدير الإيرادات','مسؤول التدبير الفندقي','مسؤول الصيانة','خدمة النزلاء','محلل أداء الفندق']],enterprise:['🏢','الشركات',['المدير التنفيذي الرقمي','مدير العمليات','مدير الموارد البشرية','مدير المالية','مدير المبيعات','مسؤول التسويق','مسؤول المشتريات','مدير المشاريع']],government:['🏛️','الجهات الحكومية',['مدير الخدمات الحكومية','مدير المعاملات','منسق العمليات الحكومية','محلل التقارير الحكومية','مراجع الامتثال','مسؤول تجربة المستفيد','مدير الخدمات','محلل أداء الجهة']]];
const nav=[['home','الرئيسية'],['library','مكتبة الموظفين'],['workforce','قوة العمل'],['tasks','المهام والتنفيذ'],['approvals','الموافقات'],['integrations','التكاملات'],['audit','سجل العمليات']];
const state={page:'home',sector:null,employees:[],busy:false,message:null,error:null};
const app=document.querySelector('#content');
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const catalog=()=>Object.entries(sectors).flatMap(([sector,v])=>v[2].map(name=>({sector,sectorName:v[1],icon:v[0],name,key:`${sector}:${name}`})));
function local(){try{return JSON.parse(localStorage.getItem(`ENJAZ_CATALOG_DEPLOYED:${WORKSPACE_ID||'preview'}`)||'[]')}catch{return[]}}
function saveLocal(e){const a=local().filter(x=>x.catalog_key!==e.catalog_key);a.unshift(e);localStorage.setItem(`ENJAZ_CATALOG_DEPLOYED:${WORKSPACE_ID||'preview'}`,JSON.stringify(a))}
function deployed(){return new Set([...state.employees.map(e=>e.catalog_key).filter(Boolean),...local().map(e=>e.catalog_key)])}
async function load(){try{const r=await apiClient.employees(WORKSPACE_ID,TOKEN);state.employees=r.data||[]}catch(e){state.error=e.message}render()}
async function activate(item){if(deployed().has(item.key)){state.message='هذا الموظف مفعّل بالفعل.';render();return}state.busy=true;state.message=null;state.error=null;render();try{const body={name:item.name,role:item.name,goal:`إدارة وتنفيذ مسؤوليات ${item.name} داخل ${item.sectorName}`,sector:item.sector,autonomy:'balanced',skills:['التخطيط','التنفيذ','المتابعة','التقارير'],tools:[],budgetCents:0,schedule:{type:'always'},policy:{approvalMode:'required'}};const r=await apiClient.createEmployee(WORKSPACE_ID,TOKEN,body);const e={...(r.data||body),catalog_key:item.key,sector:item.sector,sector_label:item.sectorName};saveLocal(e);state.employees=[e,...state.employees];state.page='workforce';state.message=`تم تفعيل ${item.name} بنجاح.`}catch(e){state.error=e.message}finally{state.busy=false;render()}}
function shell(body){app.innerHTML=`<div class="enjaz"><aside><div class="brand"><b>إ</b><strong>إنجاز</strong><small>AI DIGITAL WORKFORCE</small></div><nav>${nav.map(n=>`<button class="${state.page===n[0]?'active':''}" data-page="${n[0]}">${n[1]}</button>`).join('')}</nav><footer><b>مساحة العمل</b>${WORKSPACE_ID?'متصلة':'وضع المعاينة'}<br>● النظام جاهز</footer></aside><main><header><span>إنجاز / ${nav.find(n=>n[0]===state.page)?.[1]||'الرئيسية'}</span><span><i>م</i></span></header>${state.message?`<div class="toast">${esc(state.message)}</div>`:''}${state.error?`<div class="toast">${esc(state.error)}</div>`:''}${body}</main></div>`;bind()}
function home(){const c=catalog();return `<section class="hero"><small>ENJAZ WORKFORCE OS</small><h1>قوة عمل رقمية <em>جاهزة لمؤسستك</em></h1><p>لا تبنِ موظف الذكاء الاصطناعي من الصفر. اختر قطاعك وستجد موظفين متخصصين مصممين مسبقًا لوظائف حقيقية، ثم فعّلهم داخل مساحة عملك.</p><button data-page="library">استكشف مكتبة الموظفين</button></section><section class="stats"><div><small>موظفون جاهزون</small><b>${c.length}</b></div><div><small>قطاعات</small><b>${Object.keys(sectors).length}</b></div><div><small>مفعّلون</small><b>${state.employees.length}</b></div><div><small>حوكمة</small><b>100%</b></div></section><h2>اختر نوع مؤسستك</h2><section class="sectors">${Object.entries(sectors).map(([k,v])=>`<button data-sector="${k}"><i>${v[0]}</i><b>${v[1]}</b><small>${v[2].length} موظفين متخصصين</small></button>`).join('')}</section><div class="promise"><b>موظف رقمي، وليس روبوت محادثة</b><span>دور واضح · مهارات · أدوات · ذاكرة · صلاحيات · أهداف · تنفيذ · سجل تدقيق</span></div>`}
function library(){const keys=state.sector?[state.sector]:Object.keys(sectors);const d=deployed();const list=keys.flatMap(s=>sectors[s][2].map(name=>({sector:s,sectorName:sectors[s][1],icon:sectors[s][0],name,key:`${s}:${name}`})));return `<section class="page"><small>EMPLOYEE MARKETPLACE</small><h1>مكتبة الموظفين الرقميين</h1><p>موظفون متخصصون جاهزون للتفعيل داخل مؤسستك.</p><div class="filters"><button class="${!state.sector?'selected':''}" data-sector="all">الكل</button>${Object.entries(sectors).map(([k,v])=>`<button class="${state.sector===k?'selected':''}" data-sector="${k}">${v[0]} ${v[1]}</button>`).join('')}</div><section class="employees">${list.map(x=>{const on=d.has(x.key);return `<article class="employee"><span class="icon">${x.icon}</span><div class="grow"><b>${esc(x.name)}</b><small>${esc(x.sectorName)} · موظف متخصص</small></div><label>${on?'مفعّل':'جاهز'}</label><p>مهارات · أدوات · ذاكرة · صلاحيات · أهداف · تنفيذ</p><button data-deploy="${esc(x.key)}" ${on||state.busy?'disabled':''}>${on?'✓ الموظف مفعّل':state.busy?'جارٍ التفعيل…':'تفعيل الموظف'}</button></article>`}).join('')}</section></section>`}
function workforce(){return `<section class="page"><small>ACTIVE WORKFORCE</small><h1>قوة العمل الرقمية</h1><p>الموظفون الذين تم تفعيلهم داخل مساحة العمل.</p>${state.employees.length?`<section class="employees">${state.employees.map(e=>`<article class="employee"><span class="icon">${sectors[e.sector]?.[0]||'◈'}</span><div class="grow"><b>${esc(e.name)}</b><small>${esc(e.role||'موظف رقمي')} · ${esc(e.sector_label||sectors[e.sector]?.[1]||'المؤسسة')}</small></div><label>نشط</label><p>جاهز لاستقبال المهام وتنفيذها وفق الصلاحيات والسياسات.</p><button data-page="tasks">إسناد مهمة</button></article>`).join('')}</section>`:'<div class="empty"><b>لا يوجد موظفون مفعّلون بعد</b><br>ابدأ من مكتبة الموظفين.</div>'}</section>`}
function operations(title){return `<section class="page"><small>ENJAZ OPERATIONS</small><h1>${title}</h1><p>الموظف ← المهمة ← التنفيذ ← الموافقة ← سجل التدقيق.</p><div class="empty"><b>${state.employees.length?'قوة العمل جاهزة':'ابدأ بتفعيل موظف'}</b><br>${state.employees.length?'يمكن الآن ربط المهام والتكاملات وسير العمل بالموظفين.':'فعّل موظفًا من مكتبة إنجاز لبدء العمليات.'}</div></section>`}
function bind(){document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>{state.message=null;state.error=null;state.page=x.dataset.page;render()});document.querySelectorAll('[data-sector]').forEach(x=>x.onclick=()=>{state.message=null;state.sector=x.dataset.sector==='all'?null:x.dataset.sector;state.page='library';render()});document.querySelectorAll('[data-deploy]').forEach(x=>x.onclick=()=>{const item=catalog().find(i=>i.key===x.dataset.deploy);if(item)activate(item)})}
function render(){const body=state.page==='home'?home():state.page==='library'?library():state.page==='workforce'?workforce():operations(nav.find(n=>n[0]===state.page)?.[1]||'إنجاز');shell(body)}
render();load();