import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowUpLeft,Check,ChevronLeft,CircleCheck,Command,GitBranch,LockKeyhole,Menu,Network,Play,ShieldCheck,Sparkles,Workflow,Zap} from 'lucide-react';

const roles=[['AI Manager','يدير الأهداف والقرارات التشغيلية'],['AI Analyst','يحوّل البيانات إلى رؤى قابلة للتنفيذ'],['AI Operations Worker','ينفّذ الأعمال المتكررة ضمن الصلاحيات'],['AI Coordinator','ينسّق المهام بين البشر والموظفين الرقميين'],['AI Customer Service Worker','يتعامل مع طلبات العملاء وفق السياسات']];
const sectors=['المطاعم','المستشفيات','الفنادق','الشركات','الجهات الحكومية'];
const tools=['OpenAI','GitHub','Vercel','Supabase','n8n','Enterprise APIs','MCP Tools','Databases'];

function LiveConsole(){const [tab,setTab]=useState('command');const [step,setStep]=useState(2);
 useEffect(()=>{const t=setInterval(()=>setStep(s=>(s+1)%4),2600);return()=>clearInterval(t)},[]);
 return <div className="relative overflow-hidden rounded-[30px] border border-white/10 bg-[#071f17] shadow-[0_35px_100px_rgba(3,37,26,.25)]">
  <div className="flex items-center justify-between border-b border-white/10 px-5 py-4 text-xs"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_15px_#34d399]"/><span className="text-emerald-100">ENJAZ COMMAND CENTER</span></div><span className="rounded-full border border-emerald-300/20 bg-emerald-300/10 px-2 py-1 text-[9px] text-emerald-200">DEMO MODE</span></div>
  <div className="grid min-h-[440px] md:grid-cols-[150px_1fr]">
   <aside className="hidden border-l border-white/10 bg-black/10 p-3 md:block"><div className="mb-7 text-lg font-bold">إنجاز</div>{[['command','مركز القيادة'],['work','القوى العاملة'],['flow','سير العمل'],['guard','الحوكمة']].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`mb-1 flex w-full items-center gap-2 rounded-xl px-3 py-3 text-right text-[11px] ${tab===id?'bg-emerald-400/15 text-emerald-200':'text-slate-400'}`}>{label}</button>)}</aside>
   <main className="relative p-5 md:p-7"><div className="mb-6 flex items-end justify-between"><div><p className="text-[10px] uppercase tracking-[.2em] text-emerald-300">LIVE PRODUCT PREVIEW</p><h3 className="mt-2 text-xl font-semibold text-white md:text-2xl">{tab==='command'?'ماذا يحدث الآن؟':tab==='work'?'القوى العاملة الرقمية':tab==='flow'?'سير العمل الذكي':'طبقة الحوكمة'}</h3></div><Sparkles className="text-emerald-300" size={20}/></div>
   {tab==='command'&&<div className="space-y-3">{[['مهمة جديدة','AI Coordinator','جاري التخطيط'],['قرار حساس','Human Reviewer','بانتظار الموافقة'],['سجل التدقيق','Governance','تم التحقق']].map((x,i)=><div key={x[0]} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[.045] p-4"><div className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-400/10 text-emerald-300">{i===0?<Workflow size={18}/>:i===1?<ShieldCheck size={18}/>:<LockKeyhole size={18}/>}</div><div className="min-w-0 flex-1"><div className="text-xs text-white">{x[0]}</div><div className="mt-1 text-[10px] text-slate-400">{x[1]}</div></div><span className="text-[9px] text-emerald-300">{x[2]}</span></div>)}</div>}
   {tab==='work'&&<div className="grid gap-3 sm:grid-cols-2">{roles.slice(0,4).map((r,i)=><div key={r[0]} className="rounded-2xl border border-white/10 bg-white/[.045] p-4"><div className="mb-5 flex items-center justify-between"><span className="grid h-9 w-9 place-items-center rounded-full bg-emerald-400/15 text-xs text-emerald-200">AI</span><span className="h-2 w-2 rounded-full bg-emerald-400"/></div><b className="text-xs text-white">{r[0]}</b><p className="mt-1 text-[10px] leading-6 text-slate-400">{r[1]}</p></div>)}</div>}
   {tab==='flow'&&<div className="relative pt-8"><div className="absolute left-8 right-8 top-[68px] h-px bg-white/10"/><div className="grid grid-cols-4 gap-2">{['الهدف','التخطيط','الموافقة','التنفيذ'].map((s,i)=><div key={s} className="relative text-center"><div className={`mx-auto grid h-12 w-12 place-items-center rounded-2xl border ${i<=step?'border-emerald-300/40 bg-emerald-400/15 text-emerald-200':'border-white/10 bg-white/5 text-slate-500'}`}>{i<step?<Check size={18}/>:i===step?<Play size={16}/>:<span>{i+1}</span>}</div><span className="mt-3 block text-[9px] text-slate-400">{s}</span></div>)}</div><div className="mt-16 rounded-2xl border border-emerald-300/15 bg-emerald-300/5 p-4 text-center text-xs text-emerald-100">المسار يتقدم تلقائيًا حتى يصل إلى نقطة القرار البشري.</div></div>}
   {tab==='guard'&&<div className="grid gap-3">{['Role & Permissions','Policy Engine','Human Approval','Audit Trail'].map((s,i)=><div key={s} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[.045] p-4"><CircleCheck className="text-emerald-300" size={18}/><span className="text-xs text-slate-200">{s}</span><span className="mr-auto rounded-full bg-emerald-400/10 px-2 py-1 text-[9px] text-emerald-300">{i===2?'WAIT':'PASS'}</span></div>)}</div>}
   </main>
  </div>
 </div>}

function AuthBridge(){useEffect(()=>{document.documentElement.classList.add('enjaz-auth-route');let host=document.querySelector('.enjaz-root');if(!host){host=document.createElement('div');host.className='enjaz-root';document.body.appendChild(host)}import('../auth-gate-v2.js').catch(error=>{console.error('[ENJAZ_AUTH_BOOT]',error)});return()=>{document.documentElement.classList.remove('enjaz-auth-route');host?.remove()};},[]);return null}

function App(){const [menuOpen,setMenuOpen]=useState(false);if(new URLSearchParams(window.location.search).has('auth'))return <AuthBridge/>;return <div className="overflow-hidden">
 <header className="sticky top-0 z-50 border-b border-emerald-950/10 bg-[#f7fbf9]/85 backdrop-blur-xl"><div className="mx-auto flex h-[76px] max-w-[1240px] items-center justify-between px-5"><a href="#" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#063d2d] text-white shadow-lg"><Command size={19}/></span><span><b className="block text-[18px]">إنجاز</b><small className="text-[8px] tracking-[.2em] text-emerald-700">ENJAZ</small></span></a><nav className="hidden items-center gap-7 text-[12px] font-medium text-slate-600 md:flex">{[['المنصة','#platform'],['القوى العاملة','#workforce'],['كيف تعمل','#how'],['القطاعات','#sectors'],['الحوكمة','#governance']].map(x=><a key={x[0]} href={x[1]} className="transition hover:text-emerald-700">{x[0]}</a>)}</nav><div className="flex items-center gap-2"><a href="/?auth=1" className="hidden px-3 py-2 text-xs text-slate-600 sm:block">تسجيل الدخول</a><a href="/?auth=1&signup=1" className="rounded-xl bg-[#087c58] px-4 py-2.5 text-[11px] font-semibold text-white shadow-lg shadow-emerald-900/10 transition duration-300 hover:-translate-y-0.5 hover:bg-[#096f50] hover:shadow-xl">ابدأ مع إنجاز</a><button type="button" aria-label="فتح القائمة" aria-expanded={menuOpen} onClick={()=>setMenuOpen(v=>!v)} className="grid h-10 w-10 place-items-center rounded-xl border border-emerald-900/10 md:hidden"><Menu size={18}/></button></div></div></header>

 <section className="relative overflow-hidden bg-[#f7fbf9]"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_75%_15%,rgba(13,168,117,.14),transparent_28%),radial-gradient(circle_at_15%_60%,rgba(31,104,80,.07),transparent_25%)]"/><div className="relative mx-auto max-w-[1240px] px-5 pb-16 pt-16 md:pb-24 md:pt-24"><div className="grid items-center gap-14 lg:grid-cols-[.78fr_1.22fr]"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-emerald-800/10 bg-white px-3 py-2 text-[9px] font-semibold tracking-[.15em] text-emerald-800 shadow-sm"><Zap size={12}/> INTELLIGENT OPERATING PLATFORM</div><h1 className="max-w-[650px] text-[clamp(42px,6vw,78px)] font-semibold leading-[1.03] tracking-[-2.8px] text-[#08251b]">قوة عمل رقمية.<br/><span className="bg-gradient-to-l from-[#087c58] via-[#16a36f] to-[#063d2d] bg-clip-text text-transparent">مؤسسة تتحرك بذكاء.</span></h1><p className="mt-6 max-w-[570px] text-[15px] leading-8 text-slate-600">إنجاز توحّد الموظفين الرقميين والعمليات وسير العمل والحوكمة في طبقة تشغيل واحدة — من النية إلى التنفيذ.</p><div className="mt-8 flex flex-wrap gap-3"><a href="/?auth=1&signup=1" className="group flex items-center gap-2 rounded-2xl bg-[#063d2d] px-5 py-3.5 text-xs font-semibold text-white shadow-xl shadow-emerald-950/15 transition duration-300 hover:-translate-y-0.5 hover:shadow-2xl">أنشئ مساحة مؤسستك<ArrowLeft size={16} className="transition group-hover:-translate-x-1"/></a><a href="#demo" className="flex items-center gap-2 rounded-2xl border border-emerald-900/10 bg-white px-5 py-3.5 text-xs font-semibold text-slate-700 shadow-sm transition duration-300 hover:-translate-y-0.5 hover:border-emerald-700/20 hover:shadow-lg"><Play size={15}/> شاهد العرض التوضيحي</a></div><div className="mt-7 flex flex-wrap gap-x-6 gap-y-2 text-[10px] text-slate-500"><span>✓ صلاحيات حسب الدور</span><span>✓ موافقات بشرية</span><span>✓ سجل تدقيق</span></div></div><div id="demo" className="relative">
      <div className="absolute -inset-8 rounded-[48px] bg-[radial-gradient(circle_at_50%_45%,rgba(21,183,126,.24),transparent_62%)] blur-2xl"/>
      <div className="relative">
        <div className="mb-3 flex items-center justify-between px-2 text-[9px] font-semibold tracking-[.18em] text-emerald-800/60">
          <span>ENJAZ OS / LIVE WORKSPACE</span><span>01 — 05</span>
        </div>
        <LiveConsole/>
        <div className="pointer-events-none absolute -bottom-7 -left-7 hidden w-48 rounded-2xl border border-emerald-900/10 bg-white p-4 shadow-2xl md:block">
          <div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full bg-emerald-500 shadow-[0_0_14px_rgba(16,185,129,.65)]"/><span className="text-[9px] font-semibold text-slate-600">WORKFLOW ACTIVE</span></div>
          <div className="mt-3 h-2 rounded-full bg-emerald-50"><div className="h-2 w-3/4 rounded-full bg-emerald-500"/></div>
          <div className="mt-2 flex justify-between text-[8px] text-slate-400"><span>Execution</span><span>75%</span></div>
        </div>
        <div className="pointer-events-none absolute -right-5 -top-5 hidden w-44 rounded-2xl border border-emerald-900/10 bg-[#063d2d] p-4 text-white shadow-2xl md:block">
          <span className="text-[8px] tracking-[.15em] text-emerald-300">DIGITAL WORKER</span>
          <b className="mt-2 block text-sm">AI Coordinator</b>
          <span className="mt-1 block text-[9px] text-white/45">Planning · Routing · Approval</span>
        </div>
      </div>
    </div></div></div></section>

 <section className="border-y border-emerald-950/5 bg-white shadow-[0_1px_0_rgba(6,61,45,.03)]"><div className="mx-auto max-w-[1240px] overflow-hidden px-5 py-5"><div className="flex w-max gap-2 animate-[marquee_28s_linear_infinite]">{[...tools,...tools].map((t,i)=><span key={i} className="rounded-full border border-emerald-900/10 bg-[#f7fbf9] px-4 py-2 text-[9px] font-medium text-slate-500">{t}</span>)}</div></div></section>

 <section id="platform" className="relative mx-auto max-w-[1240px] px-5 py-24 md:py-32"><div className="max-w-2xl"><span className="text-[10px] font-bold tracking-[.18em] text-emerald-700">THE PLATFORM</span><h2 className="mt-4 text-4xl font-semibold tracking-tight text-[#08251b] md:text-5xl">ليست مجموعة أدوات.<br/>إنها طبقة تشغيل.</h2><p className="mt-5 text-sm leading-7 text-slate-500">مشاهد صغيرة من المنصة توضّح كيف تعمل المكونات معًا بدل أن تظهر كبطاقات تسويقية جامدة.</p></div><div className="relative mt-12 grid gap-4 md:grid-cols-12">
 {[
  ['command','مركز قيادة المؤسسة','كل مهمة لها سياق ومسار وقرار واضح.','md:col-span-7 min-h-[330px]','bg-[#063d2d] text-white'],
  ['chat','Human × AI','محادثة مباشرة مع الموظف الرقمي قبل وأثناء العمل.','md:col-span-5 min-h-[330px]','bg-[#e5f3ec] text-[#08251b]'],
  ['auto','من الطلب إلى التنفيذ','هدف → خطة → موافقة → تنفيذ.','md:col-span-5 min-h-[290px]','bg-[#fff4dc] text-[#352814]'],
  ['guard','Governance Engine','السياسات والصلاحيات وسجل التدقيق داخل المسار.','md:col-span-7 min-h-[290px]','bg-[#eee8f8] text-[#33253e']
 ].map((c,i)=><article key={c[0]} className={`group relative overflow-hidden rounded-[28px] p-7 shadow-[0_18px_55px_rgba(9,55,40,.08)] transition duration-500 hover:-translate-y-1 hover:shadow-[0_24px_70px_rgba(9,55,40,.14)] ${c[3]} ${c[4]}`}><div className="relative z-10 max-w-[360px]"><span className="text-[9px] font-bold uppercase tracking-[.16em] opacity-60">{c[0]}</span><h3 className="mt-4 text-2xl font-semibold">{c[1]}</h3><p className="mt-2 text-xs leading-7 opacity-65">{c[2]}</p></div><div className="absolute bottom-[-60px] left-[-30px] h-44 w-44 rounded-full border border-current opacity-10 transition duration-700 group-hover:scale-125"/><div className="absolute right-8 bottom-8 grid h-28 w-28 place-items-center rounded-full border border-current/15 bg-white/10 text-[10px] opacity-80">{i===0?<Network size={30}/>:i===1?'LIVE':i===2?<Workflow size={30}/>:<ShieldCheck size={30}/>}</div></article>)}
 </div></section>

 <section id="workforce" className="bg-[#063d2d] text-white"><div className="mx-auto grid max-w-[1240px] gap-14 px-5 py-24 md:py-32 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><div><span className="text-[10px] font-bold tracking-[.18em] text-emerald-300">DIGITAL WORKFORCE</span><h2 className="mt-4 text-4xl font-semibold tracking-tight md:text-5xl">48 موظفًا رقميًا.<br/>فريق عمل واحد.</h2><p className="mt-6 max-w-xl text-sm leading-8 text-emerald-50/65">الموظف نفسه يعمل عبر القطاعات. التخصص يأتي من Industry Context + Skills + Knowledge + Tools + Policies + Permissions.</p><div className="mt-8 grid gap-2 sm:grid-cols-2">{roles.map(r=><div key={r[0]} className="rounded-2xl border border-white/10 bg-white/[.045] p-4"><b className="text-xs">{r[0]}</b><p className="mt-1 text-[10px] leading-5 text-white/50">{r[1]}</p></div>)}</div></div><div className="relative mx-auto aspect-square w-full max-w-[560px]"><div className="absolute inset-[14%] rounded-full border border-emerald-200/10 animate-[spin_24s_linear_infinite]"/><div className="absolute inset-[25%] rounded-full border border-emerald-200/15 animate-[spin_16s_linear_infinite_reverse]"/><div className="absolute inset-[37%] rounded-full bg-[radial-gradient(circle,#18b981,#063d2d_70%)] shadow-[0_0_100px_rgba(24,185,129,.2)]"/><div className="absolute inset-0 grid place-items-center"><div className="text-center"><b className="block text-6xl tracking-tight">48</b><span className="text-[10px] tracking-[.22em] text-emerald-200">DIGITAL WORKFORCE</span></div></div>{['AI','OPS','DATA','CX','FINANCE'].map((x,i)=><div key={x} className={`absolute grid h-14 w-14 place-items-center rounded-2xl border border-emerald-200/15 bg-white/10 text-[9px] text-emerald-100 backdrop-blur ${['left-[7%] top-[42%]','right-[8%] top-[22%]','right-[14%] bottom-[18%]','left-[18%] bottom-[13%]','left-[8%] top-[17%]'][i]}`}>{x}</div>)}</div></div></section>

 <section id="how" className="mx-auto max-w-[1240px] px-5 py-24 md:py-32"><div className="max-w-xl"><span className="text-[10px] font-bold tracking-[.18em] text-emerald-700">HOW ENJAZ WORKS</span><h2 className="mt-4 text-4xl font-semibold text-[#08251b] md:text-5xl">من النية إلى الإنجاز.</h2></div><div className="mt-12 grid gap-3 md:grid-cols-5">{[['01','حدّد الهدف'],['02','خطّط'],['03','وافق'],['04','نفّذ'],['05','تتبّع']].map(([n,t])=><div key={n} className="group rounded-[24px] border border-emerald-900/10 bg-white p-6 transition duration-300 hover:-translate-y-1 hover:border-emerald-700/20 hover:shadow-xl"><span className="text-[9px] text-emerald-700">{n}</span><div className="mt-12 flex items-center justify-between"><b className="text-sm">{t}</b><ChevronLeft size={15} className="text-emerald-600 transition group-hover:-translate-x-1"/></div></div>)}</div></section>

 <section id="sectors" className="border-y border-emerald-950/5 bg-[#eef6f2]"><div className="mx-auto max-w-[1240px] px-5 py-24 md:py-28"><span className="text-[10px] font-bold tracking-[.18em] text-emerald-700">INDUSTRY CONTEXT</span><h2 className="mt-4 text-4xl font-semibold text-[#08251b] md:text-5xl">تتكيّف إنجاز مع مؤسستك.</h2><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{sectors.map((s,i)=><div key={s} className="group relative min-h-[170px] overflow-hidden rounded-[25px] border border-emerald-900/10 bg-white p-5 shadow-sm"><span className="text-[9px] text-emerald-700">0{i+1}</span><h3 className="mt-14 text-lg font-semibold">{s}</h3><ArrowUpLeft className="absolute bottom-5 left-5 text-emerald-600 transition group-hover:-translate-y-1 group-hover:translate-x-1" size={18}/></div>)}</div></div></section>

 <section id="governance" className="mx-auto max-w-[1240px] px-5 py-24 md:py-32"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><span className="text-[10px] font-bold tracking-[.18em] text-emerald-700">OPERATIONS & GOVERNANCE</span><h2 className="mt-4 text-4xl font-semibold text-[#08251b] md:text-5xl">استقلالية محسوبة.<br/>وحوكمة مستمرة.</h2><p className="mt-5 text-sm leading-8 text-slate-500">كل موظف رقمي يعمل داخل سياق وصلاحيات وسياسات يمكن تتبعها.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{['Identity','Role & Goals','Skills & Tools','Knowledge','Model Strategy','Autonomy','Budget','Policies','Audit Trail'].map(x=><div key={x} className="rounded-2xl border border-emerald-900/10 bg-white p-5"><ShieldCheck size={17} className="text-emerald-700"/><b className="mt-7 block text-xs">{x}</b></div>)}</div></div></section>

 <section id="start" className="bg-[#087c58] text-white"><div className="mx-auto max-w-[1240px] px-5 py-20 text-center md:py-28"><Sparkles className="mx-auto mb-5 text-emerald-100" size={24}/><h2 className="text-4xl font-semibold tracking-tight md:text-6xl">ابدأ من مؤسستك.<br/>لا من واجهة وهمية.</h2><p className="mx-auto mt-5 max-w-xl text-sm leading-7 text-emerald-50/75">ابنِ طبقة تشغيل تجمع البشر والموظفين الرقميين والعمليات والحوكمة في مكان واحد.</p><a href="/login" className="mt-8 inline-flex items-center gap-2 rounded-2xl bg-white px-6 py-4 text-xs font-semibold text-[#063d2d] shadow-2xl">ابدأ مع إنجاز <ArrowLeft size={16}/></a></div></section>
 <footer className="bg-[#041c14] text-white"><div className="mx-auto flex max-w-[1240px] flex-col gap-5 px-5 py-8 text-[10px] text-white/45 sm:flex-row sm:items-center sm:justify-between"><span>© ENJAZ — Intelligent Operating Platform</span><div className="flex gap-5"><a href="#">الخصوصية</a><a href="#">الشروط</a><a href="/login">تسجيل الدخول</a></div></div></footer>
 <style>{`@keyframes marquee{to{transform:translateX(-50%)}}@media(prefers-reduced-motion:reduce){.animate-\\[marquee_28s_linear_infinite\\],.animate-\\[spin_24s_linear_infinite\\],.animate-\\[spin_16s_linear_infinite_reverse\\]{animation:none}}`}</style>
 </div>}
export default App;
