import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const cors=(o:string|null)=>({"Access-Control-Allow-Origin":o||"null","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Vary":"Origin","content-type":"application/json; charset=utf-8"});
const out=(x:unknown,s=200,o:string|null=null)=>new Response(JSON.stringify(x),{status:s,headers:{...cors(o),"x-content-type-options":"nosniff","x-frame-options":"DENY"}});
const now=()=>new Date().toISOString();
async function modelRun(goal:string,context:string){
 const openrouter=Deno.env.get("OPENROUTER_API_KEY"); const gemini=Deno.env.get("GEMINI_API_KEY"); const key=openrouter||gemini;
 if(!key)return {provider:"deterministic",output:{summary:`تم تنفيذ مهمة آمنة: ${goal}`,findings:["لم تُنفذ أي عملية خارجية."],nextSteps:["مراجعة النتيجة ثم متابعة الخطوة التالية."]}};
 const url=openrouter?"https://openrouter.ai/api/v1/chat/completions":"https://generativelanguage.googleapis.com/v1beta/openai/chat/completions";
 const body={model:Deno.env.get("ENJAZ_MODEL")||(openrouter?"openai/gpt-4o-mini":"gemini-2.5-flash"),messages:[{role:"system",content:"You are an enterprise digital employee. Execute only the stated low-risk task. Never claim external side effects. Return concise JSON with summary, findings, nextSteps."},{role:"user",content:`Goal: ${goal}\nContext: ${context}`}],temperature:0.2,response_format:{type:"json_object"}};
 const r=await fetch(url,{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify(body)}); if(!r.ok)throw new Error(`Model request failed: ${r.status}`); const j=await r.json(); const text=j.choices?.[0]?.message?.content||""; let output:any; try{output=JSON.parse(text)}catch{output={summary:text,findings:[],nextSteps:[]}} return {provider:openrouter?"openrouter":"gemini",output};
}
Deno.serve(async req=>{
 const origin=req.headers.get("Origin"); if(req.method==="OPTIONS")return new Response("ok",{headers:cors(origin)}); if(req.method!=="POST")return out({error:"Method not allowed"},405,origin);
 const base=Deno.env.get("SUPABASE_URL"),anon=Deno.env.get("SUPABASE_ANON_KEY"),service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"); if(!base||!anon||!service)return out({error:"Production worker is not configured"},503,origin);
 const auth=createClient(base,anon,{global:{headers:{Authorization:req.headers.get("Authorization")||""}}}),db=createClient(base,service); const {data:{user}}=await auth.auth.getUser(); if(!user)return out({error:"Authentication required"},401,origin);
 const {data:profile}=await db.from("users").select("id").eq("auth_user_id",user.id).maybeSingle(); if(!profile)return out({error:"Profile not found"},403,origin);
 const body=await req.json().catch(()=>({})); const workspaceId=String(body.workspaceId||""); if(!workspaceId)return out({error:"workspaceId is required"},400,origin);
 const {data:member}=await db.from("workspace_members").select("role").eq("workspace_id",workspaceId).eq("user_id",profile.id).maybeSingle(); if(!member||!["owner","admin","manager"].includes(member.role))return out({error:"Manager permission required"},403,origin);
 const limit=Math.min(Math.max(Number(body.limit||5),1),10); const {data:jobs,error}=await db.from("job_queue").select("*").eq("workspace_id",workspaceId).eq("status","queued").lte("available_at",now()).order("created_at",{ascending:true}).limit(limit); if(error)return out({error:error.message},400,origin);
 const results=[];
 for(const job of jobs||[]){const workerId=`edge-worker-${crypto.randomUUID()}`,attempt=(job.attempts||0)+1; await db.from("job_queue").update({status:"running",attempts:attempt,locked_at:now(),locked_by:workerId,updated_at:now()}).eq("id",job.id).eq("status","queued"); await db.from("job_attempts").insert({job_id:job.id,worker_id:workerId,attempt,status:"started"}); try{const p=job.payload||{},taskId=p.taskId; const {data:task}=taskId?await db.from("tasks").select("*").eq("workspace_id",workspaceId).eq("id",taskId).maybeSingle():{data:null}; const {data:emp}=p.employeeId?await db.from("ai_employees").select("*").eq("workspace_id",workspaceId).eq("id",p.employeeId).maybeSingle():{data:null}; const goal=String(p.goal||task?.objective||emp?.goal||job.job_type||"تنفيذ المهمة"),context=JSON.stringify({input:task?.input||p.input||{},skills:emp?.skills||[],tools:emp?.tools||[]}),started=Date.now(),result=await modelRun(goal,context),latency=Date.now()-started; if(task)await db.from("tasks").update({status:"completed",output:{...result.output,provider:result.provider,externalSideEffect:false},started_at:task.started_at||now(),completed_at:now()}).eq("id",task.id).eq("workspace_id",workspaceId); await db.from("job_queue").update({status:"succeeded",result:result.output,last_error:null,updated_at:now(),locked_at:null,locked_by:null}).eq("id",job.id); await db.from("job_attempts").update({status:"succeeded",finished_at:now()}).eq("job_id",job.id).eq("attempt",attempt); await db.from("runtime_metrics").insert({workspace_id:workspaceId,employee_id:emp?.id||null,task_id:task?.id||null,provider:result.provider,status:"succeeded",latency_ms:latency,cost_cents:result.provider==="deterministic"?0:1}); await db.from("audit_events").insert({workspace_id:workspaceId,task_id:task?.id||null,employee_id:emp?.id||null,event_type:"execution",actor_type:"digital_employee",action:"worker.execute",metadata:{jobId:job.id,provider:result.provider,externalSideEffect:false}}); results.push({jobId:job.id,status:"succeeded",provider:result.provider});}catch(e){const message=e instanceof Error?e.message:"Worker execution failed",terminal=attempt>=(job.max_attempts||3); await db.from("job_queue").update({status:terminal?"dead":"queued",last_error:message,updated_at:now(),locked_at:null,locked_by:null}).eq("id",job.id); await db.from("job_attempts").update({status:"failed",error:message,finished_at:now()}).eq("job_id",job.id).eq("attempt",attempt); results.push({jobId:job.id,status:terminal?"dead":"retrying",error:message});}}
 return out({data:{processed:results.length,results}},200,origin);
});
