import React from 'react';
import {ArrowLeft,ArrowRight, Bot, Check, Command, Database, GitBranch, Globe2, LockKeyhole, Play, ShieldCheck, Sparkles, Workflow, Zap} from 'lucide-react';
import EnterpriseMarquee from '../ui/EnterpriseMarquee';
import SpotlightCard from '../ui/SpotlightCard';

const roles=[['AI Manager','الأهداف والقرارات'],['AI Analyst','البيانات والرؤى'],['AI Operations Worker','التنفيذ التشغيلي'],['AI Coordinator','التنسيق والتوجيه'],['AI Customer Service Worker','خدمة العملاء'],['AI Automation Worker','الأتمتة والتكامل']];
const sectors=[['المطاعم','الطلبات · الفروع · المخزون · الجودة'],['المستشفيات','العمليات · الخدمات · الموافقات · التنسيق'],['الفنادق','الضيافة · التشغيل · الطلبات · الأقسام'],['الشركات','المبيعات · المالية · العمليات · التقنية'],['الجهات الحكومية','الخدمات · الإجراءات · الامتثال · التدقيق']];
const tabs=['مركز القيادة','القوى العاملة','سير العمل','الحوكمة'];

function ProductWindow(){
 const [tab,setTab]=React.useState(0);
 return <div className="relative mx-auto max-w-[1120px]">
  <div className="absolute -inset-16 rounded-[80px] bg-emerald-400/15 blur-3xl"/>
  <div className="relative overflow-hidden rounded-[32px] border border-[#cfe1d9] bg-white shadow-[0_50px_140px_rgba(2,45,32,.18)]">
   <div className="flex items-center justify-between border-b border-[#e6eee9] bg-[#fbfdfc] px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#063d2d] text-emerald-200"><Command size={16}/></span><div><b className="block text-xs">ENJAZ OS</b><span className="text-[8px] text-slate-400">Intelligent Operating Platform</span></div></div><span className="rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1 text-[9px] font-bold tracking-widest text-emerald-700">PREVIEW</span></div>
   <div className="grid md:grid-cols-[210px_1fr]">
    <aside className="hidden bg-[#052b20] p-4 md:block"><div className="mb-7 px-3 pt-2 text-[8px] tracking-[.18em] text-emerald-300">WORKSPACE</div>{tabs.map((x,i)=><button key={x} onClick={()=>setTab(i)} className={`mb-1 w-full rounded-xl px-3 py-3 text-right text-[10px] transition ${tab===i?'bg-emerald-400/15 text-emerald-200':'text-white/40 hover:bg-white/5 hover:text-white'}`}>{x}</button>)}</aside>
    <main className="min-h-[470px] bg-[#f8fbfa] p-5 md:p-9"><div className="mb-5 flex gap-2 overflow-auto md:hidden">{tabs.map((x,i)=><button key={x} onClick={()=>setTab(i)} className={`shrink-0 rounded-xl px-3 py-2 text-[9px] ${tab===i?'bg-[#063d2d] text-white':'bg-white text-slate-500'}`}>{x}</button>)}</div><span className="text-[8px] font-bold tracking-[.2em] text-emerald-700">INTELLIGENT OPERATING PLATFORM</span><h3 className="mt-2 text-2xl font-semibold tracking-tight">{tabs[tab]}</h3>
    {tab===0&&<div className="mt-8 grid gap-3 sm:grid-cols-3">{[['CONTEXT','Operational request'],['DECISION','AI Coordinator'],['CONTROL','Human approval']].map((x,i)=><SpotlightCard key={x[0]} className="rounded-2xl border border-[#dce9e4] bg-white p-5 shadow-sm"><span className="text-[7px] font-bold tracking-widest text-slate-400">{x[0]}</span><b className="mt-4 block text-[11px]">{x[1]}</b><span className="mt-3 block text-[8px] text-emerald-700">{i===2?'CHECKPOINT':'READY'}</span></SpotlightCard>)}</div>}
    {tab===1&&<div className="mt-8 grid gap-3 sm:grid-cols-2">{roles.slice(0,4).map(x=><SpotlightCard key={x[0]} className="rounded-2xl border border-[#dce9e4] bg-white p-5"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#063d2d] text-emerald-200"><Bot size={14}/></span><b className="mt-5 block text-[10px]">{x[0]}</b><span className="mt-1 block text-[9px] text-slate-400">{x[1]}</span></SpotlightCard>)}</div>}
    {tab===2&&<div className="mt-9"><div className="grid grid-cols-4 gap-2">{['Signal','Context','Decision','Action'].map((x,i)=><div key={x} className="text-center"><span className={`mx-auto grid h-12 w-12 place-items-center rounded-2xl border ${i<3?'border-emerald-200 bg-emerald-50 text-emerald-700':'border-[#dce9e4] bg-white text-slate-400'}`}>{i<3?<Check size={16}/>:<Play size={14}/>}</span><b className="mt-3 block text-[8px] text-slate-500">{x}</b></div>)}</div><div className="mt-8 rounded-2xl border border-emerald-100 bg-emerald-50 p-5"><span className="text-[8px] font-bold tracking-widest text-emerald-700">OPERATING TRACE</span><p className="mt-2 text-[10px] leading-6 text-[#31584b]">من الإشارة إلى القرار والتنفيذ، كل مرحلة لها سياق واضح ونقطة تحكم.</p></div></div>}
    {tab===3&&<div className="mt-7 grid gap-3">{['Identity & Permissions','Policies','Human Approval','Audit Trail'].map((x,i)=><div key={x} className="flex items-center gap-3 rounded-2xl border border-[#dce9e4] bg-white p-4"><ShieldCheck size={16} className="text-emerald-700"/><b className="text-[10px]">{x}</b><span className="mr-auto rounded-full bg-emerald-50 px-2 py-1 text-[7px] text-emerald-700">{i===2?'REVIEW':'PASS'}</span></div>)}</div>}
    </main>
   </div>
  </div>
 </div>
}

export default function ReadyEnterpriseLanding(){
 return <div dir="rtl" className="min-h-screen overflow-hidden bg-[#f8fbf9] text-[#08251b]">
  <header className="sticky top-0 z-50 border-b border-emerald-950/10 bg-white/80 backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-[1320px] items-center justify-between px-5"><a href="#" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-[13px] bg-[#063d2d] text-emerald-200"><Command size={18}/></span><span><b className="block text-[17px]">إنجاز</b><small className="text-[7px] tracking-[.2em] text-slate-400">INTELLIGENT OPERATING PLATFORM</small></span></a><nav className="hidden items-center gap-8 text-[11px] text-slate-500 lg:flex"><a href="#platform">المنصة</a><a href="#workforce">القوى العاملة</a><a href="#how">كيف تعمل</a><a href="#sectors">القطاعات</a><a href="#governance">الحوكمة</a></nav><div className="flex items-center gap-2"><a href="/?auth=1" className="hidden px-4 py-2 text-[10px] text-slate-500 sm:block">تسجيل الدخول</a><a href="/?auth=1&signup=1" className="rounded-xl bg-[#078a61] px-4 py-3 text-[10px] font-bold text-white shadow-lg shadow-emerald-900/10">ابدأ الآن</a></div></div></header>
  <main>
   <section className="relative overflow-hidden px-5 pb-28 pt-20 md:pb-36 md:pt-28"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_70%_15%,rgba(20,184,130,.12),transparent_30%),linear-gradient(rgba(7,138,97,.035)_1px,transparent_1px),linear-gradient(90deg,rgba(7,138,97,.035)_1px,transparent_1px)] bg-[size:auto,56px_56px,56px_56px]"/><div className="mx-auto max-w-[1320px]"><div className="mx-auto max-w-5xl text-center"><span className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-white px-4 py-2 text-[9px] font-bold tracking-[.16em] text-emerald-700 shadow-sm"><Sparkles size={11}/> THE INTELLIGENT OPERATING PLATFORM</span><h1 className="mt-7 text-5xl font-semibold tracking-[-.06em] md:text-7xl lg:text-[82px]">قوة عمل رقمية.<br/><span className="text-emerald-700">مؤسسة تتحرك بذكاء.</span></h1><p className="mx-auto mt-7 max-w-2xl text-sm leading-8 text-slate-500 md:text-base">إنجاز تجمع الموظفين الرقميين والعمليات وسير العمل والحوكمة في طبقة تشغيل واحدة — من الطلب إلى القرار، ثم التنفيذ، ثم الأثر القابل للتدقيق.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><a href="/?auth=1&signup=1" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-[#078a61] px-7 py-4 text-xs font-bold text-white shadow-xl shadow-emerald-900/15">ابدأ مع إنجاز <ArrowLeft size={15}/></a><a href="#demo" className="inline-flex items-center justify-center gap-2 rounded-2xl border border-[#cfe2da] bg-white px-7 py-4 text-xs font-bold text-[#173a2e] shadow-sm"><Play size={14}/> شاهد المنتج</a></div></div><div id="demo" className="mt-16"><ProductWindow/></div><div className="mx-auto mt-14 max-w-[1120px] overflow-hidden rounded-2xl border border-[#dce9e4] bg-white shadow-sm"><EnterpriseMarquee duration={26}>{['OpenAI','GitHub','Vercel','Supabase','n8n','MCP','OpenAPI','PostgreSQL'].map(x=><div key={x} className="flex h-16 min-w-[150px] items-center gap-3 border-l border-[#e6efeb] px-6"><span className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Zap size={14}/></span><b className="text-[10px]">{x}</b></div>)}</EnterpriseMarquee></div></div></section>
   <section id="platform" className="border-y border-[#dce9e4] bg-white px-5 py-24 md:py-32"><div className="mx-auto max-w-[1320px]"><div className="max-w-3xl"><span className="text-[9px] font-bold tracking-[.18em] text-emerald-700">ENJAZ PLATFORM</span><h2 className="mt-5 text-4xl font-semibold tracking-tight md:text-6xl">كل ما تحتاجه المؤسسة.<br/><span className="text-emerald-700">في طبقة تشغيل واحدة.</span></h2></div><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{[['Command Center','مركز قيادة موحّد للأهداف والطلبات والقرارات',Command],['Digital Workforce','48 دورًا رقميًا عالميًا ضمن سياق المؤسسة',Bot],['Workflow Engine','مسارات قابلة للتنفيذ والمراجعة',Workflow],['Knowledge Layer','المعرفة والسياسات داخل مسار العمل',Database],['Integration Fabric','الأدوات والأنظمة متصلة بالعمل',GitBranch],['Governance Plane','صلاحيات وموافقات وأثر تدقيقي',ShieldCheck]].map(([t,d,I])=>{const Icon=I;return <SpotlightCard key={t as string} className="group relative overflow-hidden rounded-[28px] border border-[#dce9e4] bg-[#fbfdfc] p-7 transition hover:-translate-y-1 hover:shadow-2xl"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-emerald-50 text-emerald-700"><Icon size={19}/></span><h3 className="mt-8 text-xl font-semibold">{t as string}</h3><p className="mt-3 text-[11px] leading-6 text-slate-400">{d as string}</p><ArrowLeft className="absolute left-6 top-6 text-slate-200 transition group-hover:text-emerald-600" size={17}/></SpotlightCard>})}</div></div></section>
   <section id="workforce" className="bg-[#052b20] px-5 py-24 text-white md:py-32"><div className="mx-auto grid max-w-[1320px] gap-16 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><span className="text-[9px] font-bold tracking-[.18em] text-emerald-300">DIGITAL WORKFORCE</span><h2 className="mt-5 text-4xl font-semibold md:text-6xl">48 دورًا عالميًا.<br/><span className="text-emerald-300">تخصص بلا نسخ.</span></h2><p className="mt-6 max-w-lg text-sm leading-8 text-white/50">الموظف الرقمي نفسه يعمل عبر القطاعات. التخصص يأتي من سياق الصناعة والمهارات والمعرفة والأدوات والسياسات والصلاحيات.</p><div className="mt-8 grid grid-cols-2 gap-3">{roles.map(x=><SpotlightCard key={x[0]} className="rounded-2xl border border-white/10 bg-white/[.045] p-4 text-white"><span className="text-[7px] tracking-widest text-emerald-300">DIGITAL ROLE</span><b className="mt-4 block text-[10px]">{x[0]}</b><span className="mt-1 block text-[8px] text-white/35">{x[1]}</span></SpotlightCard>)}</div></div><div className="relative mx-auto aspect-square w-full max-w-[520px]"><div className="absolute inset-[5%] rounded-full border border-emerald-200/10 [transform:rotateX(65deg)_rotateZ(-15deg)]"/><div className="absolute inset-[18%] rounded-full border border-emerald-200/15 [transform:rotateX(65deg)_rotateZ(20deg)]"/><div className="absolute inset-[30%] rounded-full bg-[radial-gradient(circle_at_35%_25%,#35d8a0,#063d2d_70%)] shadow-[0_0_120px_rgba(25,185,128,.28)]"/><div className="absolute inset-0 grid place-items-center text-center"><div><b className="block text-7xl">48</b><span className="text-[8px] tracking-[.25em] text-emerald-200">GLOBAL DIGITAL ROLES</span></div></div></div></div></section>
   <section id="how" className="px-5 py-24 md:py-32"><div className="mx-auto max-w-[1320px]"><span className="text-[9px] font-bold tracking-[.18em] text-emerald-700">HOW ENJAZ WORKS</span><h2 className="mt-5 text-4xl font-semibold md:text-6xl">من الإشارة إلى الأثر.<br/>بدون فقدان السيطرة.</h2><div className="mt-14 grid overflow-hidden rounded-[30px] border border-[#dce9e4] bg-white shadow-xl md:grid-cols-5">{[['01','Signal','الطلب أو الحدث'],['02','Context','السياق والمعرفة'],['03','Decision','القرار والخطة'],['04','Action','التنفيذ المنضبط'],['05','Evidence','الأثر والتدقيق']].map((x,i)=><div key={x[0]} className="relative border-b border-[#dce9e4] p-7 md:border-b-0 md:border-l"><span className="text-[9px] font-bold tracking-widest text-emerald-700">{x[0]}</span><h3 className="mt-12 text-lg font-semibold">{x[1]}</h3><p className="mt-2 text-[9px] text-slate-400">{x[2]}</p>{i<4&&<ArrowRight className="absolute left-4 top-1/2 hidden text-emerald-300 md:block" size={15}/>}</div>)}</div></div></section>
   <section id="sectors" className="border-y border-[#dce9e4] bg-[#f1f7f4] px-5 py-24 md:py-32"><div className="mx-auto max-w-[1320px]"><span className="text-[9px] font-bold tracking-[.18em] text-emerald-700">CROSS-INDUSTRY</span><h2 className="mt-5 text-4xl font-semibold md:text-6xl">نفس القوة.<br/><span className="text-emerald-700">سياق مختلف.</span></h2><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-5">{sectors.map(x=><SpotlightCard key={x[0]} className="group rounded-[26px] border border-[#d7e6df] bg-white p-6 transition hover:-translate-y-1 hover:shadow-xl"><span className="text-[8px] font-bold tracking-widest text-emerald-700">ENJAZ</span><h3 className="mt-16 text-xl font-semibold">{x[0]}</h3><p className="mt-2 text-[9px] leading-5 text-slate-400">{x[1]}</p><ArrowLeft className="mt-7 text-slate-200 group-hover:text-emerald-600" size={16}/></SpotlightCard>)}</div></div></section>
   <section id="governance" className="bg-white px-5 py-24 md:py-32"><div className="mx-auto max-w-[1320px]"><span className="text-[9px] font-bold tracking-[.18em] text-emerald-700">OPERATIONS & GOVERNANCE</span><h2 className="mt-5 text-4xl font-semibold md:text-6xl">الاستقلالية<br/><span className="text-emerald-700">داخل حدودك.</span></h2><div className="mt-12 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{['Identity','Permissions','Policies','Human Approval','Audit Trail'].map((x,i)=><div key={x} className="rounded-2xl border border-[#dce9e4] bg-[#f8fbfa] p-5"><LockKeyhole size={16} className="text-emerald-700"/><b className="mt-8 block text-[10px]">{x}</b><span className="mt-2 block text-[7px] text-slate-400">CONTROL 0{i+1}</span></div>)}</div></div></section>
   <section className="px-5 py-20"><div className="mx-auto max-w-[1320px] overflow-hidden rounded-[36px] bg-[#063d2d] px-6 py-20 text-center text-white shadow-2xl md:py-28"><Globe2 className="mx-auto text-emerald-300" size={24}/><h2 className="mt-6 text-4xl font-semibold md:text-6xl">اجعل العمل يتحرك.<br/><span className="text-emerald-300">واجعل القرار واضحًا.</span></h2><p className="mx-auto mt-5 max-w-xl text-sm leading-7 text-white/45">ابدأ من طبقة التشغيل، ثم وسّع القوة العاملة والعمليات والتكاملات وفق سياق مؤسستك.</p><a href="/?auth=1&signup=1" className="mt-8 inline-flex items-center gap-2 rounded-2xl bg-white px-7 py-4 text-xs font-bold text-[#063d2d]">ابدأ مع إنجاز <ArrowLeft size={15}/></a></div></section>
  </main>
  <footer className="border-t border-white/10 bg-[#041c14] px-5 py-12 text-white"><div className="mx-auto flex max-w-[1320px] flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-500 text-[#063d2d]"><Command size={16}/></span><b>إنجاز</b></div><span className="text-[9px] text-white/30">© ENJAZ — Intelligent Operating Platform</span></div></footer>
 </div>
}