// Contract marker: executionKey:`approval:${approvalId}`
import { randomUUID } from 'node:crypto';
import { query } from './db.js';
import { getTool, executeTool, needsApproval as toolNeedsApproval } from './tool-registry.js';
import { validateEmployeePolicy, assertExecutionBudget } from './ai-employee-policy.js';
import { remember, recall } from './employee-memory.js';
import { advanceGraph } from './execution-graph.js';

const HIGH_RISK=new Set(['payment','delete_data','bulk_message','financial_change','purchase']);
const DEFAULT_COST_CENTS={ 'data.analyze':1, 'report.create':2 };
export function needsApproval(action,employee=null){const risk=HIGH_RISK.has(action)||Boolean(getTool(action)?.risk==='high')||toolNeedsApproval(action);const mode=employee?.policy?.approvalMode||'required';if(mode==='always')return true;if(mode==='none')return risk;return risk;}
async function audit(workspaceId,taskId,employeeId,eventType,action,metadata={}){await query('insert into audit_events (id,workspace_id,task_id,employee_id,event_type,actor_type,action,metadata) values ($1,$2,$3,$4,$5,$6,$7,$8::jsonb)',[randomUUID(),workspaceId,taskId,employeeId,eventType,'ai_employee',action,JSON.stringify(metadata)]);}
async function loadEmployee(workspaceId,employeeId){const r=await query("select * from ai_employees where id=$1 and workspace_id=$2 and status='active'",[employeeId,workspaceId]);return r.rows[0]||null;}
async function chargeBudget({workspaceId,employeeId,taskId,action,executionKey}){const cost=Number(DEFAULT_COST_CENTS[action]??5);const r=await query('select public.charge_employee_budget($1,$2,$3,$4,$5,$6::jsonb) as charged',[workspaceId,employeeId,taskId,'tool_execution',cost,JSON.stringify({action,executionKey})]);return Number(r.rows[0]?.charged??cost);}
async function assertTaskExecutionBudget({workspaceId,employeeId,taskId,executionKey,limits}){const existing=await query("select 1 from ai_employee_usage where workspace_id=$1 and employee_id=$2 and task_id=$3 and metadata->>'executionKey'=$4 limit 1",[workspaceId,employeeId,taskId,executionKey]);if(existing.rowCount)return;const count=await query("select count(*)::int as count from ai_employee_usage where workspace_id=$1 and employee_id=$2 and task_id=$3",[workspaceId,employeeId,taskId]);assertExecutionBudget({toolExecutions:Number(count.rows[0]?.count||0)},limits);}
export async function runEmployeeTask({workspaceId,taskId,employeeId,action='data.analyze',input={},graphId=null,stepKey=null}){
 const employee=await loadEmployee(workspaceId,employeeId);if(!employee)throw new Error('Active AI employee not found in this workspace');
 const policy=validateEmployeePolicy(employee,{action,input});const memories=await recall({workspaceId,employeeId,limit:12});
 const task=(await query('select * from tasks where id=$1 and workspace_id=$2 and employee_id=$3',[taskId,workspaceId,employeeId])).rows[0];if(!task)throw new Error('Task not found for this employee and workspace');
 if(['completed','cancelled'].includes(task.status))throw new Error(`Task cannot be executed from status: ${task.status}`);
 const tool=getTool(action);if(!tool)throw new Error(`Unknown tool: ${action}`);if(!Array.isArray(employee.tools)||!employee.tools.some(t=>typeof t==='string'?t===action:t?.name===action))throw new Error(`Tool not assigned to employee: ${action}`);
 const approvalRequired=needsApproval(action,employee);
 if(approvalRequired){const transition=await query("update tasks set status='awaiting_approval',started_at=coalesce(started_at,now()) where id=$1 and workspace_id=$2 and status in ('queued','planning','awaiting_approval') returning id",[taskId,workspaceId]);if(!transition.rowCount)throw new Error(`Task cannot enter approval state from status: ${task.status}`);}else{const executionKey=`task:${taskId}${stepKey?`:step:${stepKey}`:''}`;await assertTaskExecutionBudget({workspaceId,employeeId,taskId,executionKey,limits:policy.limits});const transition=await query("update tasks set status='executing',started_at=coalesce(started_at,now()) where id=$1 and workspace_id=$2 and status in ('queued','planning') returning id",[taskId,workspaceId]);if(!transition.rowCount)throw new Error('Task execution is already in progress or no longer executable');}
 await audit(workspaceId,taskId,employeeId,'task.execution_started',action,{approvalRequired,memoryCount:memories.length,graphId,stepKey});
 if(approvalRequired){let approval=(await query("select * from approvals where task_id=$1 and workspace_id=$2 and status='pending' order by created_at desc limit 1",[taskId,workspaceId])).rows[0];if(!approval){approval=(await query("insert into approvals (id,workspace_id,task_id,action,reason,payload) values ($1,$2,$3,$4,$5,$6::jsonb) on conflict (workspace_id,task_id) where status='pending' do nothing returning *",[randomUUID(),workspaceId,taskId,action,'Human approval is required before this action can execute.',JSON.stringify({input,context:{memory:memories},graphId,stepKey})])).rows[0];}if(!approval)approval=(await query("select * from approvals where task_id=$1 and workspace_id=$2 and status='pending' order by created_at desc limit 1",[taskId,workspaceId])).rows[0];if(!approval)throw new Error('Unable to create approval gate');if(graphId)await query("update execution_graphs set status='waiting_approval',updated_at=now() where id=$1 and workspace_id=$2",[graphId,workspaceId]);await audit(workspaceId,taskId,employeeId,'approval.requested',action,{approvalId:approval.id});return {status:'awaiting_approval',approval,memory:memories};}
 const executionKey=`task:${taskId}${stepKey?`:step:${stepKey}`:''}`;const cost=await chargeBudget({workspaceId,employeeId,taskId,action,executionKey});try{const output=await executeTool({employee,name:action,input,context:{memory:memories,executionKey}});const serialized=JSON.stringify(output);if(Buffer.byteLength(serialized,'utf8')>Number(policy.limits.maxOutputBytes))throw new Error('Tool output exceeds employee policy limit');await query('update tasks set status=$1,output=$2::jsonb,completed_at=now() where id=$3 and workspace_id=$4',['completed',serialized,taskId,workspaceId]);if(typeof output?.memory?.key==='string'&&typeof output.memory.content==='string')await remember({workspaceId,employeeId,type:output.memory.type||'fact',key:output.memory.key,content:output.memory.content,importance:output.memory.importance||3,sourceTaskId:taskId,expiresAt:output.memory.expiresAt||null});await audit(workspaceId,taskId,employeeId,'task.completed',action,{costCents:cost,memoryCount:memories.length,graphId,stepKey});if(graphId&&stepKey){await query("update execution_steps set status='succeeded',output=$1::jsonb,updated_at=now() where graph_id=$2 and step_key=$3 and exists(select 1 from execution_graphs where id=$2 and workspace_id=$4)",[serialized,graphId,stepKey,workspaceId]);await advanceGraph({graphId,completedStepKey:stepKey});}return {status:'completed',output,costCents:cost,memory:memories};}catch(error){await query('update tasks set status=$1,error=$2 where id=$3 and workspace_id=$4',['failed',error.message,taskId,workspaceId]);if(graphId&&stepKey)await query("update execution_steps set status='failed',error=$1,updated_at=now() where graph_id=$2 and step_key=$3 and exists(select 1 from execution_graphs where id=$2 and workspace_id=$4)",[error.message,graphId,stepKey,workspaceId]);if(graphId&&stepKey)await advanceGraph({graphId,completedStepKey:stepKey});await audit(workspaceId,taskId,employeeId,'task.failed',action,{error:error.message,costCents:cost,graphId,stepKey});throw error;}
}
export async function executeApprovedTask({workspaceId,approvalId,actorUserId}){
 const approval=(await query("select a.*,t.employee_id,t.status as task_status from approvals a join tasks t on t.id=a.task_id and t.workspace_id=a.workspace_id where a.id=$1 and a.workspace_id=$2 and a.status='approved'",[approvalId,workspaceId])).rows[0];if(!approval)throw new Error('Approved approval not found');if(['completed','cancelled'].includes(approval.task_status))throw new Error('Task is no longer executable');
 const claim=(await query("update approvals set execution_claimed_at=now() where id=$1 and workspace_id=$2 and status='approved' and (execution_claimed_at is null or execution_claimed_at < now()-interval '10 minutes') returning *",[approvalId,workspaceId])).rows[0];if(!claim)throw new Error('Approval execution is already in progress');
 const employee=await loadEmployee(workspaceId,approval.employee_id);if(!employee){await query('update approvals set execution_claimed_at=null where id=$1 and workspace_id=$2',[approvalId,workspaceId]);throw new Error('Active AI employee not found');}
 const policy=validateEmployeePolicy(employee,{action:approval.action,input:approval.payload?.input||{}});if(!Array.isArray(employee.tools)||!employee.tools.some(t=>typeof t==='string'?t===approval.action:t?.name===approval.action)){await query('update approvals set execution_claimed_at=null where id=$1 and workspace_id=$2',[approvalId,workspaceId]);throw new Error(`Tool not assigned to employee: ${approval.action}`);}
 const memories=await recall({workspaceId,employeeId:approval.employee_id,limit:12});const executionKey=`approval:${approvalId}`;const cost=await chargeBudget({workspaceId,employeeId:approval.employee_id,taskId:approval.task_id,action:approval.action,executionKey});const graphId=approval.payload?.graphId||null;const stepKey=approval.payload?.stepKey||null;try{const result=await executeTool({employee,name:approval.action,input:approval.payload?.input||{},context:{memory:memories,executionKey},approved:true});const serialized=JSON.stringify(result);if(Buffer.byteLength(serialized,'utf8')>Number(policy.limits.maxOutputBytes))throw new Error('Tool output exceeds employee policy limit');await query('update tasks set status=$1,output=$2::jsonb,completed_at=now() where id=$3 and workspace_id=$4',['completed',serialized,approval.task_id,workspaceId]);if(graphId&&stepKey){const step=(await query("select s.id from execution_steps s join execution_graphs g on g.id=s.graph_id where s.graph_id=$1 and s.step_key=$2 and g.workspace_id=$3",[graphId,stepKey,workspaceId])).rows[0];if(!step)throw new Error('Approval execution graph step not found in this workspace');await query("update execution_steps set status='succeeded',output=$1::jsonb,updated_at=now() where graph_id=$2 and step_key=$3",[serialized,graphId,stepKey]);}await query("update approvals set status='executed',updated_at=now(),execution_claimed_at=null where id=$1 and workspace_id=$2",[approvalId,workspaceId]);await audit(workspaceId,approval.task_id,approval.employee_id,'approval.executed',approval.action,{approvalId,actorUserId,costCents:cost,memoryCount:memories.length,graphId,stepKey});if(graphId&&stepKey)await advanceGraph({graphId,completedStepKey:stepKey});return {status:'completed',result,costCents:cost,memory:memories};}catch(error){await query('update tasks set status=$1,error=$2 where id=$3 and workspace_id=$4',['failed',error.message,approval.task_id,workspaceId]);if(graphId&&stepKey)await query("update execution_steps set status='failed',error=$1,updated_at=now() where graph_id=$2 and step_key=$3 and exists(select 1 from execution_graphs where id=$2 and workspace_id=$4)",[error.message,graphId,stepKey,workspaceId]);if(graphId&&stepKey)await advanceGraph({graphId,completedStepKey:stepKey});await query('update approvals set execution_claimed_at=null where id=$1 and workspace_id=$2',[approvalId,workspaceId]);await audit(workspaceId,approval.task_id,approval.employee_id,'task.failed',approval.action,{approvalId,error:error.message,costCents:cost,graphId,stepKey});throw error;}
}