import { randomUUID, createDecipheriv } from 'node:crypto';
import { query, withTransaction } from './db.js';
const masterKey=()=>process.env.ENJAZ_CREDENTIALS_KEY;
function key(){const value=masterKey();if(!value)throw new Error('ENJAZ_CREDENTIALS_KEY is not configured');const k=Buffer.from(value,'base64');if(k.length!==32)throw new Error('ENJAZ_CREDENTIALS_KEY must decode to 32 bytes');return k;}
function validatePublicMetadata(value,label){if(!value||typeof value!=='object'||Array.isArray(value))throw new Error(`${label} must be an object`);const forbidden=/(password|secret|token|api[_-]?key|credential|authorization|private[_-]?key)/i;const scan=(node,path='')=>{if(!node||typeof node!=='object')return;if(Array.isArray(node)){node.forEach((v,i)=>scan(v,`${path}[${i}]`));return;}for(const [k,v] of Object.entries(node)){if(forbidden.test(k))throw new Error(`${label} contains a secret-like field: ${path?`${path}.`:''}${k}`);scan(v,path?`${path}.${k}`:k);}};scan(value);}
export async function encryptCredentials(credentials){const k=key();const iv=globalThis.crypto.getRandomValues(new Uint8Array(12));const plaintext=new TextEncoder().encode(JSON.stringify(credentials));const cryptoKey=await globalThis.crypto.subtle.importKey('raw',k,'AES-GCM',false,['encrypt']);const encrypted=await globalThis.crypto.subtle.encrypt({name:'AES-GCM',iv},cryptoKey,plaintext);return JSON.stringify({v:1,iv:Buffer.from(iv).toString('base64'),data:Buffer.from(encrypted).toString('base64')});}
export async function decryptCredentials(encrypted){const parsed=typeof encrypted==='string'?JSON.parse(encrypted):encrypted;if(parsed?.v!==1)throw new Error('Unsupported credential format');const k=key();const iv=Buffer.from(parsed.iv,'base64');const data=Buffer.from(parsed.data,'base64');const decipher=createDecipheriv('aes-256-gcm',k,iv);decipher.setAuthTag(data.subarray(data.length-16));const plaintext=Buffer.concat([decipher.update(data.subarray(0,data.length-16)),decipher.final()]);return JSON.parse(plaintext.toString('utf8'));}
export async function saveConnection({workspaceId,provider,name=null,displayName=null,authType='api_key',credentials,scopes=[],metadata={},config={},expiresAt=null,actorUserId=null}){if(!provider)throw new Error('Integration provider is required');const connectionName=String(name||displayName||provider).trim();if(!connectionName)throw new Error('Integration connection name is required');if(!credentials||typeof credentials!=='object')throw new Error('Integration credentials are required');validatePublicMetadata(config,'config');validatePublicMetadata(metadata,'metadata');const encrypted=await encryptCredentials(credentials);return withTransaction(async client=>{const connection=(await client.query('insert into integration_connections (id,workspace_id,provider,display_name,encrypted_credentials,config,auth_type,scopes,status,metadata,expires_at) values ($1,$2,$3,$4,$5,$6::jsonb,$7,$8::jsonb,$9,$10::jsonb,$11) returning id,workspace_id,provider,display_name,config,auth_type,scopes,status,metadata,expires_at,created_at,updated_at',[randomUUID(),workspaceId,provider,displayName||connectionName,encrypted,JSON.stringify(config),authType,JSON.stringify(scopes),'active',JSON.stringify(metadata),expiresAt])).rows[0];await client.query('insert into audit_events (id,workspace_id,event_type,actor_type,action,metadata) values ($1,$2,$3,$4,$5,$6::jsonb)',[randomUUID(),workspaceId,'integration.created','user','integration.create',JSON.stringify({connectionId:connection.id,provider,displayName:connection.display_name,userId:actorUserId})]);return connection;});}
export async function revokeConnection({workspaceId,connectionId,actorUserId=null}){if(!connectionId)throw new Error('connectionId is required');return withTransaction(async client=>{const connection=(await client.query("update integration_connections set status='revoked',updated_at=now() where id=$1 and workspace_id=$2 returning id,workspace_id,provider,display_name,config,auth_type,scopes,status,metadata,expires_at,created_at,updated_at",[connectionId,workspaceId])).rows[0];if(!connection)throw Object.assign(new Error('Integration connection not found'),{status:404});await client.query('insert into audit_events (id,workspace_id,event_type,actor_type,action,metadata) values ($1,$2,$3,$4,$5,$6::jsonb)',[randomUUID(),workspaceId,'integration.revoked','user','integration.revoke',JSON.stringify({connectionId:connection.id,provider:connection.provider,displayName:connection.display_name,userId:actorUserId})]);return connection;});}
export async function listConnections(workspaceId){return (await query('select id,workspace_id,provider,display_name,config,auth_type,scopes,status,metadata,expires_at,created_at,updated_at from integration_connections where workspace_id=$1 order by created_at desc',[workspaceId])).rows;}
export async function getConnectionCredentials({workspaceId,connectionId,provider=null}){const row=(await query('select id,workspace_id,provider,display_name,encrypted_credentials,config,status,expires_at from integration_connections where id=$1 and workspace_id=$2 limit 1',[connectionId,workspaceId])).rows[0];if(!row)throw Object.assign(new Error('Integration connection not found'),{status:404});if(provider&&row.provider!==provider)throw new Error('Integration provider mismatch');if(row.status!=='active')throw new Error('Integration connection is not active');if(row.expires_at&&new Date(row.expires_at).getTime()<=Date.now())throw new Error('Integration connection has expired');return {...row,credentials:await decryptCredentials(row.encrypted_credentials)};}
export async function logIntegrationAction({workspaceId,taskId=null,employeeId=null,connectionId=null,provider,action,status,requestMeta={},responseMeta={}}){await query('insert into integration_action_logs(id,workspace_id,task_id,employee_id,connection_id,provider,action,status,request_meta,response_meta,completed_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10::jsonb,now())',[randomUUID(),workspaceId,taskId,employeeId,connectionId,provider,action,status,JSON.stringify(requestMeta),JSON.stringify(responseMeta)]);}
