import http from 'node:http';
import { createEmployee, listEmployees, getEmployee, createTask, listTasks, getTask, createApproval, decideApproval, listApprovals, listAudit, getWorkspaceAccess, listDepartments, createDepartment, listEmployeeGoals, createEmployeeGoal, listEmployeeKnowledge, createEmployeeKnowledge, listTaskComments, createTaskComment, listHandoffs, createHandoff } from './workforce-repository.js';
import { bootstrapWorkspace, getUserByAuthId, listUserWorkspaces } from './onboarding-repository.js';
import { runEmployeeTask, executeApprovedTask } from './agent-runtime.js';
import { planEmployeeTask } from './brain-orchestrator.js';
import { listTools } from './tool-registry.js';
import { saveConnection, listConnections, revokeConnection } from './credentials-vault.js';
import { getHealth } from './health.js';
import { getOpsSnapshot } from './ops-runtime.js';
import { rateLimit } from './rate-limit.js';
import { requestContext } from './request-context.js';
import { closeDb, query } from './db.js';
import { listIndustryPacks, provisionIndustryPack } from './industry-provisioning.js';
import './integrations/index.js';
const port=process.env.PORT||4000;
const supabaseUrl=process.env.SUPABASE_URL||'https://cqmwwrrmmqmgpnhnuxyu.supabase.co';
const supabaseKey=process.env.SUPABASE_ANON_KEY||process.env.SUPABASE_PUBLISHABLE_KEY||'sb_publishable_U12modLyDRQWV2sNAJHiqg_vJPOSoOz';
const allowedOrigins=new Set((process.env.CORS_ORIGINS||'').split(',').map(v=>v.trim()).filter(Boolean)); const limiter=rateLimit({windowMs:60_000,max:Number(process.env.RATE_LIMIT_PER_MINUTE||120)});
const json=(res,code,data,origin='',requestId='')=>{const cors=origin&&allowedOrigins.has(origin)?origin:'null';res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':cors,'Vary':'Origin','Access-Control-Allow-Methods':'GET,POST,DELETE,OPTIONS','Access-Control-Allow-Headers':'Authorization,Content-Type,X-Request-Id','X-Request-Id':requestId,'X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'no-referrer','Permissions-Policy':'camera=(),microphone=(),geolocation=()'});res.end(JSON.stringify(data));};
const body=req=>new Promise((resolve,reject)=>{let raw='';req.on('data',c=>{raw+=c;if(raw.length>1_000_000){reject(Object.assign(new Error('Request body too large'),{status:413}));req.destroy();}});req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{})}catch{reject(Object.assign(new Error('Invalid JSON body'),{status:400}))}});});
async function supabaseGetUser(accessToken){const response=await fetch(`${supabaseUrl}/auth/v1/user`,{headers:{apikey:supabaseKey,Authorization:`Bearer ${accessToken}`}});if(!response.ok)return null;return response.json();}
async function authIdentity(req){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return null;const data=await supabaseGetUser(h.slice(7));if(!data?.id)return null;return {authId:data.id,email:data.email||'',name:data.user_metadata?.full_name||data.user_metadata?.name||data.email?.split('@')[0]||'Enjaz user'};}
async function authUser(req){const identity=await authIdentity(req);if(!identity)return null;const profile=await getUserByAuthId(identity.authId);if(!profile)return null;return {authId:identity.authId,id:profile.id,organizationId:profile.organization_id};}
async function requireWorkspace(req,workspaceId){const user=await authUser(req);if(!user)throw Object.assign(new Error('Authentication required'),{status:401});if(!workspaceId)throw Object.assign(new Error('workspaceId is required'),{status:400});const access=await getWorkspaceAccess(workspaceId,user.id);if(!access)throw Object.assign(new Error('Workspace access denied'),{status:403});return {...user,role:access.role};}
function requireManager(user){if(!['owner','admin','manager'].includes(user.role))throw Object.assign(new Error('Manager permission required'),{status:403});}
async function listWorkflows(workspaceId){const {rows}=await query(`select g.id,g.task_id,g.employee_id,g.goal,g.status,g.created_at,g.updated_at,count(s.id)::int as step_count,count(s.id) filter (where s.status='succeeded')::int as succeeded_steps from execution_graphs g left join execution_steps s on s.graph_id=g.id where g.workspace_id=$1 group by g.id order by g.created_at desc limit 100`,[workspaceId]);return rows;}
async function getRuntimeSummary(workspaceId){const summary=(await query('select * from workspace_runtime_summary where workspace_id=$1',[workspaceId])).rows[0]||{workspace_id:workspaceId,runs:0,successful_runs:0,failed_runs:0,avg_latency_ms:null,cost_cents:0,last_run_at:null};const recent=(await query("select provider,status,latency_ms,cost_cents,error_code,created_at from runtime_metrics where workspace_id=$1 order by created_at desc limit 50",[workspaceId])).rows;return {summary,recent};}
const publicError=(error,status)=>{if(status>=500){console.error(error);return 'Internal server error';}return error?.message||'Request failed';};
export const server=http.createServer(async(req,res)=>{const context=requestContext(req),origin=req.headers.origin||'';if(req.method==='OPTIONS')return json(res,204,{},origin,context.id);const rl=limiter(req.socket.remoteAddress||'unknown');if(!rl.allowed){res.setHeader('Retry-After',Math.ceil((rl.resetAt-Date.now())/1000));return json(res,429,{error:'Rate limit exceeded',requestId:context.id},origin,context.id);}const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);try{
if(req.method==='GET'&&url.pathname==='/health'){const h=await getHealth();return json(res,h.status==='unhealthy'?503:200,h,origin,context.id);}
if(req.method==='GET'&&url.pathname==='/ops/health'){const user=await authUser(req);if(!user)throw Object.assign(new Error('Authentication required'),{status:401});const workspaceId=url.searchParams.get('workspaceId');if(!workspaceId)throw Object.assign(new Error('workspaceId is required'),{status:400});const access=await getWorkspaceAccess(workspaceId,user.id);if(!access)throw Object.assign(new Error('Workspace access denied'),{status:403});requireManager({...user,role:access.role});return json(res,200,await getOpsSnapshot({workspaceId}),origin,context.id);}
if(req.method==='GET'&&url.pathname==='/api/v1')return json(res,200,{name:'ENJAZ API',version:'0.9.0',storage:'postgresql',auth:'supabase',runtime:'enabled',integrations:'enabled',onboarding:'enabled',workforce:'enabled',aiProvider:process.env.ENJAZ_MODEL_PROVIDER||'deterministic',aiLive:Boolean(process.env.OPENAI_API_KEY),status:'ready'},origin,context.id);
if(req.method==='GET'&&url.pathname==='/api/v1/auth/me'){const identity=await authIdentity(req);if(!identity)throw Object.assign(new Error('Authentication required'),{status:401});const profile=await getUserByAuthId(identity.authId);const workspaces=profile?await listUserWorkspaces(profile.id):[];return json(res,200,{data:{identity,profile,workspaces}},origin,context.id);}
if(req.method==='POST'&&url.pathname==='/api/v1/onboarding/bootstrap'){const identity=await authIdentity(req);if(!identity)throw Object.assign(new Error('Authentication required'),{status:401});const input=await body(req);const result=await bootstrapWorkspace({authUserId:identity.authId,email:identity.email,name:input.name||identity.name,organizationName:input.organizationName,workspaceName:input.workspaceName});return json(res,result.created?201:200,{data:result},origin,context.id);}
const workspaceId=url.searchParams.get('workspaceId');const user=await requireWorkspace(req,workspaceId);
if(req.method==='GET'&&url.pathname==='/api/v1/industry-packs')return json(res,200,{data:listIndustryPacks()},origin,context.id);
const industryMatch=url.pathname.match(/^\/api\/v1\/industry-packs\/([^/]+)\/provision$/);if(industryMatch&&req.method==='POST'){requireManager(user);return json(res,201,{data:await provisionIndustryPack({workspaceId,pack:industryMatch[1],actorUserId:user.id})},origin,context.id);}
if(req.method==='GET'&&url.pathname==='/api/v1/runtime/summary')return json(res,200,{data:await getRuntimeSummary(workspaceId)},origin,context.id);
if(req.method==='GET'&&url.pathname==='/api/v1/runtime/ops'){requireManager(user);return json(res,200,{data:await getOpsSnapshot({workspaceId})},origin,context.id);}
if(req.method==='GET'&&url.pathname==='/api/v1/tools')return json(res,200,{data:listTools()},origin,context.id);
if(req.method==='GET'&&url.pathname==='/api/v1/departments')return json(res,200,{data:await listDepartments(workspaceId)},origin,context.id);
if(req.method==='POST'&&url.pathname==='/api/v1/departments'){requireManager(user);return json(res,201,{data:await createDepartment({...await body(req),workspaceId})},origin,context.id);}
if(req.method==='GET'&&url.pathname==='/api/v1/employees')return json(res,200,{data:await listEmployees(workspaceId)},origin,context.id);
if(req.method==='POST'&&url.pathname==='/api/v1/employees'){requireManager(user);return json(res,201,{data:await createEmployee({...await body(req),workspaceId})},origin,context.id);}
const employeeGoals=url.pathname.match(/^\/api\/v1\/employees\/([^/]+)\/goals$/);if(employeeGoals&&req.method==='GET')return json(res,200,{data:await listEmployeeGoals(workspaceId,employeeGoals[1])},origin,context.id);if(employeeGoals&&req.method==='POST'){requireManager(user);return json(res,201,{data:await createEmployeeGoal({...await body(req),workspaceId,employeeId:employeeGoals[1]})},origin,context.id);}
const employeeKnowledge=url.pathname.match(/^\/api\/v1\/employees\/([^/]+)\/knowledge$/);if(employeeKnowledge&&req.method==='GET')return json(res,200,{data:await listEmployeeKnowledge(workspaceId,employeeKnowledge[1])},origin,context.id);if(employeeKnowledge&&req.method==='POST'){requireManager(user);return json(res,201,{data:await createEmployeeKnowledge({...await body(req),workspaceId,employeeId:employeeKnowledge[1]})},origin,context.id);}
if(req.method==='GET'&&url.pathname==='/api/v1/tasks')return json(res,200,{data:await listTasks(workspaceId)},origin,context.id);
if(req.method==='POST'&&url.pathname==='/api/v1/tasks')return json(res,201,{data:await createTask({...await body(req),workspaceId})},origin,context.id);
const taskComments=url.pathname.match(/^\/api\/v1\/tasks\/([^/]+)\/comments$/);if(taskComments&&req.method==='GET')return json(res,200,{data:await listTaskComments(workspaceId,taskComments[1])},origin,context.id);if(taskComments&&req.method==='POST'){const input=await body(req);return json(res,201,{data:await createTaskComment({...input,workspaceId,taskId:taskComments[1],authorUserId:user.id})},origin,context.id);}
if(req.method==='POST'&&url.pathname.match(/^\/api\/v1\/tasks\/[^/]+\/plan$/)){requireManager(user);const id=url.pathname.split('/')[4];const task=await getTask(id,workspaceId);if(!task)throw Object.assign(new Error('Task not found'),{status:404});const employee=await getEmployee(task.employee_id,workspaceId);if(!employee)throw Object.assign(new Error('Employee not found'),{status:404});const input=await body(req);const goal=String(input.goal||task.objective||employee.goal||'').trim();if(!goal)throw Object.assign(new Error('A goal is required to plan this task'),{status:400});const provider=input.provider||process.env.ENJAZ_MODEL_PROVIDER||'deterministic';return json(res,200,{data:await planEmployeeTask({employee,workspaceId,employeeId:employee.id,taskId:task.id,goal,provider})},origin,context.id);}
if(req.method==='POST'&&url.pathname.match(/^\/api\/v1\/tasks\/[^/]+\/run$/)){requireManager(user);const id=url.pathname.split('/')[4];const input=await body(req);return json(res,200,{data:await runEmployeeTask({workspaceId,taskId:id,employeeId:input.employeeId,action:input.action||'data.analyze',input:input.input||{}})},origin,context.id);}
const handoffs=url.pathname==='/api/v1/handoffs';if(handoffs&&req.method==='GET')return json(res,200,{data:await listHandoffs(workspaceId,url.searchParams.get('taskId'))},origin,context.id);if(handoffs&&req.method==='POST'){requireManager(user);return json(res,201,{data:await createHandoff({...await body(req),workspaceId})},origin,context.id);}
if(req.method==='GET'&&url.pathname==='/api/v1/workflows')return json(res,200,{data:await listWorkflows(workspaceId)},origin,context.id);
if(req.method==='GET'&&url.pathname==='/api/v1/approvals')return json(res,200,{data:await listApprovals(workspaceId)},origin,context.id);
if(req.method==='POST'&&url.pathname==='/api/v1/approvals'){requireManager(user);return json(res,201,{data:await createApproval({...await body(req),workspaceId})},origin,context.id);}
const match=url.pathname.match(/^\/api\/v1\/approvals\/([^/]+)\/(approve|reject)$/);if(req.method==='POST'&&match){requireManager(user);const approvalId=match[1],status=match[2]==='approve'?'approved':'rejected';const approval=await decideApproval(approvalId,workspaceId,status,user.id);if(status==='approved')return json(res,200,{data:await executeApprovedTask({workspaceId,approvalId,actorUserId:user.id})},origin,context.id);return json(res,200,{data:approval},origin,context.id);}
if(req.method==='GET'&&url.pathname==='/api/v1/integrations')return json(res,200,{data:await listConnections(workspaceId)},origin,context.id);
if(req.method==='POST'&&url.pathname==='/api/v1/integrations'){requireManager(user);const input=await body(req);return json(res,201,{data:await saveConnection({...input,workspaceId,actorUserId:user.id})},origin,context.id);}
const integrationMatch=url.pathname.match(/^\/api\/v1\/integrations\/([^/]+)\/revoke$/);if(req.method==='DELETE'&&integrationMatch){requireManager(user);return json(res,200,{data:await revokeConnection({workspaceId,connectionId:integrationMatch[1],actorUserId:user.id})},origin,context.id);}
if(req.method==='GET'&&url.pathname==='/api/v1/audit')return json(res,200,{data:await listAudit(workspaceId)},origin,context.id);
return json(res,404,{error:'Not Found',requestId:context.id},origin,context.id);
}catch(e){const status=e.status||400;return json(res,status,{error:publicError(e,status),requestId:context.id},origin,context.id);}});
server.requestTimeout=30_000;server.headersTimeout=15_000;server.keepAliveTimeout=5_000;server.maxRequestsPerSocket=1000;
let shuttingDown=false;async function shutdown(signal){if(shuttingDown)return;shuttingDown=true;console.log(`ENJAZ API shutting down (${signal})`);server.close(async()=>{try{await closeDb();process.exit(0);}catch(error){console.error('Database shutdown failed',error);process.exit(1);}});setTimeout(()=>process.exit(1),10_000).unref();}process.once('SIGTERM',()=>void shutdown('SIGTERM'));process.once('SIGINT',()=>void shutdown('SIGINT'));
if(process.env.ENJAZ_VERCEL!=='1' && process.env.VERCEL!=='1')server.listen(port,()=>console.log(`ENJAZ API listening on ${port}`));
