import { randomUUID } from 'node:crypto';
import { query } from './db.js';

export async function enqueueJob({workspaceId,jobType,payload={},availableAt=null,maxAttempts=3,client=null,idempotencyKey=null}){const id=randomUUID();const db=client||{query};if(idempotencyKey){const existing=await db.query("select * from job_queue where workspace_id=$1 and job_type=$2 and payload->>'idempotencyKey'=$3 limit 1",[workspaceId,jobType,idempotencyKey]);if(existing.rowCount)return existing.rows[0];payload={...payload,idempotencyKey};}return (await db.query('insert into job_queue(id,workspace_id,job_type,payload,max_attempts,available_at) values($1,$2,$3,$4::jsonb,$5,coalesce($6,now())) returning *',[id,workspaceId,jobType,JSON.stringify(payload),maxAttempts,availableAt])).rows[0];}
export async function claimJob({workerId}){const r=await query(`with candidate as (select id from job_queue where status='queued' and available_at<=now() order by available_at,created_at for update skip locked limit 1) update job_queue j set status='running',attempts=attempts+1,locked_at=now(),locked_by=$1,updated_at=now() from candidate c where j.id=c.id returning j.*`,[workerId]);return r.rows[0]||null;}
export async function renewJobLease({jobId,workerId}){return (await query("update job_queue set locked_at=now(),updated_at=now() where id=$1 and status='running' and locked_by=$2 returning id",[jobId,workerId])).rowCount>0;}
export async function completeJob({jobId,workerId,result}){return (await query("update job_queue set status='succeeded',result=$1::jsonb,locked_at=null,locked_by=null,updated_at=now() where id=$2 and status='running' and locked_by=$3 returning *",[JSON.stringify(result),jobId,workerId])).rows[0]||null;}
export async function failJob({jobId,workerId,error}){return (await query("update job_queue set status=case when attempts>=max_attempts then 'dead' else 'queued' end,available_at=case when attempts>=max_attempts then available_at else now()+least(interval '10 minutes', interval '1 second' * power(2,attempts)) end,last_error=$1,locked_at=null,locked_by=null,updated_at=now() where id=$2 and status='running' and locked_by=$3 returning *",[error?.message||String(error),jobId,workerId])).rows[0]||null;}
export async function recoverStaleJobs({leaseSeconds=120}){return (await query("update job_queue set status='queued',locked_at=null,locked_by=null,available_at=now(),updated_at=now() where status='running' and locked_at<now()-make_interval(secs=>$1) returning id",[leaseSeconds])).rows;}
export async function cancelJob({jobId,workspaceId,reason='cancelled by operator'}){return (await query("update job_queue set status='cancelled',last_error=$1,locked_at=null,locked_by=null,updated_at=now() where id=$2 and workspace_id=$3 and status in ('queued','running') returning *",[reason,jobId,workspaceId])).rows[0]||null;}
export async function deadLetterJobs({workspaceId,limit=100}){return (await query("select id,job_type,attempts,max_attempts,last_error,updated_at from job_queue where workspace_id=$1 and status='dead' order by updated_at desc limit $2",[workspaceId,Math.min(1000,Math.max(1,limit))])).rows;}
